/* Rugby Legacy v0.8 — PRM 2015 resemblance pass: camera, formations, phase motion, match HUD */
(()=>{
const V='0.8.0';
if(typeof RL_DATA!=='undefined') RL_DATA.version=V;
if(typeof DB!=='undefined') DB.version=V;
state.prm8Camera=state.prm8Camera||'tv';
state.prm8Speed=state.prm8Speed||1;
let loop=0,lastEventIndex=-1,phaseStart=performance.now();
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const lerp=(a,b,t)=>a+(b-a)*t;
const smooth=t=>t*t*(3-2*t);
const key=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
const P=['PIL','TAL','PIL','2L','2L','3L','3L','3L','9','10','AIL','C','C','AIL','AR'];
function current(){let m=state.match;if(!m)return null;return m.events[Math.max(0,m.index-1)]||{x:50,y:50,type:"COUP D'ENVOI",home:true,text:'Coup d’envoi',m:0}}
function previous(){let m=state.match;if(!m)return null;return m.events[Math.max(0,m.index-2)]||current()}
function fifteen(c){if(state.save&&c.id===state.save.clubId&&state.save.lineup?.length===15)return state.save.lineup.map(id=>c.players.find(p=>p.id===id)).filter(Boolean);let used=new Set(),out=[];for(const pos of P){let pool=c.players.filter(p=>!used.has(p.id)&&p.pos===pos).sort((a,b)=>(b.ca||0)-(a.ca||0));if(!pool.length)pool=c.players.filter(p=>!used.has(p.id)).sort((a,b)=>(b.ca||0)-(a.ca||0));if(pool[0]){used.add(pool[0].id);out.push(pool[0])}}return out}
function prof(p){let pos=p?.pos||'C',h=(p?.height||185)/185,w=(p?.weight||95)/95;let bulk=['PIL','TAL'].includes(pos)?1.18:['2L','3L'].includes(pos)?1.07:['9','AIL'].includes(pos)?.92:1;return{h:clamp(h,.88,1.16),w:clamp(w*bulk,.82,1.30)}}
function shape(home,i,e){let bx=e?.x??50,by=e?.y??50,t=key(e?.type),att=e?.home===home,dir=home?1:-1,pack=i<8,x=50,y=50;
 if(t.includes('MELEE')){if(pack){const row=i<3?0:i<7?1:2,idx=i<3?i:i<7?i-3:0;const cnt=i<3?3:i<7?4:1;x=bx-dir*(1.2+row*2.2);y=by+(idx-(cnt-1)/2)*3.4}else if(i===8){x=bx-dir*7;y=by+5}else{x=bx-dir*(10+(i-9)*4);y=14+(i-9)*14}}
 else if(t.includes('TOUCHE')){let edge=by<50?9:91,sg=by<50?1:-1;if(pack){x=bx+(i%2?.9:-.9);y=edge+sg*(6+i*4.6)}else if(i===8){x=bx-dir*5;y=edge+sg*18}else{x=bx-dir*(8+(i-9)*3.8);y=16+(i-9)*13}}
 else if(t.includes('RUCK')||t.includes('TURNOVER')||t.includes('PERCUSSION')){if(pack&&i<4){x=bx-dir*(1.2+Math.floor(i/2)*1.8);y=by+(i%2?2.2:-2.2)}else if(pack){x=bx-dir*(5+(i-3)*2.4);y=by+(i-5.5)*6.5}else if(i===8){x=bx-dir*5.5;y=by+3}else{x=bx-dir*(9+(i-9)*4);y=10+(i-9)*14}}
 else if(t.includes('PIED')||t.includes('DROP')){if(i===9){x=bx-dir*4;y=by}else if(i===8){x=bx-dir*7;y=by+4}else{x=(att?bx-dir*(7+(i%5)*4):bx+dir*(10+(i%5)*3));y=8+(i*6.1)%84}}
 else if(t.includes('ESSAI')){x=att?bx-dir*(1+i*1.1):bx+dir*(5+i*.8);y=8+(i*6.2)%84}
 else {if(pack){let pod=i<3?0:i<6?1:2,slot=i<3?i:i<6?i-3:i-6;x=att?bx-dir*(4+pod*5):bx+dir*(6+pod*4);y=by+(slot-1)*7+pod*5}else if(i===8){x=bx-dir*5;y=by+2}else{x=att?bx-dir*(10+(i-9)*4.5):bx+dir*(9+(i-9)*3.8);y=10+(i-9)*15}}
 return[clamp(x,3,97),clamp(y,5,95)]}
function canvasInfo(){let c=document.getElementById('prm8-canvas');if(!c)return null;let r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,1.7),w=Math.max(320,r.width),h=Math.max(220,r.height);if(c.width!==Math.round(w*d)||c.height!==Math.round(h*d)){c.width=Math.round(w*d);c.height=Math.round(h*d)}let ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);return{c,ctx,w,h}}
function projection(px,py,w,h){let e=current(),focus=state.prm8Camera==='follow'?((e?.x??50)-50)*.16:0,x=clamp(px-focus,0,100)/100,y=py/100;let topY=h*.18,botY=h*.91,tl=w*.12,tr=w*.90,bl=w*.015,br=w*.985;if(state.prm8Camera==='high'){topY=h*.12;tl=w*.08;tr=w*.92}if(state.prm8Camera==='sideline'){topY=h*.22;tl=w*.18;tr=w*.82}let yy=lerp(topY,botY,y),l=lerp(tl,bl,y),r=lerp(tr,br,y);return{x:lerp(l,r,x),y:yy,s:lerp(.50,1.25,y)}}
function poly(ctx,p,fill,stroke,lw=1){ctx.beginPath();p.forEach((q,i)=>i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}}
function ln(ctx,a,b,c,lw=1,d=[]){ctx.save();ctx.strokeStyle=c;ctx.lineWidth=lw;ctx.setLineDash(d);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore()}
function stadium(ctx,w,h){ctx.clearRect(0,0,w,h);let sky=ctx.createLinearGradient(0,0,0,h*.23);sky.addColorStop(0,'#101a16');sky.addColorStop(1,'#2a302d');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h*.24);ctx.fillStyle='#202522';ctx.fillRect(0,h*.03,w,h*.115);ctx.fillStyle='#0e1210';ctx.fillRect(0,h*.145,w,h*.03);for(let y=0;y<9;y++)for(let x=0;x<w;x+=8){if((x/8+y)%3<2){ctx.fillStyle=['#b4b7ad','#6f7b74','#b49452','#d2d1c7'][((x/8+y)|0)%4];ctx.fillRect(x+(y%2)*3,10+y*4,2,2)}}ctx.fillStyle='#0b0d0c';ctx.fillRect(0,h*.173,w,h*.025);for(let x=0;x<w;x+=105){ctx.fillStyle=x%210?'#d7bd67':'#e1e3dc';ctx.font='bold 8px Arial';ctx.fillText(x%210?'RUGBY LEGACY':'SPORT',x+6,h*.19)}let p1=projection(0,0,w,h),p2=projection(100,0,w,h),p3=projection(100,100,w,h),p4=projection(0,100,w,h);let g=ctx.createLinearGradient(0,p1.y,0,p4.y);g.addColorStop(0,'#4d843d');g.addColorStop(.55,'#559445');g.addColorStop(1,'#397331');poly(ctx,[p1,p2,p3,p4],g,'rgba(255,255,255,.8)',1.2);for(let i=0;i<10;i+=2){poly(ctx,[projection(i*10,0,w,h),projection((i+1)*10,0,w,h),projection((i+1)*10,100,w,h),projection(i*10,100,w,h)],'rgba(255,255,255,.022)')}[0,22,40,50,60,78,100].forEach(v=>ln(ctx,projection(v,0,w,h),projection(v,100,w,h),'rgba(255,255,255,.72)',v===50?1.4:.85));[10,90].forEach(v=>ln(ctx,projection(0,v,w,h),projection(100,v,w,h),'rgba(255,255,255,.35)',.7,[4,5]));posts(ctx,3,50,w,h);posts(ctx,97,50,w,h)}
function posts(ctx,x,y,w,h){let p=projection(x,y,w,h),s=p.s;ctx.strokeStyle='#f0efe5';ctx.lineWidth=Math.max(1,1.3*s);ctx.beginPath();ctx.moveTo(p.x-5*s,p.y);ctx.lineTo(p.x-5*s,p.y-34*s);ctx.moveTo(p.x+5*s,p.y);ctx.lineTo(p.x+5*s,p.y-34*s);ctx.moveTo(p.x-5*s,p.y-22*s);ctx.lineTo(p.x+5*s,p.y-22*s);ctx.stroke()}
function pose(t,att,i){t=key(t);if(t.includes('MELEE'))return i<8?'scrum':'ready';if(t.includes('TOUCHE'))return i===3||i===4?'jump':'ready';if(t.includes('RUCK')||t.includes('TURNOVER'))return i<4?'ruck':'ready';if(t.includes('PERCUSSION'))return i%5===0?'tackle':'run';if(t.includes('ESSAI'))return att&&i%4===0?'dive':'run';if(t.includes('PIED')||t.includes('DROP'))return i===9?'kick':'chase';return'run'}
function kit(home){return home?{j:'#d2a333',s:'#17201b',sock:'#d2a333',num:'#fff0b6'}:{j:'#b8242f',s:'#ededeb',sock:'#b8242f',num:'#ffffff'}}
function player(ctx,p,n,home,pt,type,att,i,ts){let c=kit(home),pr=prof(p),sc=pt.s*pr.h,b=pr.w,po=pose(type,att,i),phase=(ts*.015+i),run=po==='run'||po==='chase',stride=run?Math.sin(phase)*4:po==='kick'?6:0,bob=run?Math.abs(Math.sin(phase))*1.4:0,lean=po==='scrum'?.68:po==='ruck'?.5:po==='tackle'?.55:po==='dive'?1.0:po==='kick'?.18:.10,x=pt.x,y=pt.y+bob*sc;ctx.save();ctx.fillStyle='rgba(0,0,0,.32)';ctx.beginPath();ctx.ellipse(x+2*sc,y+5*sc,6*b*sc,2.3*sc,0,0,Math.PI*2);ctx.fill();ctx.translate(x,y);ctx.rotate((home?1:-1)*lean);ctx.lineCap='round';ctx.strokeStyle='#1b201d';ctx.lineWidth=2.1*sc;ctx.beginPath();ctx.moveTo(-2.2*b*sc,-1*sc);ctx.lineTo((-2.4-stride)*b*sc,8.5*sc);ctx.moveTo(2.2*b*sc,-1*sc);ctx.lineTo((2.4+stride)*b*sc,8.5*sc);ctx.stroke();ctx.fillStyle=c.s;ctx.fillRect(-4.8*b*sc,-3*sc,9.6*b*sc,4.5*sc);let grad=ctx.createLinearGradient(-5*sc,-15*sc,5*sc,-4*sc);grad.addColorStop(0,c.j);grad.addColorStop(1,home?'#a77818':'#7f1720');ctx.fillStyle=grad;ctx.beginPath();ctx.moveTo(-4.6*b*sc,-14*sc);ctx.quadraticCurveTo(0,-16*sc,4.6*b*sc,-14*sc);ctx.lineTo(5.3*b*sc,-3*sc);ctx.lineTo(-5.3*b*sc,-3*sc);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(0,0,0,.32)';ctx.lineWidth=.6;ctx.stroke();ctx.fillStyle='#c88f68';ctx.beginPath();ctx.arc(0,-18*sc,3.15*sc,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#c88f68';ctx.lineWidth=2.0*sc;let arm=run?Math.sin(phase+1.6)*3.8:po==='scrum'||po==='ruck'?5.5:po==='tackle'?8:2.5;ctx.beginPath();ctx.moveTo(-4*b*sc,-11*sc);ctx.lineTo((-6-arm)*b*sc,-5*sc);ctx.moveTo(4*b*sc,-11*sc);ctx.lineTo((6+arm)*b*sc,-5*sc);ctx.stroke();if(sc>.58){ctx.fillStyle=c.num;ctx.font=`bold ${Math.max(5,6.2*sc)}px Arial`;ctx.textAlign='center';ctx.fillText(n,0,-7*sc)}ctx.restore()}
function ball(ctx,e,pr,w,h,ts){let p=projection(e?.x??50,e?.y??50,w,h),q=projection(pr?.x??50,pr?.y??50,w,h),age=Math.min(1,(performance.now()-phaseStart)/(600/state.prm8Speed)),u=smooth(age),x=lerp(q.x,p.x,u),y=lerp(q.y,p.y,u),t=key(e?.type);if(t.includes('PIED')||t.includes('DROP'))y-=Math.sin(Math.PI*u)*70;if(t.includes('PASSE'))y-=Math.sin(Math.PI*u)*18;ctx.save();ctx.translate(x,y);ctx.rotate(ts*.012);ctx.fillStyle='#eee4c7';ctx.strokeStyle='#473522';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(0,0,5*p.s,2.5*p.s,.25,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}
function effects(ctx,e,w,h,ts){let t=key(e?.type),p=projection(e?.x??50,e?.y??50,w,h);if(t.includes('RUCK')||t.includes('TURNOVER')){ctx.fillStyle='rgba(214,199,162,.14)';ctx.beginPath();ctx.ellipse(p.x,p.y,25*p.s,8*p.s,0,0,Math.PI*2);ctx.fill()}if(t.includes('MELEE')){ctx.strokeStyle='rgba(247,230,177,.35)';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(p.x,p.y,25*p.s,10*p.s,0,0,Math.PI*2);ctx.stroke()}if(t.includes('ESSAI')){ctx.save();ctx.textAlign='center';ctx.font='900 36px Arial';ctx.fillStyle='rgba(248,226,151,.95)';ctx.shadowColor='#000';ctx.shadowBlur=10;ctx.fillText('ESSAI',w/2,h*.30);ctx.restore()}}
function frame(ts){let inf=canvasInfo();if(!inf){loop=requestAnimationFrame(frame);return}let{ctx,w,h}=inf,m=state.match,e=current(),pr=previous();if(m&&m.index!==lastEventIndex){lastEventIndex=m.index;phaseStart=performance.now()}stadium(ctx,w,h);if(m){let hc=club(m.homeId),ac=club(m.awayId),hl=fifteen(hc),al=fifteen(ac),age=Math.min(1,(performance.now()-phaseStart)/(760/state.prm8Speed)),u=smooth(age),actors=[];for(let i=0;i<15;i++){let a0=shape(true,i,pr),a1=shape(true,i,e),b0=shape(false,i,pr),b1=shape(false,i,e),ah=[lerp(a0[0],a1[0],u),lerp(a0[1],a1[1],u)],bh=[lerp(b0[0],b1[0],u),lerp(b0[1],b1[1],u)];actors.push({p:hl[i],n:i+1,h:true,pt:projection(ah[0],ah[1],w,h),a:e?.home===true,i},{p:al[i],n:i+1,h:false,pt:projection(bh[0],bh[1],w,h),a:e?.home===false,i})}actors.sort((a,b)=>a.pt.y-b.pt.y).forEach(o=>player(ctx,o.p,o.n,o.h,o.pt,e?.type,o.a,o.i,ts));effects(ctx,e,w,h,ts);ball(ctx,e,pr,w,h,ts)}loop=requestAnimationFrame(frame)}
function side(c,home){let arr=fifteen(c);return `<div class="prm8-side-title"><span>${home?'DOM':'EXT'}</span><b>${c.short}</b></div>${arr.map((p,i)=>`<div class="prm8-p"><i class="${home?'h':'a'}">${i+1}</i><span><b>${p?.last||'—'}</b><small>${p?.pos||''}</small></span><em>${p?.ca||''}</em></div>`).join('')}`}
window.setPrm8Cam=c=>{state.prm8Camera=c;render()};
window.setPrm8Speed=s=>{state.prm8Speed=s;state.matchSpeed=s;restartLive?.();render()};
window.prm8Tactic=(k,v)=>{if(window.liveTacticChange)liveTacticChange(k,v)};
function tact(label,k,vals){let cur=state.save?.tactics?.[k]||'';return `<label><span>${label}</span><select onchange="prm8Tactic('${k}',this.value)">${vals.map(v=>`<option ${v===cur?'selected':''}>${v}</option>`).join('')}</select></label>`}
matchView=function(){let m=state.match,h=club(m.homeId),a=club(m.awayId),e=current(),s=m.stats||{},hp=Math.round(s.possH||50),ap=100-hp;cancelAnimationFrame(loop);setTimeout(()=>{cancelAnimationFrame(loop);loop=requestAnimationFrame(frame)},0);return `<div class="prm8"><div class="prm8-scorebar"><div class="team"><b>${h.short}</b><span>${h.name}</span></div><div class="score"><small>${m.minute}'</small><strong>${m.hs}<i>:</i>${m.as}</strong><em>${m.finished?'TERMINÉ':'LIVE'}</em></div><div class="team right"><span>${a.name}</span><b>${a.short}</b></div></div><div class="prm8-viewbar"><button class="${state.view==='2d'?'on':''}" onclick="state.view='2d';render()">2D</button><button class="${state.view==='3d'?'on':''}" onclick="state.view='3d';render()">3D PRM</button>${state.view==='3d'?`<button class="${state.prm8Camera==='tv'?'on':''}" onclick="setPrm8Cam('tv')">TV</button><button class="${state.prm8Camera==='follow'?'on':''}" onclick="setPrm8Cam('follow')">Suivi</button><button class="${state.prm8Camera==='high'?'on':''}" onclick="setPrm8Cam('high')">Haute</button><button class="${state.prm8Camera==='sideline'?'on':''}" onclick="setPrm8Cam('sideline')">Latérale</button>`:''}<button onclick="instantResult()">Résultat</button></div>${state.view==='3d'?`<div class="prm8-grid"><aside>${side(h,true)}</aside><section class="prm8-stage"><canvas id="prm8-canvas"></canvas><div class="prm8-phase"><b>${e?.type||"COUP D'ENVOI"}</b><span>${e?.text||''}</span></div></section><aside>${side(a,false)}</aside></div>`:`<div class="prm8-2d"><div id="pitch" class="v6-pitch">${matchDots()}</div></div>`}<div class="prm8-controls"><div class="transport"><button onclick="toggleLive()">${m.running?'Ⅱ':'▶'}</button><button onclick="stepMatch()">▸|</button>${[1,2,4].map(v=>`<button class="${state.prm8Speed===v?'on':''}" onclick="setPrm8Speed(${v})">×${v}</button>`).join('')}</div><div class="possession"><span>${h.short} ${hp}%</span><i><b style="width:${hp}%"></b></i><span>${ap}% ${a.short}</span></div></div><div class="prm8-tactics"><div class="group"><b>ATTAQUE</b><button onclick="prm8Tactic('attack','Jeu direct')">Avants</button><button onclick="prm8Tactic('attack','Équilibré')">Centres</button><button onclick="prm8Tactic('attack','Jeu au large')">Ailes</button><button onclick="prm8Tactic('attack','Équilibré')">Équilibre</button></div>${tact('Défense','defense',['Glissée','Montée agressive','Blitz','Inversée'])}${tact('Jeu au pied','kick',['Relance','Alternance','Occupation','Pression aérienne'])}${tact('Tempo','tempo',['Lent','Standard','Rapide','Très rapide'])}<button class="sub" onclick="toggleBenchV6?.()">Remplacements</button></div>${typeof benchBox==='function'?benchBox(h):''}${m.finished?`<div class="prm8-final"><b>${h.short} ${m.hs} – ${m.as} ${a.short}</b><button class="btn" onclick="commitMatch()">Continuer</button></div>`:''}</div>`};
render();
})();
