(()=>{'use strict';
const K='jlg-event-builder-v2';
const TYPE={mariage:'Mariage',anniversaire:'Anniversaire',seminaire:'Séminaire',association:'Association',autre:'Autre'};
const E=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const D=s=>s?new Date(s+'T12:00:00').toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric'}):'—';
const U=()=>`act_${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`;
const S=()=>{try{return JSON.parse(localStorage.getItem(K)||'{"events":[]}')}catch{return{events:[]}}};
const eventId=()=>((location.hash||'').match(/^#\/event\/([^/]+)/)||[])[1];
const EV=()=>S().events.find(x=>x.id===eventId());
function mutate(fn){const s=S(),e=s.events.find(x=>x.id===eventId());if(!e)return null;fn(e);localStorage.setItem(K,JSON.stringify(s));return e}
function baseActivity(e){return{id:U(),name:(e.options&&e.options[0])||TYPE[e.type]||'Activité',date:e.date||'',start:e.start||'',end:e.end||'',pax:Number(e.guestTarget)||0,place:e.place||'',accompanist:''}}
function program(e){const acts=Array.isArray(e.activitiesDetailed)&&e.activitiesDetailed.length?e.activitiesDetailed:[baseActivity(e)];return{startDate:e.eventStartDate||e.date||'',endDate:e.eventEndDate||e.date||'',activities:acts}}
function row(a={}){return `<tr data-act-row><td><input class="input" data-f="name" value="${E(a.name||'')}"></td><td><input class="input" data-f="date" type="date" value="${E(a.date||'')}"></td><td><input class="input" data-f="start" type="time" value="${E(a.start||'')}"></td><td><input class="input" data-f="end" type="time" value="${E(a.end||'')}"></td><td><input class="input" data-f="pax" type="number" min="0" value="${Number(a.pax)||0}"></td><td><input class="input" data-f="place" value="${E(a.place||'')}"></td><td><input class="input" data-f="accompanist" value="${E(a.accompanist||'')}"></td><td><button type="button" class="btn btn-ghost btn-sm" data-del-act>✕</button></td></tr>`}
function openProgram(){const e=EV();if(!e)return;const p=program(e),r=document.querySelector('#modal-root');r.innerHTML=`<div class="modal-backdrop"><div class="modal" style="max-width:1180px"><div class="modal-head"><h3>Dates & programme des activités</h3><button type="button" class="btn btn-ghost btn-sm" data-close-act>✕</button></div><form id="activity-program-form"><div class="modal-body"><div class="form-grid"><div class="field"><label>Date de début de l’événement</label><input class="input" name="eventStartDate" type="date" value="${E(p.startDate)}"></div><div class="field"><label>Date de fin de l’événement</label><input class="input" name="eventEndDate" type="date" value="${E(p.endDate)}"></div></div><div class="divider"></div><h3 style="color:var(--navy)">Programme par activité</h3><p class="text-muted">Chaque activité peut avoir sa propre date, ses propres horaires et son propre nombre de pax.</p><div class="table-wrap"><table class="data-table" style="min-width:1050px"><thead><tr><th>Activité</th><th>Date</th><th>Début</th><th>Fin</th><th>Pax</th><th>Lieu</th><th>Accompagnant / responsable</th><th></th></tr></thead><tbody id="activity-program-rows">${p.activities.map(row).join('')}</tbody></table></div><button type="button" class="btn btn-light btn-sm" data-add-act style="margin-top:10px">＋ Ajouter une activité</button></div><div class="modal-foot"><button type="button" class="btn btn-light" data-close-act>Annuler</button><button class="btn btn-primary">Enregistrer</button></div></form></div></div>`;
 const close=()=>r.innerHTML='';r.querySelectorAll('[data-close-act]').forEach(b=>b.onclick=close);r.querySelector('[data-add-act]').onclick=()=>r.querySelector('#activity-program-rows').insertAdjacentHTML('beforeend',row({date:r.querySelector('[name=eventStartDate]').value||e.date||'',pax:e.guestTarget||0,place:e.place||''}));r.addEventListener('click',ev=>{const b=ev.target.closest('[data-del-act]');if(b)b.closest('[data-act-row]')?.remove()});r.querySelector('#activity-program-form').onsubmit=ev=>{ev.preventDefault();const f=ev.currentTarget,startDate=f.elements.eventStartDate.value,endDate=f.elements.eventEndDate.value||startDate,activities=[...f.querySelectorAll('[data-act-row]')].map(tr=>{const g=n=>tr.querySelector(`[data-f="${n}"]`)?.value||'';return{id:U(),name:g('name'),date:g('date'),start:g('start'),end:g('end'),pax:Number(g('pax'))||0,place:g('place'),accompanist:g('accompanist')}}).filter(a=>a.name||a.date||a.start||a.end||a.pax);mutate(x=>{x.eventStartDate=startDate;x.eventEndDate=endDate;x.activitiesDetailed=activities});close();inject();};
}
function programSummary(e){const p=program(e);return `<div><strong>${D(p.startDate)} → ${D(p.endDate)}</strong></div><div class="row-sub">${p.activities.length} activité(s) détaillée(s) · horaires et pax individualisés</div>`}
function injectCard(){const e=EV();if(!e)return;const grid=document.querySelector('.doc-grid');if(!grid||grid.querySelector('[data-activity-program-card]'))return;const c=document.createElement('article');c.className='doc-card';c.dataset.activityProgramCard='1';c.innerHTML=`<h3>Dates & programme activités</h3><p>Dates de début/fin de l’événement + date, horaires et pax pour chaque activité.</p>${programSummary(e)}<button class="btn btn-primary btn-sm" type="button" data-open-activity-program style="margin-top:10px">🗓️ Modifier le programme</button>`;c.querySelector('button').onclick=openProgram;grid.prepend(c)}
function injectQuoteEndDate(){const f=document.querySelector('#proform');if(!f||f.querySelector('[data-event-end-date]'))return;const title=f.closest('.modal')?.querySelector('.modal-head h3')?.textContent||'';if(!/devis ultra détaillé/i.test(title))return;const start=f.elements.eventDate;if(!start)return;const e=EV();const fld=start.closest('.field');if(fld){const lab=fld.querySelector('label');if(lab)lab.textContent='Date de début de l’événement';const d=document.createElement('div');d.className='field';d.dataset.eventEndDate='1';d.innerHTML=`<label>Date de fin de l’événement</label><input class="input" type="date" value="${E(e?.eventEndDate||e?.date||start.value||'')}">`;fld.insertAdjacentElement('afterend',d);d.querySelector('input').addEventListener('change',ev=>mutate(x=>{x.eventStartDate=start.value||x.date||'';x.eventEndDate=ev.target.value||start.value||x.date||''}))}
 const sec=[...f.querySelectorAll('.field.full h3')].find(h=>/Prestations détaillées/i.test(h.textContent));if(sec&&!f.querySelector('[data-program-note]')){const n=document.createElement('div');n.className='field full';n.dataset.programNote='1';n.innerHTML=`<div class="card-flat"><strong>Programme des activités</strong><div class="row-sub">Les horaires et le nombre de pax de chaque activité sont repris automatiquement dans le PDF depuis « Documents → Dates & programme activités ».</div></div>`;sec.closest('.field.full').insertAdjacentElement('beforebegin',n)}}
function injectWizard(){const d=document.querySelector('#w_date');if(!d||document.querySelector('#w_end_date'))return;const field=d.closest('.field');if(!field)return;const lab=field.querySelector('label');if(lab)lab.textContent='Date de début';const wrap=document.createElement('div');wrap.className='field';wrap.innerHTML=`<label>Date de fin</label><input id="w_end_date" class="input" type="date" value="${E(sessionStorage.getItem('jlg-event-end-draft')||d.value||'')}">`;field.insertAdjacentElement('afterend',wrap);wrap.querySelector('input').addEventListener('input',ev=>sessionStorage.setItem('jlg-event-end-draft',ev.target.value));d.addEventListener('input',()=>{const x=wrap.querySelector('input');if(!x.value){x.value=d.value;sessionStorage.setItem('jlg-event-end-draft',d.value)}})}
function captureWizard(){document.addEventListener('click',ev=>{if(!ev.target.closest('[data-wiz-create]'))return;const d=document.querySelector('#w_date')?.value||'',end=document.querySelector('#w_end_date')?.value||d;sessionStorage.setItem('jlg-event-range-pending',JSON.stringify({start:d,end}))},true)}
function applyPending(){const raw=sessionStorage.getItem('jlg-event-range-pending');if(!raw||!eventId())return;try{const p=JSON.parse(raw);mutate(e=>{e.eventStartDate=p.start||e.date||'';e.eventEndDate=p.end||p.start||e.date||''});sessionStorage.removeItem('jlg-event-range-pending');sessionStorage.removeItem('jlg-event-end-draft')}catch{}}
function enrichPrint(){const e=EV(),r=document.querySelector('#print-root');if(!e||!r||!r.innerHTML||r.querySelector('[data-activity-print]'))return;const p=program(e),box=document.createElement('div');box.dataset.activityPrint='1';box.className='print-section';box.innerHTML=`<h2>Cadre de l’événement & programme</h2><table class="print-table"><tr><th style="width:32%">Début de l’événement</th><td>${D(p.startDate)}</td></tr><tr><th>Fin de l’événement</th><td>${D(p.endDate)}</td></tr></table><h3 style="margin-top:14px">Activités</h3><table class="print-table"><thead><tr><th>Activité</th><th>Date</th><th>Horaires</th><th>Pax</th><th>Lieu</th><th>Accompagnant</th></tr></thead><tbody>${p.activities.map(a=>`<tr><td>${E(a.name||'—')}</td><td>${D(a.date)}</td><td>${E(a.start||'—')}–${E(a.end||'—')}</td><td>${Number(a.pax)||0}</td><td>${E(a.place||'—')}</td><td>${E(a.accompanist||'—')}</td></tr>`).join('')}</tbody></table>`;const title=r.querySelector('.print-title');if(title)title.insertAdjacentElement('afterend',box);else r.prepend(box)}
function inject(){applyPending();injectWizard();injectCard();injectQuoteEndDate();enrichPrint()}
let t;const schedule=()=>{clearTimeout(t);t=setTimeout(inject,30)};
window.addEventListener('DOMContentLoaded',()=>{captureWizard();inject();new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true})});window.addEventListener('hashchange',()=>setTimeout(inject,30));
})();