(() => {
'use strict';

const APP_KEY = 'jlg-event-builder-v2';
const APP_VERSION = 2;
const TYPE_LABEL = {mariage:'Mariage',anniversaire:'Anniversaire',seminaire:'Séminaire',association:'Association',autre:'Autre'};
const TYPE_ICON = {mariage:'💍',anniversaire:'🎂',seminaire:'💼',association:'🤝',autre:'✨'};
const STATUS_LABEL = {todo:'À faire',doing:'En cours',done:'Terminé'};
const PRIORITY_LABEL = {low:'Basse',normal:'Normale',high:'Haute'};
const PROVIDER_STATUS = {contact:'À contacter',quote:'Devis demandé',option:'Option',confirmed:'Confirmé',cancelled:'Annulé'};
const GUEST_STATUS = {confirmed:'Confirmé',pending:'En attente',declined:'Absent'};
const BUDGET_STATUS = {planned:'Prévu',quote:'Devis',confirmed:'Confirmé',paid:'Payé'};
const el = (sel, root=document) => root.querySelector(sel);
const els = (sel, root=document) => [...root.querySelectorAll(sel)];
const escapeHtml = (s='') => String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid = (p='id') => `${p}_${Math.random().toString(36).slice(2,9)}${Date.now().toString(36).slice(-5)}`;
const isoToday = () => new Date().toISOString().slice(0,10);
const clamp = (n,a,b)=>Math.max(a,Math.min(b,n));
const euro = n => new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(n)||0);
const dateFr = s => !s ? '—' : new Date(s+'T12:00:00').toLocaleDateString('fr-FR',{day:'2-digit',month:'long',year:'numeric'});
const dateShort = s => !s ? '—' : new Date(s+'T12:00:00').toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit',year:'2-digit'});
const daysDiff = s => { if(!s) return 0; const a=new Date(isoToday()+'T12:00:00'), b=new Date(s+'T12:00:00'); return Math.round((b-a)/86400000); };
const addDays = (s,d)=>{const x=new Date((s||isoToday())+'T12:00:00');x.setDate(x.getDate()+d);return x.toISOString().slice(0,10)};
const addMinutes = (hhmm,m)=>{const [h,mi]=(hhmm||'09:00').split(':').map(Number);let t=(h*60+mi+m)%1440;if(t<0)t+=1440;return `${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`};
const byDate = (a,b)=>(a.due||a.date||'9999').localeCompare(b.due||b.date||'9999');

function toast(msg){const t=el('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('show'),2200)}
function download(name,content,type='application/json'){const blob=new Blob([content],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},600)}
function confirmAction(msg){return window.confirm(msg)}

function templateRetro(type,date){
 const m={
 mariage:[
 ['Réserver le lieu de réception','Visite, option, contrat et acompte.',-270,'Organisateur','high'],['Choisir et réserver le traiteur','Comparer les offres, dégustation et contrat.',-240,'Organisateur','high'],['Réserver photographe / vidéaste','Vérifier portfolio, horaires et livrables.',-210,'Couple','normal'],['Réserver DJ / musiciens','Ambiance, matériel, contraintes horaires.',-180,'Couple','normal'],['Envoyer les faire-part','Inclure date limite de réponse.',-120,'Couple','high'],['Valider décoration et fleuriste','Fleurs, couleurs, centres de table, cérémonie.',-90,'Organisateur','normal'],['Finaliser tenues et retouches','Derniers essayages et accessoires.',-60,'Couple','normal'],['Valider le menu définitif','Adultes, enfants et régimes spéciaux.',-45,'Traiteur','high'],['Relancer les invités','Obtenir les dernières confirmations.',-30,'Organisateur','high'],['Construire le plan de table','Répartition des invités et contraintes.',-21,'Organisateur','high'],['Confirmer tous les prestataires','Horaires, accès, contacts jour J.',-10,'Organisateur','high'],['Finaliser le conducteur','Synchroniser équipe et prestataires.',-5,'Organisateur','high'],['Briefing final','Responsables, téléphones, plan B météo.',-2,'Organisateur','high'],['Installation et tests','Salle, décoration, son, lumière, signalétique.',-1,'Équipe','high']],
 anniversaire:[
 ['Définir format et liste d’invités','Ambiance, thème, nombre de participants.',-75,'Organisateur','high'],['Réserver le lieu','Capacité, horaires et règles du site.',-60,'Organisateur','high'],['Choisir repas / buffet','Traiteur, boissons, gâteau et allergies.',-45,'Organisateur','high'],['Envoyer les invitations','RSVP et informations pratiques.',-35,'Organisateur','normal'],['Réserver animation / musique','DJ, jeux ou animation enfants.',-30,'Organisateur','normal'],['Commander décoration','Thème, ballons, photobooth, signalétique.',-21,'Équipe','normal'],['Confirmer les présences','Comptage final pour restauration.',-10,'Organisateur','high'],['Commander le gâteau','Taille, parfum, bougies, livraison.',-7,'Organisateur','normal'],['Derniers achats','Boissons, glace, accessoires et consommables.',-2,'Équipe','normal'],['Installer la salle','Mobilier, décoration, son et buffet.',-1,'Équipe','high']],
 seminaire:[
 ['Définir objectifs et format','Plénière, ateliers, durée, participants.',-120,'Direction','high'],['Demander les devis','Salles, hébergement, restauration, technique.',-100,'Organisateur','high'],['Réserver les salles','Configurations et capacités validées.',-90,'Réception','high'],['Bloquer l’hébergement','Chambres, tarifs et conditions.',-75,'Réception','high'],['Valider la restauration','Pauses, déjeuner, dîner et régimes.',-60,'Restauration','high'],['Réserver l’audiovisuel','Écran, micros, régie, visioconférence.',-45,'Technique','high'],['Collecter les participants','Coordonnées, chambre, atelier, régimes.',-30,'Organisateur','high'],['Préparer badges et supports','Badges, pochettes, programme, signalétique.',-14,'Organisateur','normal'],['Préparer les émargements','Par session ou groupe.',-10,'Organisateur','normal'],['Valider le fléchage','Accueil, salles, restaurant, chambres.',-7,'Maintenance','normal'],['Transmettre la rooming list','Derniers changements à la réception.',-5,'Réception','high'],['Tester toute la technique','Son, image, wifi, visioconférence.',-1,'Technique','high']],
 association:[
 ['Valider le projet en bureau','Objectifs, budget, date, responsabilités.',-90,'Bureau','high'],['Réserver le lieu','Convention, assurance et état des lieux.',-75,'Organisateur','high'],['Faire les démarches administratives','Autorisations, buvette, SACEM, sécurité.',-60,'Bureau','high'],['Rechercher partenaires / sponsors','Dossier, relances et contreparties.',-55,'Bureau','normal'],['Lancer la communication','Affiches, réseaux sociaux, presse locale.',-40,'Communication','normal'],['Construire le planning bénévoles','Créneaux, postes et responsables.',-25,'Organisateur','high'],['Commander boissons / restauration','Stocks, caisse, hygiène et stockage.',-15,'Bénévoles','normal'],['Valider matériel et logistique','Tables, barrières, sono, éclairage.',-10,'Bénévoles','normal'],['Briefing bénévoles','Consignes, sécurité, contacts.',-2,'Organisateur','high'],['Installer le site','Montage, signalétique, sécurité.',-1,'Bénévoles','high']],
 autre:[
 ['Cadrer l’événement','Objectif, public, format et budget.',-90,'Organisateur','high'],['Réserver le lieu','Contrat, capacité et contraintes.',-70,'Organisateur','high'],['Sélectionner les prestataires','Comparer et valider les devis.',-50,'Organisateur','high'],['Lancer communication / invitations','Diffusion et suivi des réponses.',-35,'Communication','normal'],['Valider logistique et matériel','Mobilier, technique et signalétique.',-15,'Équipe','normal'],['Confirmer les participants','Comptage final et besoins particuliers.',-7,'Organisateur','high'],['Installation et tests','Montage et validation avant ouverture.',-1,'Équipe','high']]
 };
 return m[type].map(([title,desc,days,owner,priority])=>({id:uid('rt'),title,desc,due:addDays(date,days),owner,status:'todo',priority,notes:''}));
}
function templateBudget(type,total,date){
 const map={
 mariage:[['Location','Lieu',.20],['Restauration','Traiteur',.30],['Boissons','Vins, champagne et softs',.08],['Décoration','Fleurs et décoration',.07],['Photo / Vidéo','Photographe / vidéaste',.09],['DJ / Musique','DJ, son et lumière',.07],['Hébergement','Chambres',.05],['Papeterie','Faire-part et impressions',.03],['Transport','Navettes',.03],['Cadeaux','Cadeaux invités',.03],['Divers','Marge imprévus',.05]],
 anniversaire:[['Location','Salle',.20],['Restauration','Buffet / repas',.33],['Boissons','Boissons',.14],['Décoration','Thème et décoration',.09],['Animation','Animation / photobooth',.09],['Musique','DJ / sono',.07],['Invitations','Invitations',.02],['Divers','Marge imprévus',.06]],
 seminaire:[['Location','Salles',.18],['Restauration','Pauses et repas',.26],['Hébergement','Chambres',.24],['Technique','Audiovisuel',.10],['Animation','Intervenants / team building',.09],['Transport','Navettes',.05],['Communication','Badges et supports',.03],['Divers','Marge imprévus',.05]],
 association:[['Location','Lieu et matériel',.18],['Restauration','Restauration',.24],['Boissons','Buvette',.12],['Animation','Animations',.14],['Technique','Sono / éclairage',.09],['Sécurité','Sécurité / assurance',.07],['Communication','Affiches / impression',.08],['Divers','Marge imprévus',.08]],
 autre:[['Location','Lieu',.25],['Restauration','Restauration',.25],['Technique','Technique / matériel',.15],['Animation','Animation',.10],['Communication','Communication',.10],['Transport','Transport',.05],['Divers','Marge imprévus',.10]]};
 return map[type].map(([category,label,share])=>({id:uid('bud'),category,label,planned:Math.round(total*share/10)*10,quote:0,committed:0,paid:0,provider:'',due:addDays(date,-15),status:'planned'}));
}
function templateChecklist(type,date){
 const common={
 mariage:[['Avant événement','Confirmer l’arrivée de chaque prestataire'],['Avant événement','Imprimer plan de table et conducteur'],['Accueil','Préparer accueil, vestiaire et parking'],['Salle','Dresser les tables'],['Salle','Vérifier table d’honneur'],['Décoration','Installer fleurs et décoration'],['Restauration','Valider couverts et régimes spéciaux'],['Boissons','Mettre boissons en température'],['Technique','Tester sono, micros et lumière'],['Hébergement','Vérifier les chambres liées à l’événement'],['Sécurité','Vérifier issues et extincteurs'],['Nettoyage','Prévoir remise en état'],['Clôture','Restituer matériel et objets trouvés']],
 anniversaire:[['Avant événement','Confirmer les participants'],['Avant événement','Préparer playlist / animation'],['Accueil','Préparer accueil et vestiaire'],['Salle','Disposer tables et chaises'],['Décoration','Installer décoration / photobooth'],['Restauration','Vérifier buffet et gâteau'],['Boissons','Préparer glace et boissons'],['Technique','Tester enceintes et micro'],['Sécurité','Vérifier accès et sorties'],['Nettoyage','Prévoir sacs et consommables'],['Clôture','Récupérer décoration et matériel']],
 seminaire:[['Avant événement','Valider le programme final'],['Avant événement','Imprimer badges et émargements'],['Accueil','Installer table d’accueil'],['Accueil','Mettre en place le café 30 min avant'],['Salle','Configurer la plénière'],['Salle','Équiper les ateliers'],['Technique','Tester vidéoprojecteur, son et micros'],['Technique','Afficher les accès wifi'],['Restauration','Synchroniser les pauses au programme'],['Hébergement','Valider la rooming list'],['Signalétique','Poser le fléchage'],['Sécurité','Prévoir consignes d’évacuation'],['Nettoyage','Prévoir remise en état intersessions'],['Clôture','Récupérer matériel et lancer facturation']],
 association:[['Avant événement','Vérifier autorisations et assurance'],['Avant événement','Afficher le planning bénévoles'],['Accueil','Préparer caisse et monnaie'],['Salle','Installer tables, bancs et barrières'],['Restauration','Approvisionner la buvette'],['Restauration','Contrôler règles d’hygiène'],['Technique','Sécuriser branchements et sono'],['Signalétique','Afficher fléchage et tarifs'],['Sécurité','Trousse de secours et extincteurs'],['Nettoyage','Prévoir tri et poubelles'],['Clôture','Comptage caisse et état des lieux']],
 autre:[['Avant événement','Valider le déroulé'],['Accueil','Préparer l’accueil'],['Salle','Valider configuration'],['Restauration','Confirmer restauration'],['Technique','Tester le matériel'],['Sécurité','Vérifier les consignes'],['Nettoyage','Prévoir remise en état'],['Clôture','Bilan et restitution']]
 };
 return common[type].map(([category,title])=>({id:uid('chk'),category,title,done:false,owner:'',due:addDays(date,-1),priority:'normal',comment:''}));
}
function templateRun(type,start){
 const m={
 mariage:[[-180,60,'Arrivée des prestataires','Accès livraison','Organisateur'],[-120,90,'Installation salle et décoration','Salle','Équipe'],[-30,30,'Tests son, lumière et vérification finale','Salle','Technique'],[0,45,'Accueil des invités','Accueil / extérieur','Réception'],[45,45,'Cérémonie','Espace cérémonie','Organisateur'],[90,60,'Photos et cocktail','Parc / terrasse','Photographe'],[150,30,'Entrée en salle et placement','Salle','Organisateur'],[180,120,'Repas','Salle','Restauration'],[300,30,'Discours et animations','Salle','Organisateur'],[330,30,'Ouverture du bal','Piste','DJ'],[360,30,'Dessert / pièce montée','Salle','Restauration'],[390,150,'Soirée dansante','Piste','DJ'],[540,60,'Fin et rangement','Salle','Équipe']],
 anniversaire:[[-120,60,'Installation salle et décoration','Salle','Équipe'],[-30,30,'Mise en place buffet et boissons','Buffet','Restauration'],[0,45,'Accueil des invités','Entrée','Organisateur'],[45,30,'Toast / discours','Salle','Organisateur'],[75,90,'Buffet / repas','Salle','Restauration'],[165,30,'Gâteau et bougies','Salle','Organisateur'],[195,180,'Musique et animations','Piste','DJ'],[390,60,'Fin et rangement','Salle','Équipe']],
 seminaire:[[-120,90,'Montage salles et technique','Plénière','Technique'],[-30,30,'Accueil café et badges','Hall','Réception'],[0,30,'Accueil et émargement','Hall','Organisateur'],[30,90,'Plénière d’ouverture','Plénière','Direction'],[120,20,'Pause café','Hall','Restauration'],[140,90,'Ateliers en sous-groupes','Ateliers','Organisateur'],[230,90,'Déjeuner','Restaurant','Restauration'],[320,90,'Reprise des travaux','Plénière','Direction'],[410,20,'Pause','Hall','Restauration'],[430,60,'Synthèse et conclusions','Plénière','Direction'],[490,60,'Cocktail de clôture','Lounge','Restauration'],[550,60,'Démontage et remise en état','Plénière','Technique']],
 association:[[-180,120,'Montage stands et signalétique','Site','Bénévoles'],[-60,60,'Mise en place buvette et caisse','Buvette','Bénévoles'],[-15,15,'Briefing bénévoles','Site','Organisateur'],[0,30,'Ouverture au public','Entrée','Bénévoles'],[30,120,'Animations / activités','Site','Organisateur'],[150,90,'Restauration','Buvette','Bénévoles'],[240,120,'Animations de l’après-midi','Site','Organisateur'],[360,30,'Discours et remerciements','Scène','Bureau'],[390,60,'Fermeture au public','Entrée','Bénévoles'],[450,90,'Démontage, nettoyage, caisse','Site','Bénévoles']],
 autre:[[-120,90,'Installation','Lieu','Équipe'],[-30,30,'Vérifications finales','Lieu','Organisateur'],[0,30,'Accueil','Entrée','Réception'],[30,120,'Déroulé principal','Lieu','Organisateur'],[150,30,'Pause','Lieu','Restauration'],[180,120,'Suite du programme','Lieu','Organisateur'],[300,60,'Clôture','Lieu','Organisateur'],[360,60,'Rangement','Lieu','Équipe']]
 };
 return m[type].map(([off,dur,action,place,owner])=>({id:uid('run'),start:addMinutes(start,off),end:addMinutes(start,off+dur),action,place,owner,people:'',needs:'',notes:'',status:'todo'}));
}
function templateTeam(type){
 const m={mariage:[['Organisateur','Organisateur'],['Maître d’hôtel','Restauration'],['Responsable salle','Salle'],['Régisseur','Technique']],anniversaire:[['Organisateur','Organisateur'],['Responsable buffet','Restauration'],['Responsable animation','Animation']],seminaire:[['Organisateur','Organisateur'],['Réception','Réception'],['Régisseur AV','Technique'],['Responsable restauration','Restauration'],['Direction','Direction']],association:[['Organisateur','Organisateur'],['Responsable buvette','Bénévole'],['Responsable sécurité','Sécurité'],['Responsable communication','Communication']],autre:[['Organisateur','Organisateur'],['Responsable logistique','Logistique']]};
 return m[type].map(([name,role])=>({id:uid('mem'),name,role,phone:'',email:''}));
}
function templateProviders(type){
 const m={mariage:['Traiteur','Photographe','DJ','Fleuriste','Décoration','Location matériel'],anniversaire:['Traiteur','DJ','Décoration','Animation'],seminaire:['Traiteur','Technique','Imprimeur','Transport'],association:['Sécurité','Location matériel','Animation','Imprimeur'],autre:['Traiteur','Technique']};
 return m[type].map(category=>({id:uid('pro'),name:'',category,contact:'',phone:'',email:'',site:'',amount:0,deposit:0,due:'',status:'contact',notes:''}));
}
function templatePlan(type,guests){
 const out=[]; const add=(kind,name,seats,x,y,w,h)=>out.push({id:uid('pl'),kind,name,seats,x,y,w,h});
 if(type==='seminaire'){
   add('stage','Scène / Estrade',0,35,4,30,9); add('video','Vidéoprojecteur',0,72,5,13,7); add('welcome','Accueil / Émargement',0,4,84,20,9); add('buffet','Pause café',0,72,84,24,9);
   const n=Math.max(2,Math.ceil(guests/8)); for(let i=0;i<Math.min(n,12);i++)add('rect',`Table ${i+1}`,8,8+(i%4)*23,23+Math.floor(i/4)*19,17,10);
 } else {
   add('honour','Table d’honneur',8,34,5,32,10); add('dance','Piste de danse',0,38,44,24,18); add('bar','Bar',0,3,47,14,9); add('buffet','Buffet',0,83,47,14,9); add('welcome','Accueil',0,3,87,18,8);
   const n=Math.max(2,Math.ceil(Math.max(guests-8,0)/10)); for(let i=0;i<Math.min(n,14);i++)add('round',`Table ${i+1}`,10,6+(i%4)*24,22+Math.floor(i/4)*22,15,15);
 }
 return out;
}
function optionsFor(type){return {mariage:['Repas assis','Buffet','Cocktail','Cérémonie','Hébergement','Scène / animation','Audiovisuel','Navettes','Accès PMR','Enfants','Brunch lendemain'],anniversaire:['Repas assis','Buffet','Cocktail','Animation','Audiovisuel','Enfants','Accès PMR','Photobooth','Gâteau','Navettes'],seminaire:['Plénière','Ateliers','Repas assis','Buffet','Pauses café','Hébergement','Audiovisuel','Navettes','Accès PMR','Team building','Cocktail','Visioconférence'],association:['Buvette','Repas assis','Buffet','Scène / animation','Audiovisuel','Enfants','Accès PMR','Bénévoles','Billetterie','Sécurité'],autre:['Repas assis','Buffet','Cocktail','Hébergement','Audiovisuel','Scène / animation','Navettes','Accès PMR','Enfants']}[type]}

let state = loadState();
function loadState(){try{const raw=localStorage.getItem(APP_KEY);if(!raw)return{version:APP_VERSION,events:[]};const x=JSON.parse(raw);return x&&Array.isArray(x.events)?x:{version:APP_VERSION,events:[]}}catch{return{version:APP_VERSION,events:[]}}}
function saveState(){localStorage.setItem(APP_KEY,JSON.stringify(state))}
function setState(mutator){mutator(state);saveState();render()}
function getEvent(id){return state.events.find(e=>e.id===id)}
function createEvent(input){
 const e={id:uid('ev'),createdAt:new Date().toISOString(),type:input.type,name:input.name,date:input.date,start:input.start,end:input.end,place:input.place,setting:input.setting,guestTarget:Number(input.guestTarget)||0,budgetTotal:Number(input.budgetTotal)||0,contactName:input.contactName||'',contactPhone:input.contactPhone||'',contactEmail:input.contactEmail||'',notes:input.notes||'',options:input.options||[],retro:templateRetro(input.type,input.date),budget:templateBudget(input.type,Number(input.budgetTotal)||0,input.date),plan:templatePlan(input.type,Number(input.guestTarget)||0),guests:[],checklist:templateChecklist(input.type,input.date),team:templateTeam(input.type),tasks:[],providers:templateProviders(input.type),run:templateRun(input.type,input.start)};
 state.events.unshift(e);saveState();return e;
}
function eventProgress(e){const all=[...e.retro.map(x=>x.status==='done'),...e.checklist.map(x=>x.done),...e.tasks.map(x=>x.status==='done')];return all.length?Math.round(all.filter(Boolean).length/all.length*100):0}
function budgetTotals(e){const planned=e.budget.reduce((s,x)=>s+Number(x.planned||0),0), committed=e.budget.reduce((s,x)=>s+Number(x.committed||0),0), paid=e.budget.reduce((s,x)=>s+Number(x.paid||0),0);return{planned,committed,paid,remainingToPay:committed-paid,remainingBudget:e.budgetTotal-committed}}
function guestTotals(e){return{total:e.guests.length,confirmed:e.guests.filter(g=>g.status==='confirmed').length,pending:e.guests.filter(g=>g.status==='pending').length,declined:e.guests.filter(g=>g.status==='declined').length,special:e.guests.filter(g=>g.diet).length,lodged:e.guests.filter(g=>g.lodging).length,placed:e.guests.filter(g=>g.tableId).length}}
function nextDeadline(e){const arr=[...e.retro.filter(x=>x.status!=='done').map(x=>({date:x.due,label:x.title})),...e.checklist.filter(x=>!x.done).map(x=>({date:x.due,label:x.title})),...e.tasks.filter(x=>x.status!=='done').map(x=>({date:x.due,label:x.title}))].filter(x=>x.date).sort((a,b)=>a.date.localeCompare(b.date));return arr[0]||null}

function route(){
 const h=(location.hash||'#/').replace(/^#/,'');
 const p=h.split('/').filter(Boolean);
 if(p[0]==='new') return {name:'new',step:Number(new URLSearchParams(location.search).get('step')||1)};
 if(p[0]==='event'&&p[1]) return {name:'event',id:p[1],module:p[2]||'overview'};
 if(p[0]==='settings') return {name:'settings'};
 return {name:'dashboard'};
}
function navTo(hash){location.hash=hash}
function topbar(title){return `<div class="topbar"><div class="topbar-inner"><a class="brand" href="#/"><div class="brand-mark">JLG</div><div class="brand-text"><strong>Event Builder</strong><small>JLG Creative</small></div></a><div class="top-actions"><button class="btn btn-light btn-sm desktop-only" data-nav="#/settings">⚙ Sauvegardes</button><button class="btn btn-gold btn-sm" data-nav="#/new">＋ <span class="label">Nouvel événement</span></button></div></div></div>`}
function bottomNav(active='home',eventId=''){const eventLink=eventId?`#/event/${eventId}/overview`:'#/';return `<nav class="bottom-nav no-print"><button class="${active==='home'?'active':''}" data-nav="#/"><span>⌂</span>Accueil</button><button class="${active==='event'?'active':''}" data-nav="${eventLink}"><span>◫</span>Événement</button><button class="${active==='new'?'active':''}" data-nav="#/new"><span>＋</span>Nouveau</button><button class="${active==='settings'?'active':''}" data-nav="#/settings"><span>⚙</span>Sauvegardes</button></nav>`}
function appShell(content,active='home',eventId=''){return `<div class="app-shell">${topbar()}${content}${bottomNav(active,eventId)}<div id="print-root" class="print-sheet"></div></div>`}
function sectionTitle(title,sub='',action=''){return `<div class="section-title"><div><h2>${escapeHtml(title)}</h2>${sub?`<p>${escapeHtml(sub)}</p>`:''}</div>${action}</div>`}
function badge(text,kind=''){return `<span class="badge ${kind}">${escapeHtml(text)}</span>`}
function stat(label,value,sub=''){return `<div class="card stat-card"><div class="stat-label">${escapeHtml(label)}</div><div class="stat-value">${value}</div>${sub?`<div class="stat-sub">${sub}</div>`:''}</div>`}
function progressBar(v){return `<div class="progress"><span style="width:${clamp(v,0,100)}%"></span></div>`}
function emptyState(icon,title,text,action=''){return `<div class="empty"><div class="big">${icon}</div><h3>${escapeHtml(title)}</h3><p>${escapeHtml(text)}</p>${action}</div>`}
function inputField(name,label,value='',type='text',extra=''){return `<div class="field"><label for="${name}">${escapeHtml(label)}</label><input class="input" id="${name}" name="${name}" type="${type}" value="${escapeHtml(value)}" ${extra}></div>`}
function selectField(name,label,options,value='',extra=''){return `<div class="field"><label for="${name}">${escapeHtml(label)}</label><select class="select" id="${name}" name="${name}" ${extra}>${options.map(o=>`<option value="${escapeHtml(o.value??o)}" ${(o.value??o)===value?'selected':''}>${escapeHtml(o.label??o)}</option>`).join('')}</select></div>`}
function textareaField(name,label,value='',extra=''){return `<div class="field full"><label for="${name}">${escapeHtml(label)}</label><textarea class="textarea" id="${name}" name="${name}" ${extra}>${escapeHtml(value)}</textarea></div>`}
function serializeForm(form){return Object.fromEntries(new FormData(form).entries())}
function openModal(title,body,onSubmit,{submitLabel='Enregistrer',danger=false,width='760px'}={}){
 const root=el('#modal-root');root.innerHTML=`<div class="modal-backdrop"><div class="modal" style="max-width:${width}"><div class="modal-head"><h3>${escapeHtml(title)}</h3><button class="btn btn-ghost btn-sm" data-modal-close>✕</button></div><form id="modal-form"><div class="modal-body">${body}</div><div class="modal-foot"><button type="button" class="btn btn-light" data-modal-close>Annuler</button><button class="btn ${danger?'btn-danger':'btn-primary'}" type="submit">${escapeHtml(submitLabel)}</button></div></form></div></div>`;
 const close=()=>root.innerHTML='';els('[data-modal-close]',root).forEach(b=>b.addEventListener('click',close));el('.modal-backdrop',root).addEventListener('click',e=>{if(e.target===e.currentTarget)close()});el('#modal-form',root).addEventListener('submit',e=>{e.preventDefault();onSubmit(e.currentTarget,close)});
}
function priorityBadge(p){return p==='high'?badge('Haute','danger'):p==='low'?badge('Basse','muted'):badge('Normale','gold')}
function statusBadge(s){return s==='done'?badge('Terminé','ok'):s==='doing'?badge('En cours','warn'):badge('À faire','muted')}
function providerBadge(s){const k={contact:'muted',quote:'warn',option:'gold',confirmed:'ok',cancelled:'danger'}[s]||'';return badge(PROVIDER_STATUS[s]||s,k)}
function dateAlertClass(due,done=false){if(done||!due)return'';const d=daysDiff(due);if(d<0)return'row-overdue';if(d<=7)return'row-soon';return''}
function moduleTabs(e,current){const mods=[['overview','Vue d’ensemble'],['retro','Rétroplanning'],['budget','Budget'],['plan','Plan de salle'],['guests','Invités'],['checklist','Checklist'],['team','Équipe & tâches'],['providers','Prestataires'],['run','Conducteur'],['docs','Documents']];return `<div class="tabs-wrap"><div class="tabs">${mods.map(([k,l])=>`<button class="tab ${k===current?'active':''}" data-nav="#/event/${e.id}/${k}">${l}</button>`).join('')}</div></div>`}
function eventHeader(e,current){const d=daysDiff(e.date);return `<div class="event-head"><div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:6px">${badge(`${TYPE_ICON[e.type]} ${TYPE_LABEL[e.type]}`,'gold')}${d>=0?badge(`J-${d}`,'ok'):badge(`Terminé depuis ${Math.abs(d)} j`,'muted')}</div><h1>${escapeHtml(e.name)}</h1><div class="event-head-meta"><span>📅 ${dateFr(e.date)} · ${escapeHtml(e.start)}–${escapeHtml(e.end)}</span><span>📍 ${escapeHtml(e.place||'Lieu à préciser')}</span><span>👥 ${e.guestTarget} prévus</span><span>💶 ${euro(e.budgetTotal)}</span></div></div><div class="event-head-actions"><button class="btn btn-light btn-sm" data-action="edit-event" data-event="${e.id}">✎ Modifier</button><button class="btn btn-danger btn-sm" data-action="delete-event" data-event="${e.id}">Supprimer</button></div></div>${moduleTabs(e,current)}`}

function render(){
 const r=route();let html='';
 if(r.name==='dashboard')html=renderDashboard();
 else if(r.name==='new')html=renderNew();
 else if(r.name==='settings')html=renderSettings();
 else if(r.name==='event'){const e=getEvent(r.id);html=e?renderEvent(e,r.module):renderNotFound()}
 el('#app').innerHTML=html;
 bindGlobal();
 if(r.name==='event'){const e=getEvent(r.id);if(e)bindEventModule(e,r.module)}
 if(r.name==='new')bindNewWizard();
 if(r.name==='settings')bindSettings();
}
function renderNotFound(){return appShell(`<main class="page">${emptyState('🔎','Événement introuvable','Il a peut-être été supprimé.','<button class="btn btn-primary" data-nav="#/">Retour à l’accueil</button>')}</main>`)}

function renderDashboard(){
 const events=state.events;
 const active=events.filter(e=>daysDiff(e.date)>=0);
 const urgent=active.reduce((n,e)=>n+e.retro.filter(x=>x.status!=='done'&&daysDiff(x.due)<=7).length+e.checklist.filter(x=>!x.done&&daysDiff(x.due)<=7).length,0);
 const totalBudget=active.reduce((s,e)=>s+Math.max(0,budgetTotals(e).remainingBudget),0);
 const nexts=active.map(e=>({e,n:nextDeadline(e)})).filter(x=>x.n).sort((a,b)=>a.n.date.localeCompare(b.n.date));
 return appShell(`<main class="page">
 <section class="hero"><div class="gold">JLG Creative · Outil événementiel</div><h1>Construisez un événement sans perdre le fil.</h1><p>Budget, rétroplanning, invités, plan de salle, prestataires, équipe, conducteur de journée et documents : tout le dossier opérationnel au même endroit.</p><button class="btn btn-gold" data-nav="#/new">＋ Créer un événement</button></section>
 <div class="grid grid-4" style="margin-top:14px">${stat('Événements actifs',String(active.length),'À venir')}${stat('Tâches urgentes',String(urgent),'Échéance sous 7 jours')}${stat('Budget disponible',euro(totalBudget),'Sur les événements actifs')}${stat('Prochaine échéance',nexts[0]?dateShort(nexts[0].n.date):'—',nexts[0]?escapeHtml(nexts[0].n.label):'Aucune')}</div>
 ${sectionTitle('Mes événements','Créez un dossier, puis pilotez-le jusqu’au jour J.',events.length?`<div class="toolbar-group"><input id="event-search" class="input" style="width:190px" placeholder="Rechercher…"><select id="event-filter" class="select" style="width:130px"><option value="all">Tous</option><option value="upcoming">À venir</option><option value="past">Passés</option></select></div>`:'')}
 <div id="event-list">${renderEventList(events)}</div>
 </main>`,'home');
}
function renderEventList(events){
 if(!events.length)return emptyState('🗂️','Aucun événement pour l’instant','Créez votre premier mariage, anniversaire, séminaire ou événement associatif. Le dossier sera automatiquement prérempli avec des modèles adaptés.','<button class="btn btn-primary" data-nav="#/new">Créer mon premier événement</button>');
 return `<div class="event-list">${events.map(e=>{const p=eventProgress(e),b=budgetTotals(e),n=nextDeadline(e),d=daysDiff(e.date);return `<article class="event-card"><div class="event-main"><div style="display:flex;gap:7px;align-items:center;flex-wrap:wrap">${badge(`${TYPE_ICON[e.type]} ${TYPE_LABEL[e.type]}`,'gold')}${d>=0?badge(`J-${d}`,'ok'):badge('Passé','muted')}</div><div class="event-title">${escapeHtml(e.name)}</div><div class="event-meta"><span>📅 ${dateFr(e.date)}</span><span>📍 ${escapeHtml(e.place||'Lieu à préciser')}</span><span>👥 ${e.guestTarget} pers.</span><span>💶 ${euro(e.budgetTotal)}</span></div><div class="event-progress">${progressBar(p)}<span class="progress-label">${p}% prêt</span></div>${n?`<div class="row-sub" style="margin-top:8px">Prochain jalon : <strong>${escapeHtml(n.label)}</strong> · ${dateShort(n.date)}</div>`:''}${b.remainingBudget<0?`<div class="row-sub text-danger">Budget engagé dépassé de ${euro(Math.abs(b.remainingBudget))}</div>`:''}</div><div class="event-actions"><button class="btn btn-primary btn-sm" data-nav="#/event/${e.id}/overview">Ouvrir</button><button class="btn btn-light btn-sm" data-action="duplicate-event" data-event="${e.id}">Dupliquer</button></div></article>`}).join('')}</div>`;
}
let wizard = {step:1,type:'mariage',name:'',date:'',start:'15:00',end:'02:00',place:'',setting:'indoor',guestTarget:80,budgetTotal:12000,contactName:'',contactPhone:'',contactEmail:'',notes:'',options:[]};
function renderNew(){
 const s=wizard.step;
 let body='';
 if(s===1){body=`<div class="choice-grid">${Object.keys(TYPE_LABEL).map(k=>`<button class="choice ${wizard.type===k?'active':''}" data-wiz-type="${k}"><strong>${TYPE_ICON[k]} ${TYPE_LABEL[k]}</strong><small>${{mariage:'Réception, cérémonie, dîner et soirée',anniversaire:'Soirée, repas, animation et invités',seminaire:'Réunion, hébergement, ateliers et technique',association:'Bénévoles, buvette, sécurité et logistique',autre:'Un modèle souple à personnaliser'}[k]}</small></button>`).join('')}</div>`}
 if(s===2){body=`<div class="form-grid">${inputField('w_name','Nom de l’événement',wizard.name,'text','required')}${inputField('w_date','Date',wizard.date,'date','required')}${inputField('w_start','Heure de début',wizard.start,'time','required')}${inputField('w_end','Heure de fin',wizard.end,'time','required')}${inputField('w_place','Lieu',wizard.place,'text','placeholder="Nom du lieu, ville…"')}${selectField('w_setting','Configuration',[{value:'indoor',label:'Intérieur'},{value:'outdoor',label:'Extérieur'},{value:'mixed',label:'Intérieur + extérieur'}],wizard.setting)}${inputField('w_guests','Nombre d’invités / participants',wizard.guestTarget,'number','min="0"')}${inputField('w_budget','Budget global (€)',wizard.budgetTotal,'number','min="0" step="100"')}${inputField('w_contactName','Contact principal',wizard.contactName)}${inputField('w_contactPhone','Téléphone',wizard.contactPhone,'tel')}${inputField('w_contactEmail','E-mail',wizard.contactEmail,'email')}<div></div>${textareaField('w_notes','Notes initiales',wizard.notes,'placeholder="Contraintes, souhaits du client, informations utiles…"')}</div>`}
 if(s===3){body=`<div class="option-grid">${optionsFor(wizard.type).map(o=>`<label class="check-chip"><input type="checkbox" data-wiz-option value="${escapeHtml(o)}" ${wizard.options.includes(o)?'checked':''}><span>${escapeHtml(o)}</span></label>`).join('')}</div>`}
 if(s===4){body=`<div class="grid grid-2"><div class="card-flat"><div class="stat-label">Type</div><div class="event-title">${TYPE_ICON[wizard.type]} ${TYPE_LABEL[wizard.type]}</div><div class="row-sub">${escapeHtml(wizard.name||'Événement sans nom')}</div></div><div class="card-flat"><div class="stat-label">Date & lieu</div><div class="event-title">${dateFr(wizard.date)}</div><div class="row-sub">${escapeHtml(wizard.place||'Lieu à préciser')} · ${escapeHtml(wizard.start)}–${escapeHtml(wizard.end)}</div></div><div class="card-flat"><div class="stat-label">Invités</div><div class="event-title">${Number(wizard.guestTarget)||0}</div><div class="row-sub">Capacité à organiser</div></div><div class="card-flat"><div class="stat-label">Budget</div><div class="event-title">${euro(wizard.budgetTotal)}</div><div class="row-sub">Ventilation automatique à la création</div></div></div><div class="card" style="margin-top:12px"><h3 style="color:var(--navy)">Ce que JLG Event Builder va générer</h3><div class="option-grid">${['Rétroplanning adapté','Budget ventilé','Plan de salle initial','Checklist opérationnelle','Équipe de base','Prestataires types','Conducteur de journée'].map(x=>`<div class="check-chip">✓ ${x}</div>`).join('')}</div></div>`}
 return appShell(`<main class="page narrow"><div class="toolbar"><button class="btn btn-ghost" data-nav="#/">← Annuler</button><div class="badge gold">Création guidée · étape ${s}/4</div></div><div class="stepper">${[1,2,3,4].map(i=>`<span class="step ${i<s?'done':i===s?'active':''}"></span>`).join('')}</div><div class="card"><h1 style="font-family:Georgia,serif;color:var(--navy);margin-top:0">${['Quel type d’événement ?','Informations essentielles','Options & besoins','Vérification avant création'][s-1]}</h1><p class="text-muted">${['Le modèle choisi détermine les tâches, le budget et le conducteur générés.','Ces données servent de base à tous les modules.','Sélectionnez uniquement ce qui concerne cet événement.','Tout restera modifiable après création.'][s-1]}</p><div class="divider"></div>${body}<div class="toolbar" style="margin-bottom:0"><button class="btn btn-light" data-wiz-prev ${s===1?'disabled':''}>← Précédent</button>${s<4?`<button class="btn btn-primary" data-wiz-next>Continuer →</button>`:`<button class="btn btn-gold" data-wiz-create>Créer le dossier événement</button>`}</div></div></main>`,'new');
}
function bindNewWizard(){
 els('[data-wiz-type]').forEach(b=>b.onclick=()=>{wizard.type=b.dataset.wizType;wizard.options=[];render()});
 el('[data-wiz-prev]')?.addEventListener('click',()=>{wizard.step=Math.max(1,wizard.step-1);render()});
 el('[data-wiz-next]')?.addEventListener('click',()=>{if(wizard.step===2){const names=['w_name','w_date','w_start','w_end','w_place','w_setting','w_guests','w_budget','w_contactName','w_contactPhone','w_contactEmail','w_notes'];const vals={};for(const n of names){const x=el('#'+n);if(x)vals[n]=x.value}if(!vals.w_name||!vals.w_date){toast('Le nom et la date sont obligatoires.');return}Object.assign(wizard,{name:vals.w_name,date:vals.w_date,start:vals.w_start,end:vals.w_end,place:vals.w_place,setting:vals.w_setting,guestTarget:Number(vals.w_guests)||0,budgetTotal:Number(vals.w_budget)||0,contactName:vals.w_contactName,contactPhone:vals.w_contactPhone,contactEmail:vals.w_contactEmail,notes:vals.w_notes});}if(wizard.step===3)wizard.options=els('[data-wiz-option]:checked').map(x=>x.value);wizard.step=Math.min(4,wizard.step+1);render()});
 el('[data-wiz-create]')?.addEventListener('click',()=>{const e=createEvent(wizard);wizard={step:1,type:'mariage',name:'',date:'',start:'15:00',end:'02:00',place:'',setting:'indoor',guestTarget:80,budgetTotal:12000,contactName:'',contactPhone:'',contactEmail:'',notes:'',options:[]};toast('Événement créé.');navTo(`#/event/${e.id}/overview`)});
}

function renderSettings(){return appShell(`<main class="page narrow">${sectionTitle('Sauvegardes & données','Vos événements sont enregistrés dans ce navigateur, sur cet appareil.')}
 <div class="grid grid-2"><div class="card"><h3>Exporter une sauvegarde</h3><p class="text-muted">Télécharge un fichier JSON contenant tous les événements. À conserver avant un changement de téléphone ou pour transférer les données.</p><button class="btn btn-primary" data-action="export-all">⬇ Exporter toutes les données</button></div><div class="card"><h3>Importer une sauvegarde</h3><p class="text-muted">Importe un fichier précédemment exporté. Les événements portant le même identifiant sont remplacés par la version importée.</p><input id="import-file" type="file" accept="application/json,.json" class="input"><button class="btn btn-light" style="margin-top:10px" data-action="import-all">Importer</button></div></div>
 <div class="card" style="margin-top:14px"><h3>À propos de la sauvegarde locale</h3><p class="small-note">Cette version fonctionne sans serveur : aucune donnée n’est envoyée ailleurs. La contrepartie est que deux téléphones ne partagent pas automatiquement les mêmes données. Pour travailler à plusieurs, il faudra plus tard ajouter une synchronisation.</p><div class="divider"></div><div class="row"><div><div class="row-title">Événements enregistrés</div><div class="row-sub">${state.events.length} dossier(s) sur cet appareil</div></div><div class="row-actions"><button class="btn btn-danger btn-sm" data-action="clear-all">Effacer toutes les données</button></div></div></div>
 <div class="card" style="margin-top:14px"><h3>Installation sur téléphone</h3><p class="text-muted">Une fois l’application publiée sur une adresse HTTPS, ouvre-la dans Chrome puis utilise « Ajouter à l’écran d’accueil » / « Installer l’application ». L’icône JLG Events apparaîtra comme une application autonome.</p></div>
 </main>`,'settings');}
function bindSettings(){
 el('[data-action="export-all"]')?.addEventListener('click',()=>download(`jlg-event-builder-sauvegarde-${isoToday()}.json`,JSON.stringify(state,null,2)));
 el('[data-action="import-all"]')?.addEventListener('click',async()=>{const f=el('#import-file')?.files?.[0];if(!f){toast('Choisis un fichier JSON.');return}try{const x=JSON.parse(await f.text());if(!x||!Array.isArray(x.events))throw new Error();const map=new Map(state.events.map(e=>[e.id,e]));x.events.forEach(e=>map.set(e.id,e));state={version:APP_VERSION,events:[...map.values()]};saveState();toast('Sauvegarde importée.');render()}catch{toast('Fichier de sauvegarde invalide.')}});
 el('[data-action="clear-all"]')?.addEventListener('click',()=>{if(confirmAction('Supprimer définitivement tous les événements de cet appareil ?')){state={version:APP_VERSION,events:[]};saveState();toast('Données effacées.');render()}})
}

function renderEvent(e,module){let content='';
 if(module==='overview')content=renderOverview(e);
 else if(module==='retro')content=renderRetro(e);
 else if(module==='budget')content=renderBudget(e);
 else if(module==='plan')content=renderPlan(e);
 else if(module==='guests')content=renderGuests(e);
 else if(module==='checklist')content=renderChecklist(e);
 else if(module==='team')content=renderTeam(e);
 else if(module==='providers')content=renderProviders(e);
 else if(module==='run')content=renderRun(e);
 else if(module==='docs')content=renderDocs(e);
 else content=renderOverview(e);
 return appShell(`<main class="page">${eventHeader(e,module)}${content}</main>`,'event',e.id);
}
function renderOverview(e){const p=eventProgress(e),b=budgetTotals(e),g=guestTotals(e),confirmedProviders=e.providers.filter(x=>x.status==='confirmed').length,urgent=[...e.retro.filter(x=>x.status!=='done'&&daysDiff(x.due)<=7),...e.checklist.filter(x=>!x.done&&daysDiff(x.due)<=7)].slice(0,6);const n=nextDeadline(e);return `<div class="kpis"><div class="kpi"><small>Préparation</small><strong>${p}%</strong>${progressBar(p)}</div><div class="kpi"><small>Invités confirmés</small><strong>${g.confirmed}/${e.guestTarget}</strong></div><div class="kpi"><small>Budget engagé</small><strong>${euro(b.committed)}</strong></div><div class="kpi"><small>Budget restant</small><strong class="${b.remainingBudget<0?'text-danger':''}">${euro(b.remainingBudget)}</strong></div><div class="kpi"><small>Prestataires</small><strong>${confirmedProviders}/${e.providers.length}</strong></div><div class="kpi"><small>Prochaine échéance</small><strong>${n?dateShort(n.date):'—'}</strong></div></div>
 <div class="grid grid-2"> <div class="card">${sectionTitle('Priorités immédiates','Ce qui demande ton attention maintenant.')} ${urgent.length?`<div class="list">${urgent.map(x=>`<div class="row ${dateAlertClass(x.due,x.done||x.status==='done')}"><div><div class="row-title">${escapeHtml(x.title)}</div><div class="row-sub">${dateFr(x.due)} · ${escapeHtml(x.owner||'Sans responsable')}</div></div><div>${daysDiff(x.due)<0?badge('En retard','danger'):badge('À traiter','warn')}</div></div>`).join('')}</div>`:emptyState('✓','Aucune urgence','Les échéances à moins de 7 jours apparaîtront ici.')}</div>
 <div class="card">${sectionTitle('Dossier événement','Accès rapide aux modules.')}<div class="option-grid">${[['retro','🗓️ Rétroplanning',`${e.retro.filter(x=>x.status==='done').length}/${e.retro.length} terminées`],['budget','💶 Budget',`${euro(b.remainingBudget)} restant`],['plan','🪑 Plan de salle',`${e.plan.length} éléments`],['guests','👥 Invités',`${g.confirmed} confirmés`],['checklist','☑ Checklist',`${e.checklist.filter(x=>x.done).length}/${e.checklist.length} cochées`],['team','🧑‍🤝‍🧑 Équipe',`${e.tasks.length} tâches`],['providers','📞 Prestataires',`${confirmedProviders} confirmés`],['run','⏱ Conducteur',`${e.run.length} séquences`]].map(([m,l,s])=>`<button class="choice" data-nav="#/event/${e.id}/${m}"><strong>${l}</strong><small>${s}</small></button>`).join('')}</div></div></div>
 ${e.notes?`<div class="card" style="margin-top:14px"><h3>Notes générales</h3><p style="white-space:pre-wrap">${escapeHtml(e.notes)}</p></div>`:''}`}
function renderRetro(e){const sorted=[...e.retro].sort((a,b)=>a.due.localeCompare(b.due));const done=e.retro.filter(x=>x.status==='done').length;return `${sectionTitle('Rétroplanning',`${done}/${e.retro.length} étapes terminées. Les échéances sont générées selon le type d’événement.`,`<button class="btn btn-primary btn-sm" data-action="add-retro" data-event="${e.id}">＋ Ajouter une étape</button>`)}<div class="grid grid-3" style="margin-bottom:12px">${stat('Terminées',String(done))}${stat('En retard',String(e.retro.filter(x=>x.status!=='done'&&daysDiff(x.due)<0).length))}${stat('Cette semaine',String(e.retro.filter(x=>x.status!=='done'&&daysDiff(x.due)>=0&&daysDiff(x.due)<=7).length))}</div><div class="timeline">${sorted.map(x=>`<article class="timeline-item ${x.status==='done'?'row-done':''}"><div style="display:flex;justify-content:space-between;gap:10px;align-items:start"><div><div class="timeline-time">${dateFr(x.due)}</div><div class="timeline-main">${escapeHtml(x.title)}</div><div class="timeline-sub">${escapeHtml(x.desc||'')} · ${escapeHtml(x.owner||'Sans responsable')}</div><div style="margin-top:8px;display:flex;gap:6px;flex-wrap:wrap">${statusBadge(x.status)}${priorityBadge(x.priority)}${x.status!=='done'&&daysDiff(x.due)<0?badge(`${Math.abs(daysDiff(x.due))} j de retard`,'danger'):''}</div>${x.notes?`<div class="row-sub" style="margin-top:6px">${escapeHtml(x.notes)}</div>`:''}</div><div class="row-actions"><button class="btn btn-light btn-sm" data-action="toggle-retro" data-event="${e.id}" data-id="${x.id}">${x.status==='done'?'↶ Réouvrir':'✓ Terminer'}</button><button class="btn btn-ghost btn-sm" data-action="edit-retro" data-event="${e.id}" data-id="${x.id}">✎</button><button class="btn btn-ghost btn-sm text-danger" data-action="delete-retro" data-event="${e.id}" data-id="${x.id}">🗑</button></div></div></article>`).join('')}</div>`}

function renderBudget(e){const t=budgetTotals(e);const used=e.budgetTotal?Math.round(t.committed/e.budgetTotal*100):0;const providers=[{value:'',label:'—'},...e.providers.map(p=>({value:p.id,label:p.name||p.category}))];return `${sectionTitle('Budget',`Budget global : ${euro(e.budgetTotal)}. Les montants sont recalculés automatiquement.`,`<button class="btn btn-primary btn-sm" data-action="add-budget" data-event="${e.id}">＋ Ajouter une ligne</button>`)}<div class="grid grid-4" style="margin-bottom:12px">${stat('Prévu',euro(t.planned))}${stat('Engagé',euro(t.committed),`${used}% du budget`)}${stat('Payé',euro(t.paid))}${stat('Reste disponible',`<span class="${t.remainingBudget<0?'text-danger':''}">${euro(t.remainingBudget)}</span>`,t.remainingBudget<0?'Dépassement':'Après engagements')}</div><div class="card" style="margin-bottom:12px"><div style="display:flex;justify-content:space-between;gap:10px;font-size:12px;margin-bottom:7px"><strong>Consommation du budget</strong><span>${clamp(used,0,999)}%</span></div>${progressBar(clamp(used,0,100))}${t.remainingBudget<0?`<p class="small-note text-danger">Attention : les engagements dépassent le budget de ${euro(Math.abs(t.remainingBudget))}.</p>`:''}</div><div class="table-wrap"><table class="data-table"><thead><tr><th>Catégorie</th><th>Libellé</th><th>Prestataire</th><th>Prévu</th><th>Devis</th><th>Engagé</th><th>Payé</th><th>Reste à payer</th><th>Échéance</th><th>Statut</th><th></th></tr></thead><tbody>${e.budget.map(x=>`<tr><td><input data-budget-field="category" data-id="${x.id}" value="${escapeHtml(x.category)}"></td><td><input data-budget-field="label" data-id="${x.id}" value="${escapeHtml(x.label)}"></td><td><select data-budget-field="provider" data-id="${x.id}">${providers.map(o=>`<option value="${o.value}" ${x.provider===o.value?'selected':''}>${escapeHtml(o.label)}</option>`).join('')}</select></td><td><input type="number" min="0" data-budget-field="planned" data-id="${x.id}" value="${Number(x.planned)||0}"></td><td><input type="number" min="0" data-budget-field="quote" data-id="${x.id}" value="${Number(x.quote)||0}"></td><td><input type="number" min="0" data-budget-field="committed" data-id="${x.id}" value="${Number(x.committed)||0}"></td><td><input type="number" min="0" data-budget-field="paid" data-id="${x.id}" value="${Number(x.paid)||0}"></td><td class="nowrap">${euro((Number(x.committed)||0)-(Number(x.paid)||0))}</td><td><input type="date" data-budget-field="due" data-id="${x.id}" value="${escapeHtml(x.due||'')}"></td><td><select data-budget-field="status" data-id="${x.id}">${Object.entries(BUDGET_STATUS).map(([v,l])=>`<option value="${v}" ${x.status===v?'selected':''}>${l}</option>`).join('')}</select></td><td><button class="btn btn-ghost btn-sm text-danger" data-action="delete-budget" data-event="${e.id}" data-id="${x.id}">🗑</button></td></tr>`).join('')}</tbody></table></div><p class="small-note">Les modifications dans le tableau sont enregistrées dès que tu quittes un champ.</p>`}

const PLAN_KIND_LABEL={round:'Table ronde',rect:'Table rectangulaire',square:'Table carrée',honour:'Table d’honneur',buffet:'Buffet',stage:'Scène',dance:'Piste de danse',bar:'Bar',welcome:'Accueil',video:'Vidéoprojecteur'};
const PLAN_KIND_ICON={round:'◯',rect:'▭',square:'□',honour:'★',buffet:'🍽',stage:'🎤',dance:'♫',bar:'🍸',welcome:'⌂',video:'▣'};
let selectedPlanId=null;
function planClass(kind){if(kind==='round')return'round';if(['rect','square','honour'].includes(kind))return kind==='square'?'square':kind==='honour'?'honneur':'rect';return'zone'}
function renderPlan(e){const seats=e.plan.reduce((s,x)=>s+(Number(x.seats)||0),0),g=guestTotals(e);const selected=e.plan.find(x=>x.id===selectedPlanId)||null;return `${sectionTitle('Plan de salle','Déplace les éléments au doigt ou à la souris. Les positions sont sauvegardées automatiquement.')}<div class="plan-counter">${badge(`${seats} places disponibles`,'gold')}${badge(`${g.placed} invités placés`,'ok')}${badge(`${Math.max(0,g.confirmed-g.placed)} à placer`,g.confirmed-g.placed>0?'warn':'ok')}</div><div class="plan-layout"><aside class="plan-tools"><h3>Ajouter</h3><div class="tool-grid">${Object.entries(PLAN_KIND_LABEL).map(([k,l])=>`<button class="tool-btn" data-action="add-plan" data-event="${e.id}" data-kind="${k}">${PLAN_KIND_ICON[k]} ${l}</button>`).join('')}</div>${selected?`<div class="plan-editor"><h3>Élément sélectionné</h3><div class="field"><label>Nom</label><input class="input" data-plan-edit="name" data-id="${selected.id}" value="${escapeHtml(selected.name)}"></div><div class="field" style="margin-top:8px"><label>Places</label><input class="input" type="number" min="0" data-plan-edit="seats" data-id="${selected.id}" value="${Number(selected.seats)||0}"></div><div class="toolbar-group" style="margin-top:10px"><button class="btn btn-light btn-sm" data-action="duplicate-plan" data-event="${e.id}" data-id="${selected.id}">Dupliquer</button><button class="btn btn-danger btn-sm" data-action="delete-plan" data-event="${e.id}" data-id="${selected.id}">Supprimer</button></div></div>`:`<p class="small-note" style="margin-top:12px">Touchez un élément du plan pour modifier son nom, ses places ou le supprimer.</p>`}</aside><div class="plan-stage-wrap"><div class="plan-stage" id="plan-stage">${e.plan.map(x=>`<div class="plan-item ${planClass(x.kind)} ${x.id===selectedPlanId?'selected':''}" data-plan-item="${x.id}" style="left:${x.x}%;top:${x.y}%;width:${x.w}%;height:${x.h}%"><span>${PLAN_KIND_ICON[x.kind]||''} ${escapeHtml(x.name)}${x.seats?`<br><small>${x.seats} places</small>`:''}</span></div>`).join('')}</div></div></div><div class="card" style="margin-top:14px"><h3>Placement des invités</h3><p class="small-note">Attribue les invités à une table depuis le module « Invités ». Le compteur ci-dessus indique automatiquement qui reste à placer.</p><button class="btn btn-light" data-nav="#/event/${e.id}/guests">Ouvrir la liste des invités</button></div>`}
function renderGuests(e){const g=guestTotals(e);const tableOptions=[{value:'',label:'Non placé'},...e.plan.filter(x=>Number(x.seats)>0).map(x=>({value:x.id,label:x.name}))];return `${sectionTitle(e.type==='seminaire'?'Participants':'Invités','Liste, confirmations, régimes alimentaires, hébergement et placement.',`<button class="btn btn-primary btn-sm" data-action="add-guest" data-event="${e.id}">＋ Ajouter</button>`)}<div class="grid grid-4" style="margin-bottom:12px">${stat('Total',String(g.total),`Objectif ${e.guestTarget}`)}${stat('Confirmés',String(g.confirmed))}${stat('En attente',String(g.pending))}${stat('Hébergés',String(g.lodged))}</div>${e.guests.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Nom</th><th>Présence</th><th>Groupe / société</th><th>Régime / allergie</th><th>Hébergement</th><th>Table</th><th></th></tr></thead><tbody>${e.guests.map(x=>`<tr><td><strong>${escapeHtml(x.firstName)} ${escapeHtml(x.lastName)}</strong><div class="row-sub">${escapeHtml(x.phone||x.email||'')}</div></td><td><select data-guest-field="status" data-id="${x.id}">${Object.entries(GUEST_STATUS).map(([v,l])=>`<option value="${v}" ${x.status===v?'selected':''}>${l}</option>`).join('')}</select></td><td>${escapeHtml(x.company||x.group||'—')}</td><td>${escapeHtml(x.diet||'—')}</td><td><input type="checkbox" data-guest-check="lodging" data-id="${x.id}" ${x.lodging?'checked':''}></td><td><select data-guest-field="tableId" data-id="${x.id}">${tableOptions.map(o=>`<option value="${o.value}" ${x.tableId===o.value?'selected':''}>${escapeHtml(o.label)}</option>`).join('')}</select></td><td class="nowrap"><button class="btn btn-ghost btn-sm" data-action="edit-guest" data-event="${e.id}" data-id="${x.id}">✎</button><button class="btn btn-ghost btn-sm text-danger" data-action="delete-guest" data-event="${e.id}" data-id="${x.id}">🗑</button></td></tr>`).join('')}</tbody></table></div>`:emptyState('👥','Aucun invité ajouté','Ajoute les personnes au fur et à mesure des réponses.',`<button class="btn btn-primary" data-action="add-guest" data-event="${e.id}">＋ Ajouter un invité</button>`)}`}

function renderChecklist(e){const done=e.checklist.filter(x=>x.done).length,cats=[...new Set(e.checklist.map(x=>x.category))];return `${sectionTitle('Checklist opérationnelle',`${done}/${e.checklist.length} tâches cochées.`,`<button class="btn btn-primary btn-sm" data-action="add-check" data-event="${e.id}">＋ Ajouter une tâche</button>`)}<div class="card" style="margin-bottom:12px"><div style="display:flex;justify-content:space-between;gap:10px;font-size:12px;margin-bottom:7px"><strong>Progression globale</strong><span>${e.checklist.length?Math.round(done/e.checklist.length*100):0}%</span></div>${progressBar(e.checklist.length?done/e.checklist.length*100:0)}</div>${cats.map(c=>`<div class="card" style="margin-bottom:12px"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px"><h3 style="margin:0;color:var(--navy)">${escapeHtml(c)}</h3>${badge(`${e.checklist.filter(x=>x.category===c&&x.done).length}/${e.checklist.filter(x=>x.category===c).length}`,'gold')}</div><div class="list" style="margin-top:10px">${e.checklist.filter(x=>x.category===c).map(x=>`<div class="row ${x.done?'row-done':''} ${dateAlertClass(x.due,x.done)}"><div><label style="display:flex;gap:10px;align-items:start"><input type="checkbox" data-action="toggle-check" data-event="${e.id}" data-id="${x.id}" ${x.done?'checked':''} style="width:20px;height:20px;accent-color:var(--navy)"><span><div class="row-title">${escapeHtml(x.title)}</div><div class="row-sub">${dateFr(x.due)} · ${escapeHtml(x.owner||'Sans responsable')} ${x.comment?`· ${escapeHtml(x.comment)}`:''}</div></span></label></div><div class="row-actions">${priorityBadge(x.priority)}<button class="btn btn-ghost btn-sm" data-action="edit-check" data-event="${e.id}" data-id="${x.id}">✎</button><button class="btn btn-ghost btn-sm text-danger" data-action="delete-check" data-event="${e.id}" data-id="${x.id}">🗑</button></div></div>`).join('')}</div></div>`).join('')}`}

function renderTeam(e){const unassigned=e.tasks.filter(x=>!x.memberId).length;const workload=e.team.map(m=>({m,count:e.tasks.filter(t=>t.memberId===m.id&&t.status!=='done').length}));return `${sectionTitle('Équipe & répartition des tâches','Qui fait quoi, pour quand, et où sont les surcharges.',`<div class="toolbar-group"><button class="btn btn-light btn-sm" data-action="add-member" data-event="${e.id}">＋ Membre</button><button class="btn btn-primary btn-sm" data-action="add-task" data-event="${e.id}">＋ Tâche</button></div>`)}<div class="grid grid-3" style="margin-bottom:12px">${stat('Membres',String(e.team.length))}${stat('Tâches ouvertes',String(e.tasks.filter(x=>x.status!=='done').length))}${stat('Sans responsable',String(unassigned))}</div><div class="grid grid-2"><div class="card"><h3>Équipe</h3><div class="people-grid">${workload.map(({m,count})=>`<div class="person-card"><div style="display:flex;justify-content:space-between;gap:8px"><div><h4>${escapeHtml(m.name)}</h4><p>${escapeHtml(m.role)}</p></div>${count>=5?badge(`${count} ouvertes`,'danger'):badge(`${count} ouvertes`,count?'warn':'ok')}</div>${m.phone?`<p>📞 ${escapeHtml(m.phone)}</p>`:''}<div style="margin-top:8px"><button class="btn btn-ghost btn-sm" data-action="edit-member" data-event="${e.id}" data-id="${m.id}">Modifier</button><button class="btn btn-ghost btn-sm text-danger" data-action="delete-member" data-event="${e.id}" data-id="${m.id}">Suppr.</button></div></div>`).join('')}</div></div><div class="card"><h3>Tâches</h3>${e.tasks.length?`<div class="list">${e.tasks.map(x=>{const m=e.team.find(m=>m.id===x.memberId);return `<div class="row ${dateAlertClass(x.due,x.status==='done')} ${x.status==='done'?'row-done':''}"><div><div class="row-title">${escapeHtml(x.title)}</div><div class="row-sub">${m?escapeHtml(m.name):'<span class="text-danger">Sans responsable</span>'} · ${dateFr(x.due)}</div></div><div class="row-actions">${statusBadge(x.status)}${priorityBadge(x.priority)}<button class="btn btn-ghost btn-sm" data-action="edit-task" data-event="${e.id}" data-id="${x.id}">✎</button><button class="btn btn-ghost btn-sm text-danger" data-action="delete-task" data-event="${e.id}" data-id="${x.id}">🗑</button></div></div>`}).join('')}</div>`:emptyState('🧑‍🤝‍🧑','Aucune tâche d’équipe','Crée les tâches opérationnelles et affecte-les aux personnes responsables.')}</div></div>`}

function renderProviders(e){const sum=e.providers.reduce((s,x)=>s+Number(x.amount||0),0),confirmed=e.providers.filter(x=>x.status==='confirmed').length;return `${sectionTitle('Prestataires','Contacts, devis, acomptes, échéances et statut.',`<button class="btn btn-primary btn-sm" data-action="add-provider" data-event="${e.id}">＋ Ajouter un prestataire</button>`)}<div class="grid grid-3" style="margin-bottom:12px">${stat('Fiches',String(e.providers.length))}${stat('Confirmés',String(confirmed))}${stat('Montant total',euro(sum))}</div><div class="list">${e.providers.map(x=>`<div class="row"><div><div style="display:flex;gap:6px;flex-wrap:wrap;align-items:center">${badge(x.category,'gold')}${providerBadge(x.status)}</div><div class="row-title" style="margin-top:5px">${escapeHtml(x.name||`${x.category} à trouver`)}</div><div class="row-sub">${escapeHtml(x.contact||'Contact à compléter')} ${x.phone?`· ${escapeHtml(x.phone)}`:''} ${x.email?`· ${escapeHtml(x.email)}`:''}</div><div class="row-sub">Montant ${euro(x.amount)} · acompte ${euro(x.deposit)} · solde ${euro((Number(x.amount)||0)-(Number(x.deposit)||0))}${x.due?` · échéance ${dateFr(x.due)}`:''}</div>${x.notes?`<div class="row-sub">${escapeHtml(x.notes)}</div>`:''}</div><div class="row-actions"><button class="btn btn-light btn-sm" data-action="edit-provider" data-event="${e.id}" data-id="${x.id}">Modifier</button><button class="btn btn-ghost btn-sm text-danger" data-action="delete-provider" data-event="${e.id}" data-id="${x.id}">🗑</button></div></div>`).join('')}</div>`}

function renderRun(e){return `${sectionTitle('Conducteur de journée','Timeline opérationnelle du jour J. Les horaires sont entièrement modifiables.',`<button class="btn btn-primary btn-sm" data-action="add-run" data-event="${e.id}">＋ Ajouter une séquence</button>`)}<div class="toolbar"><div class="toolbar-group">${badge(`${e.run.length} séquences`,'gold')}${badge(`${e.run.filter(x=>x.status==='done').length} terminées`,'ok')}</div><button class="btn btn-light btn-sm" data-action="day-mode" data-event="${e.id}">☀ Mode Jour J</button></div><div class="timeline">${[...e.run].sort((a,b)=>a.start.localeCompare(b.start)).map(x=>`<article class="timeline-item ${x.status==='done'?'row-done':''}"><div style="display:flex;justify-content:space-between;gap:12px;align-items:start"><div><div class="timeline-time">${escapeHtml(x.start)} → ${escapeHtml(x.end)}</div><div class="timeline-main">${escapeHtml(x.action)}</div><div class="timeline-sub">📍 ${escapeHtml(x.place||'—')} · 👤 ${escapeHtml(x.owner||'Sans responsable')}</div>${x.needs?`<div class="timeline-sub">Matériel : ${escapeHtml(x.needs)}</div>`:''}${x.notes?`<div class="timeline-sub">${escapeHtml(x.notes)}</div>`:''}<div style="margin-top:7px">${statusBadge(x.status)}</div></div><div class="row-actions"><button class="btn btn-light btn-sm" data-action="toggle-run" data-event="${e.id}" data-id="${x.id}">${x.status==='done'?'↶':'✓'}</button><button class="btn btn-ghost btn-sm" data-action="edit-run" data-event="${e.id}" data-id="${x.id}">✎</button><button class="btn btn-ghost btn-sm text-danger" data-action="delete-run" data-event="${e.id}" data-id="${x.id}">🗑</button></div></div></article>`).join('')}</div>`}

function renderDocs(e){const docs=[['summary','Fiche récapitulative','Les informations essentielles, contacts, budget et état de préparation.'],['retro','Rétroplanning','Toutes les échéances, responsables et statuts.'],['budget','Budget','Prévisionnel, engagements, paiements et reste à payer.'],['checklist','Checklist','Checklist opérationnelle par catégorie.'],['plan','Plan de salle','Plan visuel avec tables, zones et capacités.'],['guests',e.type==='seminaire'?'Participants':'Invités','Présences, régimes, hébergement et tables.'],['providers','Prestataires','Contacts, montants, acomptes et statuts.'],['team','Répartition des tâches','Équipe, responsabilités, échéances et statuts.'],['run','Conducteur de journée','Timeline détaillée du jour J.'],['contacts','Contacts utiles','Contact principal, équipe et prestataires.']];return `${sectionTitle('Documents à imprimer','Chaque document utilise une mise en page A4 propre avec en-tête JLG Event Builder.')}<div class="doc-grid">${docs.map(([k,t,d])=>`<article class="doc-card"><h3>${escapeHtml(t)}</h3><p>${escapeHtml(d)}</p><button class="btn btn-light btn-sm" data-action="print-doc" data-event="${e.id}" data-doc="${k}">🖨 Imprimer / PDF</button></article>`).join('')}</div><div class="card" style="margin-top:14px"><h3>Sauvegarde du dossier</h3><p class="small-note">En plus des documents imprimables, tu peux exporter ce seul événement en JSON pour l’archiver ou le transférer.</p><button class="btn btn-primary btn-sm" data-action="export-event" data-event="${e.id}">⬇ Exporter cet événement</button></div>`}
function bindGlobal(){
 els('[data-nav]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();navTo(b.dataset.nav)}));
 el('#event-search')?.addEventListener('input',filterEventList);el('#event-filter')?.addEventListener('change',filterEventList);
 els('[data-action]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',handleAction)});
}
function filterEventList(){const q=(el('#event-search')?.value||'').trim().toLowerCase(),f=el('#event-filter')?.value||'all';let arr=state.events.filter(e=>!q||[e.name,e.place,TYPE_LABEL[e.type]].join(' ').toLowerCase().includes(q));if(f==='upcoming')arr=arr.filter(e=>daysDiff(e.date)>=0);if(f==='past')arr=arr.filter(e=>daysDiff(e.date)<0);el('#event-list').innerHTML=renderEventList(arr);els('[data-nav]',el('#event-list')).forEach(b=>b.onclick=()=>navTo(b.dataset.nav));els('[data-action]',el('#event-list')).forEach(b=>b.onclick=handleAction)}
function handleAction(ev){ev.preventDefault();const b=ev.currentTarget,a=b.dataset.action,id=b.dataset.event,sub=b.dataset.id;const e=id?getEvent(id):null;
 if(a==='duplicate-event'&&e){const copy=JSON.parse(JSON.stringify(e));copy.id=uid('ev');copy.name=e.name+' — copie';copy.createdAt=new Date().toISOString();copy.retro.forEach(x=>x.id=uid('rt'));copy.budget.forEach(x=>x.id=uid('bud'));copy.plan.forEach(x=>x.id=uid('pl'));copy.guests.forEach(x=>x.id=uid('gst'));copy.checklist.forEach(x=>x.id=uid('chk'));copy.team.forEach(x=>x.id=uid('mem'));copy.tasks.forEach(x=>x.id=uid('tsk'));copy.providers.forEach(x=>x.id=uid('pro'));copy.run.forEach(x=>x.id=uid('run'));state.events.unshift(copy);saveState();toast('Événement dupliqué.');render();return}
 if(a==='edit-event'&&e)return modalEvent(e);
 if(a==='delete-event'&&e){if(confirmAction(`Supprimer définitivement « ${e.name} » ?`)){state.events=state.events.filter(x=>x.id!==e.id);saveState();toast('Événement supprimé.');navTo('#/')}return}
 if(!e)return;
 const find=(key)=>e[key].find(x=>x.id===sub);
 if(a==='add-retro')return modalRetro(e);if(a==='edit-retro')return modalRetro(e,find('retro'));if(a==='toggle-retro'){const x=find('retro');x.status=x.status==='done'?'todo':'done';saveState();render();return}if(a==='delete-retro'){if(confirmAction('Supprimer cette étape ?')){e.retro=e.retro.filter(x=>x.id!==sub);saveState();render()}return}
 if(a==='add-budget'){e.budget.push({id:uid('bud'),category:'Nouvelle catégorie',label:'Nouvelle ligne',planned:0,quote:0,committed:0,paid:0,provider:'',due:'',status:'planned'});saveState();render();return}if(a==='delete-budget'){if(confirmAction('Supprimer cette ligne budgétaire ?')){e.budget=e.budget.filter(x=>x.id!==sub);saveState();render()}return}
 if(a==='add-plan')return addPlanItem(e,b.dataset.kind);if(a==='duplicate-plan'){const x=find('plan');if(x){e.plan.push({...x,id:uid('pl'),name:x.name+' copie',x:clamp(x.x+4,0,90),y:clamp(x.y+4,0,90)});selectedPlanId=e.plan.at(-1).id;saveState();render()}return}if(a==='delete-plan'){if(confirmAction('Supprimer cet élément du plan ?')){e.guests.forEach(g=>{if(g.tableId===sub)g.tableId=''});e.plan=e.plan.filter(x=>x.id!==sub);selectedPlanId=null;saveState();render()}return}
 if(a==='add-guest')return modalGuest(e);if(a==='edit-guest')return modalGuest(e,find('guests'));if(a==='delete-guest'){if(confirmAction('Supprimer cette personne ?')){e.guests=e.guests.filter(x=>x.id!==sub);saveState();render()}return}
 if(a==='add-check')return modalCheck(e);if(a==='edit-check')return modalCheck(e,find('checklist'));if(a==='toggle-check'){const x=find('checklist');x.done=!x.done;saveState();render();return}if(a==='delete-check'){if(confirmAction('Supprimer cette tâche de checklist ?')){e.checklist=e.checklist.filter(x=>x.id!==sub);saveState();render()}return}
 if(a==='add-member')return modalMember(e);if(a==='edit-member')return modalMember(e,find('team'));if(a==='delete-member'){const used=e.tasks.some(t=>t.memberId===sub);if(used&&!confirmAction('Ce membre a des tâches affectées. Les tâches deviendront sans responsable. Continuer ?'))return;e.tasks.forEach(t=>{if(t.memberId===sub)t.memberId=''});e.team=e.team.filter(x=>x.id!==sub);saveState();render();return}
 if(a==='add-task')return modalTask(e);if(a==='edit-task')return modalTask(e,find('tasks'));if(a==='delete-task'){if(confirmAction('Supprimer cette tâche ?')){e.tasks=e.tasks.filter(x=>x.id!==sub);saveState();render()}return}
 if(a==='add-provider')return modalProvider(e);if(a==='edit-provider')return modalProvider(e,find('providers'));if(a==='delete-provider'){if(confirmAction('Supprimer ce prestataire ?')){e.providers=e.providers.filter(x=>x.id!==sub);saveState();render()}return}
 if(a==='add-run')return modalRun(e);if(a==='edit-run')return modalRun(e,find('run'));if(a==='toggle-run'){const x=find('run');x.status=x.status==='done'?'todo':'done';saveState();render();return}if(a==='delete-run'){if(confirmAction('Supprimer cette séquence ?')){e.run=e.run.filter(x=>x.id!==sub);saveState();render()}return}if(a==='day-mode')return openDayMode(e);
 if(a==='print-doc')return printDocument(e,b.dataset.doc);if(a==='export-event')return download(`jlg-event-${safeFile(e.name)}-${e.date}.json`,JSON.stringify({version:APP_VERSION,events:[e]},null,2));
}
function safeFile(s){return String(s||'evenement').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'').toLowerCase()}

function bindEventModule(e,module){
 if(module==='budget'){els('[data-budget-field]').forEach(inp=>inp.addEventListener('change',()=>{const x=e.budget.find(y=>y.id===inp.dataset.id);if(!x)return;const k=inp.dataset.budgetField;x[k]=['planned','quote','committed','paid'].includes(k)?Number(inp.value)||0:inp.value;saveState();render()}))}
 if(module==='guests'){els('[data-guest-field]').forEach(inp=>inp.addEventListener('change',()=>{const x=e.guests.find(y=>y.id===inp.dataset.id);if(x){x[inp.dataset.guestField]=inp.value;saveState();render()}}));els('[data-guest-check]').forEach(inp=>inp.addEventListener('change',()=>{const x=e.guests.find(y=>y.id===inp.dataset.id);if(x){x[inp.dataset.guestCheck]=inp.checked;saveState();render()}}))}
 if(module==='plan')bindPlan(e);
}
function modalEvent(e){
 const body=`<div class="form-grid">${inputField('name','Nom',e.name,'text','required')}${selectField('type','Type',Object.entries(TYPE_LABEL).map(([value,label])=>({value,label})),e.type)}${inputField('date','Date',e.date,'date','required')}${inputField('start','Début',e.start,'time')}${inputField('end','Fin',e.end,'time')}${inputField('place','Lieu',e.place)}${inputField('guestTarget','Invités / participants prévus',e.guestTarget,'number','min="0"')}${inputField('budgetTotal','Budget global (€)',e.budgetTotal,'number','min="0" step="100"')}${inputField('contactName','Contact principal',e.contactName)}${inputField('contactPhone','Téléphone',e.contactPhone,'tel')}${inputField('contactEmail','E-mail',e.contactEmail,'email')}<div></div>${textareaField('notes','Notes',e.notes)}</div>`;
 openModal('Modifier l’événement',body,(form,close)=>{const v=serializeForm(form);Object.assign(e,{name:v.name,type:v.type,date:v.date,start:v.start,end:v.end,place:v.place,guestTarget:Number(v.guestTarget)||0,budgetTotal:Number(v.budgetTotal)||0,contactName:v.contactName,contactPhone:v.contactPhone,contactEmail:v.contactEmail,notes:v.notes});saveState();close();toast('Événement mis à jour.');render()});
}
function modalRetro(e,x=null){x=x||{title:'',desc:'',due:e.date,owner:'',status:'todo',priority:'normal',notes:''};const body=`<div class="form-grid">${inputField('title','Étape',x.title,'text','required')}${inputField('due','Échéance',x.due,'date')}${inputField('owner','Responsable',x.owner)}${selectField('status','Statut',Object.entries(STATUS_LABEL).map(([value,label])=>({value,label})),x.status)}${selectField('priority','Priorité',Object.entries(PRIORITY_LABEL).map(([value,label])=>({value,label})),x.priority)}<div></div>${textareaField('desc','Description',x.desc)}${textareaField('notes','Notes',x.notes)}</div>`;openModal(x.id?'Modifier l’étape':'Ajouter une étape',body,(f,c)=>{const v=serializeForm(f);if(x.id)Object.assign(x,v);else e.retro.push({id:uid('rt'),...v});saveState();c();render()})}
function modalGuest(e,x=null){
 x=x||{firstName:'',lastName:'',group:'',company:'',email:'',phone:'',status:'pending',child:false,diet:'',lodging:false,room:'',tableId:'',role:'',attendance:'full',workshop:'',notes:''};
 const tables=[{value:'',label:'Non placé'},...e.plan.filter(p=>Number(p.seats)>0).map(p=>({value:p.id,label:p.name}))];
 const seminar=e.type==='seminaire'?`${inputField('role','Fonction',x.role)}${selectField('attendance','Présence',[{value:'full',label:'Journée complète'},{value:'morning',label:'Matin uniquement'},{value:'afternoon',label:'Après-midi uniquement'}],x.attendance||'full')}${inputField('workshop','Atelier / groupe',x.workshop||'')}${inputField('room','Chambre',x.room||'')}`:`${inputField('room','Chambre / hébergement',x.room||'')}<div></div>`;
 const body=`<div class="form-grid">${inputField('firstName','Prénom',x.firstName,'text','required')}${inputField('lastName','Nom',x.lastName,'text','required')}${inputField('group','Famille / groupe',x.group)}${inputField('company','Société',x.company)}${inputField('email','E-mail',x.email,'email')}${inputField('phone','Téléphone',x.phone,'tel')}${selectField('status','Présence',Object.entries(GUEST_STATUS).map(([value,label])=>({value,label})),x.status)}${selectField('tableId','Table',tables,x.tableId)}${inputField('diet','Régime / allergie',x.diet)}${seminar}<div class="field"><label><input type="checkbox" name="child" ${x.child?'checked':''}> Enfant</label></div><div class="field"><label><input type="checkbox" name="lodging" ${x.lodging?'checked':''}> Hébergement prévu</label></div>${textareaField('notes','Notes',x.notes)}</div>`;
 openModal(x.id?'Modifier la personne':'Ajouter une personne',body,(f,c)=>{const fd=new FormData(f),v=Object.fromEntries(fd.entries());v.child=fd.has('child');v.lodging=fd.has('lodging');if(x.id)Object.assign(x,v);else e.guests.push({id:uid('gst'),...v});saveState();c();render()})
}
function modalCheck(e,x=null){x=x||{category:'Avant événement',title:'',done:false,owner:'',due:e.date,priority:'normal',comment:''};const cats=['Avant événement','Accueil','Salle','Restauration','Boissons','Technique','Hébergement','Décoration','Signalétique','Sécurité','Nettoyage','Clôture','Autre'];const body=`<div class="form-grid">${inputField('title','Tâche',x.title,'text','required')}${selectField('category','Catégorie',cats,x.category)}${inputField('owner','Responsable',x.owner)}${inputField('due','Échéance',x.due,'date')}${selectField('priority','Priorité',Object.entries(PRIORITY_LABEL).map(([value,label])=>({value,label})),x.priority)}<div class="field"><label><input type="checkbox" name="done" ${x.done?'checked':''}> Tâche terminée</label></div>${textareaField('comment','Commentaire',x.comment)}</div>`;openModal(x.id?'Modifier la tâche':'Ajouter une tâche',body,(f,c)=>{const fd=new FormData(f),v=Object.fromEntries(fd.entries());v.done=fd.has('done');if(x.id)Object.assign(x,v);else e.checklist.push({id:uid('chk'),...v});saveState();c();render()})}
function modalMember(e,x=null){x=x||{name:'',role:'',phone:'',email:''};const body=`<div class="form-grid">${inputField('name','Nom / rôle opérationnel',x.name,'text','required')}${inputField('role','Service / fonction',x.role)}${inputField('phone','Téléphone',x.phone,'tel')}${inputField('email','E-mail',x.email,'email')}</div>`;openModal(x.id?'Modifier le membre':'Ajouter un membre',body,(f,c)=>{const v=serializeForm(f);if(x.id)Object.assign(x,v);else e.team.push({id:uid('mem'),...v});saveState();c();render()})}
function modalTask(e,x=null){x=x||{title:'',memberId:'',due:e.date,status:'todo',priority:'normal',notes:''};const members=[{value:'',label:'Sans responsable'},...e.team.map(m=>({value:m.id,label:`${m.name} — ${m.role}`}))];const body=`<div class="form-grid">${inputField('title','Tâche',x.title,'text','required')}${selectField('memberId','Responsable',members,x.memberId)}${inputField('due','Échéance',x.due,'date')}${selectField('status','Statut',Object.entries(STATUS_LABEL).map(([value,label])=>({value,label})),x.status)}${selectField('priority','Priorité',Object.entries(PRIORITY_LABEL).map(([value,label])=>({value,label})),x.priority)}<div></div>${textareaField('notes','Notes',x.notes)}</div>`;openModal(x.id?'Modifier la tâche':'Ajouter une tâche',body,(f,c)=>{const v=serializeForm(f);if(x.id)Object.assign(x,v);else e.tasks.push({id:uid('tsk'),...v});saveState();c();render()})}
function modalProvider(e,x=null){x=x||{name:'',category:'Traiteur',contact:'',phone:'',email:'',site:'',amount:0,deposit:0,due:'',status:'contact',notes:''};const cats=['Traiteur','DJ / musique','Photographe','Vidéaste','Fleuriste','Décoration','Technique','Location matériel','Transport','Sécurité','Animation','Imprimeur','Hébergement','Autre'];const body=`<div class="form-grid">${inputField('name','Nom du prestataire',x.name)}${selectField('category','Catégorie',cats,x.category)}${inputField('contact','Contact',x.contact)}${inputField('phone','Téléphone',x.phone,'tel')}${inputField('email','E-mail',x.email,'email')}${inputField('site','Site web',x.site,'url')}${inputField('amount','Montant total (€)',x.amount,'number','min="0"')}${inputField('deposit','Acompte versé (€)',x.deposit,'number','min="0"')}${inputField('due','Échéance du solde',x.due,'date')}${selectField('status','Statut',Object.entries(PROVIDER_STATUS).map(([value,label])=>({value,label})),x.status)}${textareaField('notes','Notes',x.notes)}</div>`;openModal(x.id?'Modifier le prestataire':'Ajouter un prestataire',body,(f,c)=>{const v=serializeForm(f);v.amount=Number(v.amount)||0;v.deposit=Number(v.deposit)||0;if(x.id)Object.assign(x,v);else e.providers.push({id:uid('pro'),...v});saveState();c();render()})}
function modalRun(e,x=null){x=x||{start:e.start,end:addMinutes(e.start,30),action:'',place:e.place,owner:'',people:'',needs:'',notes:'',status:'todo'};const body=`<div class="form-grid">${inputField('start','Début',x.start,'time','required')}${inputField('end','Fin',x.end,'time','required')}${inputField('action','Action',x.action,'text','required')}${inputField('place','Lieu',x.place)}${inputField('owner','Responsable',x.owner)}${inputField('people','Personnes concernées',x.people)}${selectField('status','Statut',Object.entries(STATUS_LABEL).map(([value,label])=>({value,label})),x.status)}<div></div>${textareaField('needs','Matériel / besoins',x.needs)}${textareaField('notes','Notes',x.notes)}</div>`;openModal(x.id?'Modifier la séquence':'Ajouter une séquence',body,(f,c)=>{const v=serializeForm(f);if(x.id)Object.assign(x,v);else e.run.push({id:uid('run'),...v});saveState();c();render()})}
function addPlanItem(e,kind){const defs={round:['Table ronde',10,10,10,15,15],rect:['Table rectangulaire',8,12,12,18,10],square:['Table carrée',8,14,14,14,14],honour:['Table d’honneur',8,20,8,30,10],buffet:['Buffet',0,70,15,20,8],stage:['Scène',0,35,5,30,9],dance:['Piste de danse',0,38,42,24,18],bar:['Bar',0,5,50,14,9],welcome:['Accueil',0,5,85,18,8],video:['Vidéoprojecteur',0,72,5,13,7]};const [name,seats,x,y,w,h]=defs[kind]||['Élément',0,10,10,15,10];const item={id:uid('pl'),kind,name,seats,x,y,w,h};e.plan.push(item);selectedPlanId=item.id;saveState();render()}
function bindPlan(e){
 const stage=el('#plan-stage');if(!stage)return;
 els('[data-plan-edit]').forEach(inp=>inp.addEventListener('change',()=>{const x=e.plan.find(y=>y.id===inp.dataset.id);if(!x)return;x[inp.dataset.planEdit]=inp.dataset.planEdit==='seats'?Number(inp.value)||0:inp.value;saveState();render()}));
 let drag=null;
 els('[data-plan-item]',stage).forEach(item=>{
   item.addEventListener('pointerdown',ev=>{ev.preventDefault();selectedPlanId=item.dataset.planItem;const x=e.plan.find(y=>y.id===selectedPlanId);if(!x)return;const rect=stage.getBoundingClientRect();drag={x,startX:ev.clientX,startY:ev.clientY,origX:x.x,origY:x.y,stageW:rect.width,stageH:rect.height};item.setPointerCapture?.(ev.pointerId);renderPlanSelectionOnly(e);});
   item.addEventListener('pointermove',ev=>{if(!drag||drag.x.id!==item.dataset.planItem)return;const nx=drag.origX+(ev.clientX-drag.startX)/drag.stageW*100,ny=drag.origY+(ev.clientY-drag.startY)/drag.stageH*100;drag.x.x=clamp(nx,0,100-drag.x.w);drag.x.y=clamp(ny,0,100-drag.x.h);item.style.left=drag.x.x+'%';item.style.top=drag.x.y+'%';});
   item.addEventListener('pointerup',()=>{if(drag){saveState();drag=null;render()}});item.addEventListener('pointercancel',()=>{drag=null});
   item.addEventListener('click',()=>{selectedPlanId=item.dataset.planItem;render()});
 });
}
function renderPlanSelectionOnly(e){els('[data-plan-item]').forEach(n=>n.classList.toggle('selected',n.dataset.planItem===selectedPlanId))}

function openDayMode(e){const rows=[...e.run].sort((a,b)=>a.start.localeCompare(b.start));const body=`<div style="background:var(--navy);color:#fff;border-radius:16px;padding:16px;margin-bottom:12px"><div class="stat-label" style="color:var(--gold2)">MODE JOUR J</div><div style="font-family:Georgia,serif;font-size:26px;margin-top:4px">${escapeHtml(e.name)}</div><div style="opacity:.8;margin-top:4px">${dateFr(e.date)} · ${escapeHtml(e.place)}</div></div><div class="list">${rows.map(x=>`<div class="row ${x.status==='done'?'row-done':''}"><div><div style="font-size:22px;font-weight:900;color:var(--navy)">${escapeHtml(x.start)}–${escapeHtml(x.end)}</div><div class="row-title">${escapeHtml(x.action)}</div><div class="row-sub">${escapeHtml(x.place||'—')} · ${escapeHtml(x.owner||'Sans responsable')}</div></div><div>${statusBadge(x.status)}</div></div>`).join('')}</div>`;openModal('Conducteur — Jour J',body,(f,c)=>c(),{submitLabel:'Fermer',width:'900px'})}

function printHeader(e,title){return `<div class="print-head"><div><strong>JLG Event Builder</strong><small> · JLG Creative</small></div><div class="right"><strong style="font-size:14px">${escapeHtml(e.name)}</strong><br><small>${dateFr(e.date)}</small></div></div><div class="print-title">${escapeHtml(title)}</div><div class="print-sub">${TYPE_LABEL[e.type]} · ${escapeHtml(e.place||'Lieu à préciser')} · ${e.guestTarget} personnes prévues · Généré le ${dateFr(isoToday())}</div>`}
function printDocument(e,kind){let html=printHeader(e,{summary:'Fiche récapitulative',retro:'Rétroplanning',budget:'Budget',checklist:'Checklist opérationnelle',plan:'Plan de salle',guests:e.type==='seminaire'?'Participants':'Invités',providers:'Prestataires',team:'Répartition des tâches',run:'Conducteur de journée',contacts:'Contacts utiles'}[kind]||'Document');const b=budgetTotals(e),g=guestTotals(e);
 if(kind==='summary'){html+=`<div class="print-grid"><div class="print-box"><strong>Date & horaires</strong><br>${dateFr(e.date)} · ${escapeHtml(e.start)}–${escapeHtml(e.end)}</div><div class="print-box"><strong>Lieu</strong><br>${escapeHtml(e.place||'—')}</div><div class="print-box"><strong>Invités / participants</strong><br>${g.confirmed} confirmés / objectif ${e.guestTarget}</div><div class="print-box"><strong>Budget</strong><br>${euro(b.committed)} engagés / ${euro(e.budgetTotal)}</div></div><div class="print-section"><h2>Contact principal</h2><p>${escapeHtml(e.contactName||'—')} · ${escapeHtml(e.contactPhone||'')} · ${escapeHtml(e.contactEmail||'')}</p></div><div class="print-section"><h2>Options</h2><p>${e.options.length?e.options.map(escapeHtml).join(' · '):'Aucune option sélectionnée'}</p></div><div class="print-section"><h2>Notes</h2><p>${escapeHtml(e.notes||'—').replace(/\n/g,'<br>')}</p></div><div class="print-section"><h2>État de préparation</h2><p>${eventProgress(e)}% · ${e.retro.filter(x=>x.status==='done').length}/${e.retro.length} étapes du rétroplanning terminées · ${e.checklist.filter(x=>x.done).length}/${e.checklist.length} tâches de checklist cochées.</p></div>`}
 if(kind==='retro')html+=`<table class="print-table"><thead><tr><th>Date</th><th>Étape</th><th>Responsable</th><th>Priorité</th><th>Statut</th></tr></thead><tbody>${[...e.retro].sort((a,b)=>a.due.localeCompare(b.due)).map(x=>`<tr><td>${dateShort(x.due)}</td><td><strong>${escapeHtml(x.title)}</strong><br>${escapeHtml(x.desc||'')}</td><td>${escapeHtml(x.owner||'—')}</td><td>${PRIORITY_LABEL[x.priority]}</td><td>${STATUS_LABEL[x.status]}</td></tr>`).join('')}</tbody></table>`;
 if(kind==='budget')html+=`<div class="print-grid"><div class="print-box"><strong>Budget global</strong><br>${euro(e.budgetTotal)}</div><div class="print-box"><strong>Engagé</strong><br>${euro(b.committed)}</div><div class="print-box"><strong>Payé</strong><br>${euro(b.paid)}</div><div class="print-box"><strong>Disponible</strong><br>${euro(b.remainingBudget)}</div></div><div class="print-section"><table class="print-table"><thead><tr><th>Catégorie</th><th>Libellé</th><th>Prévu</th><th>Devis</th><th>Engagé</th><th>Payé</th><th>Reste</th></tr></thead><tbody>${e.budget.map(x=>`<tr><td>${escapeHtml(x.category)}</td><td>${escapeHtml(x.label)}</td><td>${euro(x.planned)}</td><td>${euro(x.quote)}</td><td>${euro(x.committed)}</td><td>${euro(x.paid)}</td><td>${euro((Number(x.committed)||0)-(Number(x.paid)||0))}</td></tr>`).join('')}</tbody></table></div>`;
 if(kind==='checklist'){const cats=[...new Set(e.checklist.map(x=>x.category))];html+=cats.map(c=>`<div class="print-section no-break"><h2>${escapeHtml(c)}</h2><table class="print-table"><tbody>${e.checklist.filter(x=>x.category===c).map(x=>`<tr><td style="width:24px">${x.done?'☑':'☐'}</td><td>${escapeHtml(x.title)}</td><td>${escapeHtml(x.owner||'—')}</td><td>${dateShort(x.due)}</td></tr>`).join('')}</tbody></table></div>`).join('')}
 if(kind==='plan'){html+=`<div class="print-section"><div class="print-plan">${e.plan.map(x=>`<div class="print-plan-item" style="left:${x.x}%;top:${x.y}%;width:${x.w}%;height:${x.h}%">${escapeHtml(x.name)}${x.seats?` · ${x.seats} pl.`:''}</div>`).join('')}</div></div><p>${g.placed} personnes placées · ${e.plan.reduce((s,x)=>s+(Number(x.seats)||0),0)} places disponibles.</p>`}
 if(kind==='guests')html+=`<table class="print-table"><thead><tr><th>Nom</th><th>Présence</th><th>Groupe / société</th><th>Régime</th><th>Hébergement</th><th>Table</th></tr></thead><tbody>${e.guests.map(x=>`<tr><td>${escapeHtml(x.firstName)} ${escapeHtml(x.lastName)}</td><td>${GUEST_STATUS[x.status]}</td><td>${escapeHtml(x.company||x.group||'—')}</td><td>${escapeHtml(x.diet||'—')}</td><td>${x.lodging?'Oui':'Non'}</td><td>${escapeHtml(e.plan.find(p=>p.id===x.tableId)?.name||'—')}</td></tr>`).join('')}</tbody></table>`;
 if(kind==='providers')html+=`<table class="print-table"><thead><tr><th>Catégorie</th><th>Prestataire</th><th>Contact</th><th>Montant</th><th>Acompte</th><th>Solde</th><th>Statut</th></tr></thead><tbody>${e.providers.map(x=>`<tr><td>${escapeHtml(x.category)}</td><td>${escapeHtml(x.name||'—')}</td><td>${escapeHtml(x.contact||'')}<br>${escapeHtml(x.phone||'')} ${escapeHtml(x.email||'')}</td><td>${euro(x.amount)}</td><td>${euro(x.deposit)}</td><td>${euro((Number(x.amount)||0)-(Number(x.deposit)||0))}</td><td>${PROVIDER_STATUS[x.status]}</td></tr>`).join('')}</tbody></table>`;
 if(kind==='team')html+=`<div class="print-section"><h2>Équipe</h2><table class="print-table"><thead><tr><th>Nom</th><th>Rôle</th><th>Contact</th></tr></thead><tbody>${e.team.map(m=>`<tr><td>${escapeHtml(m.name)}</td><td>${escapeHtml(m.role)}</td><td>${escapeHtml(m.phone||'')} ${escapeHtml(m.email||'')}</td></tr>`).join('')}</tbody></table></div><div class="print-section"><h2>Tâches</h2><table class="print-table"><thead><tr><th>Tâche</th><th>Responsable</th><th>Échéance</th><th>Priorité</th><th>Statut</th></tr></thead><tbody>${e.tasks.map(t=>`<tr><td>${escapeHtml(t.title)}</td><td>${escapeHtml(e.team.find(m=>m.id===t.memberId)?.name||'—')}</td><td>${dateShort(t.due)}</td><td>${PRIORITY_LABEL[t.priority]}</td><td>${STATUS_LABEL[t.status]}</td></tr>`).join('')}</tbody></table></div>`;
 if(kind==='run')html+=`<table class="print-table"><thead><tr><th>Horaires</th><th>Action</th><th>Lieu</th><th>Responsable</th><th>Besoins / notes</th></tr></thead><tbody>${[...e.run].sort((a,b)=>a.start.localeCompare(b.start)).map(x=>`<tr><td>${escapeHtml(x.start)}–${escapeHtml(x.end)}</td><td><strong>${escapeHtml(x.action)}</strong></td><td>${escapeHtml(x.place||'—')}</td><td>${escapeHtml(x.owner||'—')}</td><td>${escapeHtml([x.needs,x.notes].filter(Boolean).join(' · ')||'—')}</td></tr>`).join('')}</tbody></table>`;
 if(kind==='contacts')html+=`<div class="print-section"><h2>Contact principal</h2><p><strong>${escapeHtml(e.contactName||'—')}</strong><br>${escapeHtml(e.contactPhone||'')}<br>${escapeHtml(e.contactEmail||'')}</p></div><div class="print-section"><h2>Équipe</h2><table class="print-table"><tbody>${e.team.map(m=>`<tr><td><strong>${escapeHtml(m.name)}</strong><br>${escapeHtml(m.role)}</td><td>${escapeHtml(m.phone||'—')}</td><td>${escapeHtml(m.email||'—')}</td></tr>`).join('')}</tbody></table></div><div class="print-section"><h2>Prestataires</h2><table class="print-table"><tbody>${e.providers.filter(x=>x.name||x.contact).map(x=>`<tr><td>${escapeHtml(x.category)}</td><td><strong>${escapeHtml(x.name||'—')}</strong><br>${escapeHtml(x.contact||'')}</td><td>${escapeHtml(x.phone||'—')}</td><td>${escapeHtml(x.email||'—')}</td></tr>`).join('')}</tbody></table></div>`;
 const root=el('#print-root');root.innerHTML=html;root.classList.add('printing');setTimeout(()=>{window.print();setTimeout(()=>{root.classList.remove('printing');root.innerHTML=''},300)},100)
}

window.addEventListener('hashchange',render);
window.addEventListener('DOMContentLoaded',()=>{if(!location.hash)location.hash='#/';render();if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})});
})();
