(() => {
'use strict';

const APP_KEY='jlg-event-builder-v2';
const TYPE_LABEL={mariage:'Mariage',anniversaire:'Anniversaire',seminaire:'Séminaire',association:'Association',autre:'Autre'};
const PROVIDER_STATUS={contact:'À contacter',quote:'Devis demandé',option:'Option',confirmed:'Confirmé',cancelled:'Annulé'};
const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const euro=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(n)||0);
const dateFr=s=>!s?'—':new Date(s+'T12:00:00').toLocaleDateString('fr-FR',{day:'2-digit',month:'long',year:'numeric'});
const today=()=>new Date().toISOString().slice(0,10);

function state(){try{return JSON.parse(localStorage.getItem(APP_KEY)||'{"events":[]}')}catch{return{events:[]}}}
function currentEvent(){const m=(location.hash||'').match(/^#\/event\/([^/]+)/);if(!m)return null;return(state().events||[]).find(e=>e.id===m[1])||null}
function printHeader(e,title){return `<div class="print-head"><div><strong>JLG Event Builder</strong><small> · JLG Creative</small></div><div class="right"><strong style="font-size:14px">${esc(e.name)}</strong><br><small>${dateFr(e.date)}</small></div></div><div class="print-title">${esc(title)}</div><div class="print-sub">${esc(TYPE_LABEL[e.type]||e.type)} · ${esc(e.place||'Lieu à préciser')} · ${Number(e.guestTarget)||0} personnes prévues · Généré le ${dateFr(today())}</div>`}
function doPrint(html){const root=document.querySelector('#print-root');if(!root)return;root.innerHTML=html;root.classList.add('printing');setTimeout(()=>{window.print();setTimeout(()=>{root.classList.remove('printing');root.innerHTML=''},300)},100)}

function printClientBon(e){let html=printHeader(e,'Bon de confirmation client');html+=`<div class="print-grid"><div class="print-box"><strong>Client / contact principal</strong><br>${esc(e.contactName||'—')}<br>${esc(e.contactPhone||'')}<br>${esc(e.contactEmail||'')}</div><div class="print-box"><strong>Événement</strong><br>${esc(TYPE_LABEL[e.type]||e.type)}<br>${dateFr(e.date)} · ${esc(e.start||'')}–${esc(e.end||'')}<br>${esc(e.place||'Lieu à préciser')}</div><div class="print-box"><strong>Participants prévus</strong><br>${Number(e.guestTarget)||0} personne(s)</div><div class="print-box"><strong>Référence dossier</strong><br>${esc(e.id)}</div></div><div class="print-section"><h2>Prestations / options retenues</h2><p>${e.options?.length?e.options.map(esc).join(' · '):'À préciser'}</p></div><div class="print-section"><h2>Confirmation</h2><p>Ce bon récapitule les informations opérationnelles connues à ce jour. Toute modification ultérieure doit être confirmée par les parties.</p></div><div class="print-grid" style="margin-top:24px"><div class="print-box" style="min-height:100px"><strong>Client — Bon pour accord</strong><br><br>Date :<br><br>Signature :</div><div class="print-box" style="min-height:100px"><strong>Organisateur — Validation</strong><br><br>Date :<br><br>Signature :</div></div><p class="small-note" style="margin-top:12px">Document de confirmation opérationnelle. Il ne remplace pas un devis, un contrat ou une facture lorsque l’un de ces documents est requis.</p>`;doPrint(html)}

function printProviderBon(e,p){const solde=(Number(p.amount)||0)-(Number(p.deposit)||0);let html=printHeader(e,'Bon de commande prestataire');html+=`<div class="print-grid"><div class="print-box"><strong>Prestataire</strong><br>${esc(p.name||'—')}<br>${esc(p.category||'')}<br>${esc(p.contact||'')}<br>${esc(p.phone||'')}<br>${esc(p.email||'')}</div><div class="print-box"><strong>Événement concerné</strong><br>${esc(e.name)}<br>${dateFr(e.date)} · ${esc(e.start||'')}–${esc(e.end||'')}<br>${esc(e.place||'Lieu à préciser')}</div><div class="print-box"><strong>Montant convenu</strong><br>${euro(p.amount)}<br><small>Acompte : ${euro(p.deposit)}</small></div><div class="print-box"><strong>Solde à régler</strong><br>${euro(solde)}<br><small>${p.due?`Échéance : ${dateFr(p.due)}`:'Échéance à préciser'}</small></div></div><div class="print-section"><h2>Prestation commandée</h2><p><strong>${esc(p.category||'Prestation')}</strong></p><p>${esc(p.notes||'Détails à préciser').replace(/\n/g,'<br>')}</p></div><div class="print-section"><h2>Statut</h2><p>${esc(PROVIDER_STATUS[p.status]||p.status||'—')}</p></div><div class="print-grid" style="margin-top:24px"><div class="print-box" style="min-height:100px"><strong>Prestataire — Bon pour accord</strong><br><br>Date :<br><br>Signature :</div><div class="print-box" style="min-height:100px"><strong>Organisateur — Commande validée</strong><br><br>Date :<br><br>Signature :</div></div><p class="small-note" style="margin-top:12px">Ce bon formalise la commande opérationnelle liée à l’événement. Il ne remplace pas un devis, un contrat ou une facture lorsque l’un de ces documents est requis.</p>`;doPrint(html)}

function inject(){const e=currentEvent();if(!e)return;
 document.querySelectorAll('[data-action="edit-provider"]').forEach(edit=>{const row=edit.closest('.row-actions');if(!row||row.querySelector('[data-bon-provider]'))return;const id=edit.dataset.id;const btn=document.createElement('button');btn.className='btn btn-gold btn-sm';btn.type='button';btn.dataset.bonProvider=id;btn.textContent='🧾 Bon de commande';btn.addEventListener('click',ev=>{ev.preventDefault();const fresh=currentEvent();const p=fresh?.providers?.find(x=>x.id===id);if(p)printProviderBon(fresh,p)});row.insertBefore(btn,edit)});
 const grid=document.querySelector('.doc-grid');if(grid&&!grid.querySelector('[data-bon-client-card]')){const card=document.createElement('article');card.className='doc-card';card.dataset.bonClientCard='1';card.innerHTML='<h3>Bon de confirmation client</h3><p>Date, horaires, lieu, options retenues et zones de validation client / organisateur.</p><button class="btn btn-gold btn-sm" type="button">🧾 Imprimer / PDF</button>';card.querySelector('button').addEventListener('click',ev=>{ev.preventDefault();const fresh=currentEvent();if(fresh)printClientBon(fresh)});grid.prepend(card)}
}

let timer;const schedule=()=>{clearTimeout(timer);timer=setTimeout(inject,50)};
window.addEventListener('DOMContentLoaded',()=>{schedule();new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true})});
window.addEventListener('hashchange',schedule);
})();
