/* Rugby Legacy v0.4 — deep roster + premium UI + PRM-inspired match presentation */
(()=>{
const V='0.4.0';
const adds=['PIL','PIL','PIL','TAL','TAL','2L','2L','3L','3L','9','9','10','C','AIL'];
const foreignNats=['Afrique du Sud','Nouvelle-Zélande','Argentine','Fidji','Angleterre','Écosse','Géorgie','Australie','Samoa','Tonga','Irlande','Pays de Galles','Italie'];
const firstFR=['Mathis','Louis','Hugo','Baptiste','Arthur','Léo','Théo','Noé','Clément','Maxence','Antoine','Gabriel','Nicolas','Jules','Romain','Tom','Paul','Nathan'];
const lastFR=['Delaunay','Marceau','Ferrand','Borie','Lacombe','Vernet','Tessier','Aubert','Roussel','Delmas','Giraud','Carrel','Montel','Vallier','Picard','Lavigne'];
const firstINT=['Liam','Jack','Finn','Sione','Tomas','Pablo','Facundo','Ruan','Akira','Sevu','Leicester','Josh','Cameron','Blair','Santiago','Mateo','Tupou','Semi'];
const lastINT=['McKenna','Williams','Turner','Talakai','Nakoroi','Ortega','Mendoza','Pretorius','Muller','Ioaneva','Sutherland','Davies','Krielz','Vanwyk'];
const builds={PIL:[178,193,108,137],TAL:[175,188,100,119],'2L':[195,209,110,132],'3L':[184,199,96,119],'9':[168,183,72,89],'10':[176,191,80,97],C:[180,196,88,111],AIL:[174,193,80,103],AR:[176,193,82,102],UTIL:[178,193,84,106]};
const hsh=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0};
const pick=(a,s)=>a[hsh(s)%a.length];
const rng=(s,min,max)=>min+(hsh(s)%(max-min+1));
function normalizeBody(p,c,i){let b=builds[p.pos]||builds.UTIL;p.height=Math.max(b[0],Math.min(b[1],p.height||rng(c.name+'h'+i,b[0],b[1])));p.weight=Math.max(b[2],Math.min(b[3],p.weight||rng(c.name+'w'+i,b[2],b[3])));if(p.pos==='PIL'&&p.weight<110)p.weight=110;if(p.pos==='2L'&&p.height<196)p.height=196}
function filler(c,i,pos,nat){let fr=nat==='France',seed=c.name+'-'+i+'-'+pos;let ca=Math.max(48,Math.min(91,Math.round(c.strength-11+rng(seed+'ca',0,13))));let age=rng(seed+'age',19,32),b=builds[pos]||builds.UTIL;return{id:c.id+'-v04-'+i,first:pick(fr?firstFR:firstINT,seed+'f'),last:pick(fr?lastFR:lastINT,seed+'l'),pos,age,nat,height:rng(seed+'h',b[0],b[1]),weight:rng(seed+'w',b[2],b[3]),foot:rng(seed+'ft',0,4)===0?'Gauche':'Droit',ca,potential:Math.min(96,ca+rng(seed+'pot',1,9)),salary:Math.round((c.comp==='top14'?9000:c.comp==='prod2'?4700:2500)*(0.7+ca/90)*(.78+rng(seed+'sal',0,35)/100)/100)*100,contract:2027+rng(seed+'ct',0,3),value:Math.round(ca*ca*(age<24?1.3:age>30?.78:1)*330/1000)*1000,fitness:rng(seed+'fit',89,100),morale:rng(seed+'mor',68,95),form:(rng(seed+'form',55,88)/10),attrs:{vitesse:rng(seed+'a1',8,18),puissance:rng(seed+'a2',8,19),endurance:rng(seed+'a3',9,18),plaquage:rng(seed+'a4',8,19),passe:rng(seed+'a5',7,18),jeuPied:rng(seed+'a6',5,18),ruck:rng(seed+'a7',7,19),touche:rng(seed+'a8',5,19),melee:rng(seed+'a9',5,19),vision:rng(seed+'a10',7,18),decision:rng(seed+'a11',7,18),leadership:rng(seed+'a12',6,18),finition:rng(seed+'a13',6,19),reception:rng(seed+'a14',7,19)}}}
function expandClub(c){
 if(c.players.length>=44){c.players.forEach((p,i)=>normalizeBody(p,c,i));return}
 let fr=c.players.filter(p=>p.nat==='France').length,needFR=Math.max(0,27-fr);
 adds.forEach((pos,k)=>{let nat=k<needFR?'France':foreignNats[hsh(c.name+'nat'+k)%foreignNats.length];c.players.push(filler(c,c.players.length,pos,nat))});
 // If the seed was unusually foreign-heavy, convert the last generated slots until the club reaches 27 French.
 for(let i=c.players.length-1;c.players.filter(p=>p.nat==='France').length<27&&i>=0;i--)if(c.players[i].nat!=='France')c.players[i].nat='France';
 c.players.forEach((p,i)=>normalizeBody(p,c,i));
}
RL_DATA.clubs.forEach(expandClub);RL_DATA.version=V;
const oldContinue=continueCareer;continueCareer=function(){oldContinue();if(state.save?.clubs){state.save.clubs.forEach(expandClub);saveLocal();render()}};
const oldStartDraft=startDraftSetup;startDraftSetup=function(){oldStartDraft();if(state.draft){state.draft.rounds=44;state.draft.pool=DB.clubs.flatMap(c=>c.players.map(p=>({...clone(p),origin:c.name})));render()}};
const oldFinish=finishDraft;finishDraft=function(){let d=state.draft;if(!d)return oldFinish();d.rounds=Math.max(d.rounds,44);oldFinish();if(state.save?.clubs){state.save.clubs.forEach(expandClub);saveLocal();render()}};

header=function(back=false){return `<div class="topbar"><div class="brand">${back?`<button class="btn ghost backbtn" onclick="goHome()">←</button>`:''}<img class="brand-logo" src="icons/mark.svg" alt=""><div class="brand-copy"><strong>Rugby Legacy</strong><small>Club Manager 2026-27</small></div></div><div class="pill version">v${DB.version}</div></div>`};
renderLanding=function(){let existing=loadLocal();return `${header()}<main class="page"><section class="hero legacy-hero"><img class="hero-logo" src="icons/brand-logo.svg" alt="Rugby Legacy"><div class="kicker">Construis. Dirige. Fais vivre la légende.</div><h1>RUGBY<br>LEGACY</h1><p>Manager de rugby français : effectifs professionnels profonds, tactique, recrutement, finances, infrastructures et matchs jouables en résultat instantané, 2D animée ou vue 3D immersive.</p><div class="actions"><button class="btn" onclick="newCareer()">Nouvelle carrière</button>${existing?`<button class="btn secondary" onclick="continueCareer()">Continuer</button>`:''}<button class="btn ghost" onclick="state.screen='create';render()">Créer mon club</button><button class="btn ghost" onclick="startDraftSetup()">Fantasy Draft</button></div></section><div class="section-title"><h2>Univers 2026-2027</h2><p>${DB.clubs.length} clubs • ${DB.clubs.reduce((s,c)=>s+c.players.length,0)} joueurs</p></div><div class="grid three">${Object.values(DB.comps).map(c=>`<div class="card comp-card"><span class="badge">${c.clubs} clubs</span><h3>${c.name}</h3><div class="meta">${c.rounds} journées • niveau ${c.level}${c.salaryCap?` • salary cap ${fmt(c.salaryCap)}`:''}</div></div>`).join('')}</div><div class="section-title"><h2>Le match, à ta façon</h2></div><div class="grid three"><div class="card"><div class="num">01</div><h3>Instantané</h3><div class="meta">Résultat, événements et statistiques en une seconde.</div></div><div class="card"><div class="num">02</div><h3>2D tactique</h3><div class="meta">30 joueurs animés, regroupements, conquête, ballon et occupation.</div></div><div class="card"><div class="num">03</div><h3>3D immersive</h3><div class="meta">Caméra inclinée, tribunes, profondeur et console de coaching inspirée des managers rugby PC.</div></div></div></main>`};
squadView=function(){let c=userClub(),q=state.filter.toLowerCase(),players=c.players.filter(p=>(state.position==='ALL'||p.pos===state.position)&&(`${p.first} ${p.last}`.toLowerCase().includes(q))),groups=['PIL','TAL','2L','3L','9','10','C','AIL','AR'];return `<div class="section-title"><h2>Effectif professionnel</h2><p>${c.players.length} joueurs • ${c.players.filter(p=>p.nat==='France').length} Français • ${c.players.filter(p=>p.nat!=='France').length} étrangers</p></div><div class="position-strip">${groups.map(g=>`<button class="pos-summary ${state.position===g?'active':''}" onclick="state.position='${state.position===g?'ALL':g}';render()"><b>${c.players.filter(p=>p.pos===g).length}</b><span>${g}</span></button>`).join('')}</div><div class="toolbar"><input placeholder="Rechercher un joueur..." value="${esc(state.filter)}" oninput="state.filter=this.value;render()"><select onchange="state.position=this.value;render()">${['ALL','PIL','TAL','2L','3L','9','10','C','AIL','AR','UTIL'].map(p=>`<option ${state.position===p?'selected':''}>${p}</option>`).join('')}</select></div><div class="table-wrap squad-table"><table><thead><tr><th>Joueur</th><th>Poste</th><th>Âge</th><th>Nat.</th><th>Taille</th><th>Poids</th><th>Niv.</th><th>Pot.</th><th>Salaire</th><th>Contrat</th></tr></thead><tbody>${players.sort((a,b)=>b.ca-a.ca).map(p=>`<tr onclick="playerModal('${p.id}')"><td><span class="player-name">${p.first} ${p.last}</span></td><td><span class="pos">${p.pos}</span></td><td>${p.age}</td><td><span class="flag-dot ${p.nat==='France'?'fr':'foreign'}"></span>${p.nat}</td><td>${p.height} cm</td><td>${p.weight} kg</td><td><span class="rating ${p.ca>82?'hi':p.ca>72?'mid':''}">${p.ca}</span></td><td>${p.potential}</td><td>${fmt(p.salary)}/m</td><td>${p.contract}</td></tr>`).join('')}</tbody></table></div>`};

if(!('matchSpeed' in state))state.matchSpeed=1;
function sidePanel(c,home){let starters=[...c.players].sort((x,y)=>y.ca-x.ca).slice(0,15);return `<div class="panel-title"><span>${home?'DOMICILE':'EXTÉRIEUR'}</span><b>${c.short}</b></div>${starters.map((p,i)=>`<div class="panel-player"><span class="jersey ${home?'home':'away'}">${i+1}</span><div><b>${p.last}</b><small>${p.pos}</small></div><i><em style="width:${p.fitness}%"></em></i></div>`).join('')}`}

matchDots=function(){let m=state.match,e=m.events[Math.max(0,m.index-1)]||{x:50,y:50,type:'COUP D’ENVOI',home:true},phase=m.index;const form=(home,i)=>{let row=i<8?0:i<13?1:2,col=i<8?i:i<13?i-8:i-13,x=home?(22+row*13):(78-row*13),y=row===0?10+col*11.2:row===1?18+col*16:31+col*38;if(e.type==='MÊLÉE'&&i<8){x=(home?47:53)+(i%4)*(home?-.8:.8);y=35+Math.floor(i/4)*7+(i%4)*2}if(e.type==='TOUCHE'&&i<7){x=(home?47:53)+(i%2)*(home?-1:1);y=20+i*8}if(e.type==='ESSAI'&&e.home===home){x=home?Math.min(91,55+i*2.1):Math.max(9,45-i*2.1);y=12+(i*5.2)%76}let j=((phase+i*7)%5-2)*.55;return[x+j,y+(((phase*3+i)%5)-2)*.35]};let out='<div class="pitch-lines"><i class="l22 a"></i><i class="l22 b"></i><i class="l10 a"></i><i class="l10 b"></i><i class="half"></i><i class="goal g1"></i><i class="goal g2"></i></div>';for(let i=0;i<15;i++){let[x,y]=form(true,i),[ax,ay]=form(false,i);out+=`<span class="player-token home" style="left:${x}%;top:${y}%"><i></i><b>${i+1}</b></span><span class="player-token away" style="left:${ax}%;top:${ay}%"><i></i><b>${i+1}</b></span>`}out+=`<span class="rugby-ball ${e.type==='ESSAI'?'flight':''}" style="left:${e.x}%;top:${e.y}%"></span>`;if(['MÊLÉE','TURNOVER'].includes(e.type))out+=`<span class="contact-cloud" style="left:${e.x}%;top:${e.y}%"></span>`;return out};

matchView=function(){let m=state.match,h=club(m.homeId),a=club(m.awayId),evt=m.events[Math.max(0,m.index-1)]||null,hp=Math.max(38,Math.min(62,Math.round(50+(teamRating(h)-teamRating(a))/4))),ap=100-hp;return `<div class="match-console"><div class="match-topscore"><div class="score-team"><span class="mini-crest home">${h.short}</span><div><strong>${h.name}</strong><small>${h.city}</small></div></div><div class="score-center"><span>${m.minute}'</span><b>${m.hs} - ${m.as}</b><em>${m.finished?'TERMINÉ':'EN DIRECT'}</em></div><div class="score-team away"><div><strong>${a.name}</strong><small>${a.city}</small></div><span class="mini-crest away">${a.short}</span></div></div><div class="match-tabs"><button class="${state.view==='2d'?'active':''}" onclick="state.view='2d';render()">Vue 2D</button><button class="${state.view==='3d'?'active':''}" onclick="state.view='3d';render()">Vue 3D</button><button onclick="instantResult()">Résultat instantané</button></div><div class="match-layout"><aside class="coach-panel">${sidePanel(h,true)}</aside><section class="stadium-shell ${state.view==='3d'?'mode3d':'mode2d'}"><div class="stand stand-top"></div><div class="stand stand-left"></div><div class="stand stand-right"></div><div id="pitch" class="match-pitch ${state.view==='3d'?'perspective':''}">${matchDots()}</div><div class="phase-banner">${evt?`<b>${evt.type}</b><span>${evt.text}</span>`:'<b>COUP D’ENVOI</b><span>Les équipes se mettent en place.</span>'}</div></section><aside class="coach-panel">${sidePanel(a,false)}</aside></div><div class="match-controls"><button class="ctrl primary" onclick="toggleLive()">${m.running?'Ⅱ':'▶'}</button><button class="ctrl" onclick="stepMatch()">▸|</button><div class="speed">${[1,2,4].map(s=>`<button class="${state.matchSpeed===s?'active':''}" onclick="state.matchSpeed=${s};restartLive()">x${s}</button>`).join('')}</div><div class="match-meter"><span>Possession ${hp}%</span><i><b style="width:${hp}%"></b></i><span>${ap}%</span></div><span class="pill clock">${m.minute}'</span></div><div class="grid two match-bottom"><div class="card"><h3>Statistiques live</h3><div class="stat-grid"><div><span>Essais</span><b>${m.hTries}</b><b>${m.aTries}</b></div><div><span>Possession</span><b>${hp}%</b><b>${ap}%</b></div><div><span>Joueurs disponibles</span><b>${h.players.filter(p=>p.fitness>75).length}</b><b>${a.players.filter(p=>p.fitness>75).length}</b></div></div></div><div class="card"><h3>Fil du match</h3><div class="timeline">${m.events.slice(0,m.index).reverse().slice(0,7).map(e=>`<div class="event"><time>${e.m}'</time><div><strong>${e.type}</strong><br>${e.text}</div></div>`).join('')||'<div class="meta">Le match n’a pas commencé.</div>'}</div></div></div>${m.finished?`<div class="card final-card"><h2>Terminé : ${h.short} ${m.hs} - ${m.as} ${a.short}</h2><button class="btn" onclick="commitMatch()">Continuer la saison</button></div>`:''}</div>`};
window.restartLive=function(){if(state.match?.running){clearInterval(liveTimer);liveTimer=setInterval(stepMatch,Math.max(130,700/state.matchSpeed))}render()};
toggleLive=function(){let m=state.match;if(m.finished)return;if(m.running){m.running=false;clearInterval(liveTimer);render();return}m.running=true;render();liveTimer=setInterval(()=>{if(!state.match||!state.match.running)return clearInterval(liveTimer);stepMatch()},Math.max(130,700/state.matchSpeed))};
afterRender=function(){if(state.match&&state.match.running){clearInterval(liveTimer);liveTimer=setInterval(stepMatch,Math.max(130,700/state.matchSpeed))}};
render();
})();