/* Rugby Legacy v0.7 — PRM2015-inspired pseudo-3D match presentation */
(()=>{
const V='0.7.0';
if(typeof RL_DATA!=='undefined') RL_DATA.version=V;
if(typeof DB!=='undefined') DB.version=V;
if(!('prmCamera' in state)) state.prmCamera='tv';
if(!('prmQuality' in state)) state.prmQuality='standard';
window.__rlPrmLoop && cancelAnimationFrame(window.__rlPrmLoop);

const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const lerp=(a,b,t)=>a+(b-a)*t;
const phaseKey=t=>(t||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
function teamColors(home){return home?{shirt:'#d8a936',shorts:'#141a17',socks:'#d8a936',accent:'#f5e5a5'}:{shirt:'#c6252d',shorts:'#f0f0eb',socks:'#c6252d',accent:'#ffffff'}}
function currentEvent(){const m=state.match;if(!m)return null;return m.events[Math.max(0,m.index-1)]||{x:50,y:50,type:"COUP D'ENVOI",home:true,m:0,text:'Coup d’envoi'}}
function prevEvent(){const m=state.match;if(!m)return null;return m.events[Math.max(0,m.index-2)]||{x:50,y:50,type:"COUP D'ENVOI",home:true,m:0,text:'Coup d’envoi'}}
function clubLine(c){if(state.save&&c.id===state.save.clubId&&Array.isArray(state.save.lineup))return state.save.lineup.map(id=>c.players.find(p=>p.id===id)).filter(Boolean).slice(0,15);const order=['PIL','TAL','PIL','2L','2L','3L','3L','3L','9','10','AIL','C','C','AIL','AR'],used=new Set(),out=[];for(const pos of order){let pool=c.players.filter(p=>!used.has(p.id)&&p.pos===pos).sort((a,b)=>(b.ca||0)-(a.ca||0));if(!pool.length)pool=c.players.filter(p=>!used.has(p.id)).sort((a,b)=>(b.ca||0)-(a.ca||0));if(pool[0]){used.add(pool[0].id);out.push(pool[0])}}return out}
function posProfile(p){const pos=p?.pos||'C',h=p?.height||185,w=p?.weight||95;const bulky=['PIL','TAL'].includes(pos)?1.18:['2L','3L'].includes(pos)?1.08:['9','AIL'].includes(pos)?.91:1;return{height:clamp(h/185,.90,1.14),width:clamp((w/95)*bulky,.82,1.30)}}
function baseFormation(home,i,e){const dir=home?1:-1,att=e?.home===home,bx=e?.x??50,by=e?.y??50,t=phaseKey(e?.type),pack=i<8;let x=50,y=50;if(t.includes('MELEE')){if(pack){const row=i<3?0:i<5?1:2,idx=i<3?i:i<5?i-3:i-5;x=bx-dir*(1.6+row*2);y=by+(idx-(row===1?.5:1))*3.8}else{x=bx-dir*(9+(i-8)*3.6);y=14+(i-8)*12.2}}else if(t.includes('TOUCHE')){const edge=by<50?10:90,side=by<50?1:-1;if(i<7){x=bx+((i%2)?2.2:-2.2);y=edge+side*(6+Math.floor(i/2)*4.8)}else{x=bx-dir*(8+(i-7)*3.2);y=15+(i-8)*11.5}}else if(t.includes('RUCK')||t.includes('PERCUSSION')||t.includes('TURNOVER')){if(i<5){x=bx-dir*(1.5+Math.floor(i/2)*2.1);y=by+(i-2)*2.3}else if(pack){x=bx-dir*(6+(i-4)*2.1);y=by+(i-5)*6.4}else{x=bx-dir*(8+(i-8)*3.8);y=8+(i-8)*14}}else if(t.includes('PIED')||t.includes('DROP')){if(i===9){x=bx-dir*5.5;y=by}else{x=att?bx-dir*(5+(i%6)*3.8):bx+dir*(7+(i%5)*3);y=7+(i*6.2)%86}}else if(t.includes('ESSAI')){x=att?bx-dir*(1.5+i*1.2):bx+dir*(4+i*.7);y=8+(i*6.1)%84}else{if(pack){x=att?bx-dir*(3+(i%4)*3):bx+dir*(5+(i%4)*2.5);y=13+(i%4)*23}else{x=att?bx-dir*(8+(i-8)*3.6):bx+dir*(8+(i-8)*2.7);y=8+(i-8)*14}}return[clamp(x,3,97),clamp(y,5,95)]}
function canvasInfo(){const canvas=document.getElementById('prm-canvas');if(!canvas)return null;const rect=canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,state.prmQuality==='high'?2:1.45),w=Math.max(300,Math.round(rect.width*dpr)),h=Math.max(220,Math.round(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{canvas,ctx,w:rect.width,h:rect.height,dpr}}
function project(px,py,w,h){const topY=h*.075,botY=h*.91,topL=w*.17,topR=w*.86,botL=w*.025,botR=w*.985;let y=py/100,x=px/100;const yy=lerp(topY,botY,y);let l=lerp(topL,botL,y),r=lerp(topR,botR,y);if(state.prmCamera==='high'){l=lerp(w*.10,w*.04,y);r=lerp(w*.90,w*.96,y)}if(state.prmCamera==='follow'){const e=currentEvent(),focus=((e?.x??50)-50)/100*w*.16;l-=focus;r-=focus}return{x:lerp(l,r,x),y:yy,scale:lerp(.58,1.30,y)}}
function poly(ctx,pts,fill,stroke=null,lw=1){ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}}
function line(ctx,a,b,stroke,lw=1,dash=[]){ctx.save();ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore()}
function drawStadium(ctx,w,h){ctx.clearRect(0,0,w,h);const sky=ctx.createLinearGradient(0,0,0,h*.22);sky.addColorStop(0,'#18201c');sky.addColorStop(1,'#0b0e0c');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);ctx.fillStyle='#262c29';ctx.fillRect(0,h*.015,w,h*.11);ctx.fillStyle='#111512';ctx.fillRect(0,h*.11,w,h*.04);for(let y=0;y<5;y++)for(let x=0;x<Math.ceil(w/9);x++){if((x+y)%3===0){ctx.fillStyle=['#b8b6a9','#8e9790','#cfb15c','#6d7870'][(x+y)%4];ctx.fillRect(x*9+(y%2)*3,8+y*5,2.2,2.2)}}ctx.fillStyle='#141816';ctx.fillRect(0,h*.145,w,h*.027);for(let x=0;x<w;x+=120){ctx.fillStyle=x%240?'#d7b85b':'#d8d8d2';ctx.font='bold 8px Arial';ctx.fillText(x%240?'RUGBY LEGACY':'SPORT PRO',x+8,h*.164)}const p1=project(0,0,w,h),p2=project(100,0,w,h),p3=project(100,100,w,h),p4=project(0,100,w,h),grass=ctx.createLinearGradient(0,p1.y,0,p4.y);grass.addColorStop(0,'#4d8739');grass.addColorStop(.55,'#4f913c');grass.addColorStop(1,'#3f7f32');poly(ctx,[p1,p2,p3,p4],grass,'rgba(255,255,255,.86)',1.4);for(let i=0;i<10;i+=2){const a=project(i*10,0,w,h),b=project((i+1)*10,0,w,h),c=project((i+1)*10,100,w,h),d=project(i*10,100,w,h);poly(ctx,[a,b,c,d],'rgba(255,255,255,.026)')}[0,22,40,50,60,78,100].forEach(v=>line(ctx,project(v,0,w,h),project(v,100,w,h),'rgba(255,255,255,.75)',v===50?1.5:1));[10,90].forEach(v=>line(ctx,project(0,v,w,h),project(100,v,w,h),'rgba(255,255,255,.36)',.8,[5,6]));[5,15,85,95].forEach(v=>line(ctx,project(0,v,w,h),project(100,v,w,h),'rgba(255,255,255,.27)',.75,[3,8]));drawPosts(ctx,3,50,w,h);drawPosts(ctx,97,50,w,h)}
function drawPosts(ctx,x,y,w,h){const p=project(x,y,w,h),sc=p.scale;ctx.save();ctx.strokeStyle='#ecebd8';ctx.lineWidth=Math.max(1,1.4*sc);ctx.beginPath();ctx.moveTo(p.x-6*sc,p.y);ctx.lineTo(p.x-6*sc,p.y-36*sc);ctx.moveTo(p.x+6*sc,p.y);ctx.lineTo(p.x+6*sc,p.y-36*sc);ctx.moveTo(p.x-6*sc,p.y-23*sc);ctx.lineTo(p.x+6*sc,p.y-23*sc);ctx.stroke();ctx.restore()}
function playerPose(type,attacking,i){const t=phaseKey(type);if(t.includes('MELEE'))return'scrum';if(t.includes('TOUCHE'))return i===3||i===4?'jump':'lineout';if(t.includes('RUCK')||t.includes('TURNOVER'))return i<5?'ruck':'ready';if(t.includes('PERCUSSION'))return i%4===0?'tackle':'run';if(t.includes('ESSAI'))return attacking&&i%5===0?'dive':'run';if(t.includes('PIED')||t.includes('DROP'))return i===9?'kick':'chase';return'run'}
function drawPlayer(ctx,p,n,home,pt,type,attacking,i,time){const c=teamColors(home),prof=posProfile(p),sc=pt.scale*prof.height,bulk=prof.width,pose=playerPose(type,attacking,i),bob=(pose==='run'||pose==='chase')?Math.sin(time*.012+i)*1.6*sc:0,lean=pose==='scrum'?.55:pose==='ruck'?.42:pose==='tackle'?.48:pose==='dive'?.70:pose==='kick'?.18:.12,x=pt.x,y=pt.y+bob;ctx.save();ctx.fillStyle='rgba(0,0,0,.34)';ctx.beginPath();ctx.ellipse(x+2*sc,y+5*sc,5.8*bulk*sc,2.2*sc,0,0,Math.PI*2);ctx.fill();ctx.translate(x,y);ctx.rotate((home?1:-1)*lean);ctx.strokeStyle='#202421';ctx.lineWidth=2.2*sc;ctx.lineCap='round';const stride=(pose==='run'||pose==='chase')?Math.sin(time*.016+i)*4:pose==='kick'?5:0;ctx.beginPath();ctx.moveTo(-2*bulk*sc,0);ctx.lineTo((-2-stride)*bulk*sc,8*sc);ctx.moveTo(2*bulk*sc,0);ctx.lineTo((2+stride)*bulk*sc,8*sc);ctx.stroke();ctx.fillStyle=c.shirt;ctx.strokeStyle='rgba(0,0,0,.35)';ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(-4.2*bulk*sc,-13*sc);ctx.lineTo(4.2*bulk*sc,-13*sc);ctx.lineTo(5.2*bulk*sc,-2*sc);ctx.lineTo(-5.2*bulk*sc,-2*sc);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle=c.shorts;ctx.fillRect(-4.7*bulk*sc,-2*sc,9.4*bulk*sc,4.2*sc);ctx.fillStyle='#c9956d';ctx.beginPath();ctx.arc(0,-17.2*sc,3.1*sc,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#c9956d';ctx.lineWidth=2.1*sc;const armSwing=(pose==='run'||pose==='chase')?Math.sin(time*.016+i+1.4)*4:pose==='scrum'||pose==='ruck'?5:pose==='tackle'?7:pose==='kick'?4:2;ctx.beginPath();ctx.moveTo(-4*bulk*sc,-11*sc);ctx.lineTo((-6-armSwing)*bulk*sc,-5*sc);ctx.moveTo(4*bulk*sc,-11*sc);ctx.lineTo((6+armSwing)*bulk*sc,-5*sc);ctx.stroke();if(sc>.62){ctx.fillStyle=c.accent;ctx.font=`bold ${Math.max(5,6.5*sc)}px Arial`;ctx.textAlign='center';ctx.fillText(n,0,-6*sc)}ctx.restore()}
function drawBall(ctx,e,prev,w,h,time){if(!e)return;const t=phaseKey(e.type),p=project(e.x??50,e.y??50,w,h),pr=project(prev?.x??50,prev?.y??50,w,h);let u=.65+.35*Math.sin(time*.004),x=lerp(pr.x,p.x,u),y=lerp(pr.y,p.y,u);if(t.includes('PIED')||t.includes('DROP'))y-=Math.sin(Math.PI*u)*55;if(t.includes('PASSE'))y-=Math.sin(Math.PI*u)*14;ctx.save();ctx.translate(x,y);ctx.rotate(time*.01);ctx.fillStyle='#e8dfc6';ctx.strokeStyle='#3a2b1c';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(0,0,5*p.scale,2.6*p.scale,.2,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}
function drawPhaseFx(ctx,e,w,h,time){if(!e)return;const t=phaseKey(e.type),p=project(e.x??50,e.y??50,w,h);if(t.includes('RUCK')||t.includes('TURNOVER')||t.includes('PERCUSSION')){ctx.save();ctx.globalAlpha=.18+.08*Math.sin(time*.01);ctx.fillStyle='#d8ccb0';ctx.beginPath();ctx.ellipse(p.x,p.y,24*p.scale,9*p.scale,0,0,Math.PI*2);ctx.fill();ctx.restore()}if(t.includes('ESSAI')){ctx.save();ctx.font='900 34px Arial';ctx.textAlign='center';ctx.fillStyle='rgba(245,224,160,.92)';ctx.shadowColor='rgba(0,0,0,.7)';ctx.shadowBlur=10;ctx.fillText('ESSAI',w/2,h*.26);ctx.restore()}}
function drawFrame(ts){const inf=canvasInfo();if(!inf){window.__rlPrmLoop=requestAnimationFrame(drawFrame);return}const{ctx,w,h}=inf,m=state.match,e=currentEvent(),pr=prevEvent();drawStadium(ctx,w,h);if(m){const hc=club(m.homeId),ac=club(m.awayId),hl=clubLine(hc),al=clubLine(ac);let actors=[];for(let i=0;i<15;i++){const hp=baseFormation(true,i,e),ap=baseFormation(false,i,e),hpp=baseFormation(true,i,pr),app=baseFormation(false,i,pr),cyc=(ts%900)/900,smooth=cyc*cyc*(3-2*cyc),hxy=[lerp(hpp[0],hp[0],smooth),lerp(hpp[1],hp[1],smooth)],axy=[lerp(app[0],ap[0],smooth),lerp(app[1],ap[1],smooth)];actors.push({p:hl[i],n:i+1,home:true,pt:project(hxy[0],hxy[1],w,h),att:e?.home===true,i});actors.push({p:al[i],n:i+1,home:false,pt:project(axy[0],axy[1],w,h),att:e?.home===false,i})}actors.sort((a,b)=>a.pt.y-b.pt.y);actors.forEach(a=>drawPlayer(ctx,a.p,a.n,a.home,a.pt,e?.type,a.att,a.i,ts));drawBall(ctx,e,pr,w,h,ts);drawPhaseFx(ctx,e,w,h,ts)}window.__rlPrmLoop=requestAnimationFrame(drawFrame)}
window.startPrmRenderer=function(){cancelAnimationFrame(window.__rlPrmLoop);window.__rlPrmLoop=requestAnimationFrame(drawFrame)};window.setPrmCamera=function(v){state.prmCamera=v;render();setTimeout(window.startPrmRenderer,10)};window.setPrmTactic=function(k,v){if(window.liveTacticChange)window.liveTacticChange(k,v);setTimeout(window.startPrmRenderer,10)};window.prmSub=function(){if(window.toggleBenchV6)window.toggleBenchV6()};
function rosterSide(c,home){const xv=clubLine(c);return `<aside class="prm-roster ${home?'home':'away'}"><div class="prm-rhead"><span>${home?'DOM':'EXT'}</span><b>${c.short}</b></div>${xv.map((p,i)=>`<div class="prm-rplayer"><i>${i+1}</i><span><b>${p?.last||'—'}</b><small>${p?.pos||''}</small></span><em>${Math.max(50,Math.round((p?.fitness||92)-(state.match?.minute||0)*(i<8?.18:.12)))}</em></div>`).join('')}</aside>`}
function phaseButtons(){const t=state.save?.tactics||{};return `<div class="prm-phasebuttons"><button onclick="prmSub()">↔ <b>Remplacement</b></button><button class="${t.attack==='Jeu direct'?'active':''}" onclick="setPrmTactic('attack','Jeu direct')">Avants</button><button class="${t.attack==='Équilibré'?'active':''}" onclick="setPrmTactic('attack','Équilibré')">Centres</button><button class="${t.attack==='Jeu au large'?'active':''}" onclick="setPrmTactic('attack','Jeu au large')">Ailes</button><button class="${t.attack==='Occupation'?'active':''}" onclick="setPrmTactic('attack','Occupation')">Équilibre</button></div>`}
function sliderControl(label,key,left,right){const t=state.save?.tactics||{},val=key==='defense'?(t.defense==='Glissée'?35:t.defense==='Montée agressive'?65:t.defense==='Blitz'?88:50):(t.kick==='Relance'?18:t.kick==='Alternance'?50:t.kick==='Occupation'?80:66);return `<div class="prm-slider"><div><span>${label}</span><small>${left}</small><small>${right}</small></div><input type="range" min="0" max="100" value="${val}" onchange="${key==='defense'?`setPrmTactic('defense',this.value<45?'Glissée':this.value<75?'Montée agressive':'Blitz')`:`setPrmTactic('kick',this.value<35?'Relance':this.value<65?'Alternance':'Occupation')`}"></div>`}
const oldMatchView=matchView;matchView=function(){const m=state.match;if(!m)return oldMatchView();const h=club(m.homeId),a=club(m.awayId),e=currentEvent(),s=m.stats||{},hp=Math.round(s.possH||50);const html=`<div class="prm-match ${state.view==='3d'?'is3d':'is2d'}"><div class="prm-stagebar"><button onclick="state.view='2d';render()">2D</button><button class="${state.view==='3d'?'active':''}" onclick="state.view='3d';render();setTimeout(startPrmRenderer,10)">3D</button><span>RUGBY LEGACY · MOTEUR PRM</span><button onclick="instantResult()">Résultat instantané</button></div><div class="prm-scorebox"><div><b>${m.hs}</b><i></i><b>${m.as}</b></div><strong>${String(m.minute).padStart(2,'0')}:00</strong><small>${m.minute<40?'1MT':'2MT'}</small></div><div class="prm-world">${rosterSide(h,true)}<section class="prm-video">${state.view==='3d'?`<canvas id="prm-canvas"></canvas>`:`<div class="prm-2d-wrap"><div class="prm-2d-title">VUE TACTIQUE 2D</div><div class="prm-2d-pitch">${typeof matchDots==='function'?matchDots():''}</div></div>`}<div class="prm-event"><b>${e?.type||"COUP D'ENVOI"}</b><span>${e?.text||'Les équipes se mettent en place.'}</span></div><div class="prm-cameras">${['tv','sideline','high','follow'].map(c=>`<button class="${state.prmCamera===c?'active':''}" onclick="setPrmCamera('${c}')">${c==='tv'?'TV':c==='sideline'?'Latérale':c==='high'?'Haute':'Suivi'}</button>`).join('')}</div></section>${rosterSide(a,false)}</div><div class="prm-controlbar"><div class="prm-transport"><button onclick="toggleLive()">${m.running?'Ⅱ':'▶'}</button><button onclick="stepMatch()">▸|</button>${[1,2,4].map(v=>`<button class="${state.matchSpeed===v?'active':''}" onclick="state.matchSpeed=${v};restartLive()">x${v}</button>`).join('')}</div>${phaseButtons()}<div class="prm-sliders">${sliderControl('Défense','defense','Attendre','Monter')}${sliderControl('Jeu au pied','kick','Relancer','Occuper')}</div></div>${typeof benchBox==='function'?benchBox(h):''}<div class="prm-details"><div><b>Possession</b><span>${hp}% / ${100-hp}%</span></div><div><b>Territoire</b><span>${Math.round(s.territoryH||50)}% / ${100-Math.round(s.territoryH||50)}%</span></div><div><b>Mêlées</b><span>${s.scrumH||0} / ${s.scrumA||0}</span></div><div><b>Touches</b><span>${s.lineH||0} / ${s.lineA||0}</span></div><div><b>Rucks</b><span>${s.ruckH||0} / ${s.ruckA||0}</span></div></div>${m.finished?`<div class="prm-finish"><h2>${h.short} ${m.hs} - ${m.as} ${a.short}</h2><button class="btn" onclick="commitMatch()">Continuer la saison</button></div>`:''}</div>`;setTimeout(()=>{if(state.view==='3d')startPrmRenderer()},20);return html};const baseRender=render;render=function(){cancelAnimationFrame(window.__rlPrmLoop);const r=baseRender();if(state.match&&state.view==='3d')setTimeout(window.startPrmRenderer,30);return r};if(state.match&&state.view==='3d')setTimeout(window.startPrmRenderer,30);
})();
