/* Rugby Legacy v0.9 — continuous PRM-style action choreography */
(()=>{
const V='0.9.0';
if(typeof RL_DATA!=='undefined') RL_DATA.version=V;
if(typeof DB!=='undefined') DB.version=V;
state.prm9Camera=state.prm9Camera||'tv';
state.prm9Speed=state.prm9Speed||1;
let raf=0,lastIdx=-1,phaseStart=performance.now(),camX=50,camY=50;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const lerp=(a,b,t)=>a+(b-a)*t;
const sm=t=>t*t*(3-2*t);
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
const POS=['PIL','TAL','PIL','2L','2L','3L','3L','3L','9','10','AIL','C','C','AIL','AR'];
function evt(off=1){const m=state.match;if(!m)return null;return m.events[Math.max(0,m.index-off)]||{x:50,y:50,type:"COUP D'ENVOI",home:true,text:'Coup d’envoi',m:0}}
function fifteen(c){if(state.save&&c.id===state.save.clubId&&state.save.lineup?.length===15)return state.save.lineup.map(id=>c.players.find(p=>p.id===id)).filter(Boolean);let used=new Set(),out=[];for(const pos of POS){let p=c.players.filter(x=>!used.has(x.id)&&x.pos===pos).sort((a,b)=>(b.ca||0)-(a.ca||0))[0]||c.players.filter(x=>!used.has(x.id)).sort((a,b)=>(b.ca||0)-(a.ca||0))[0];if(p){used.add(p.id);out.push(p)}}return out}
function profile(p){let pos=p?.pos||'C',h=clamp((p?.height||185)/185,.88,1.16),w=clamp((p?.weight||95)/95,.80,1.24);if(['PIL','TAL'].includes(pos))w*=1.12;if(pos==='9'||pos==='AIL')w*=.94;return{h,w}}
function duration(type){type=norm(type);if(type.includes('MELEE'))return 4200;if(type.includes('TOUCHE'))return 3600;if(type.includes('RUCK')||type.includes('TURNOVER'))return 3300;if(type.includes('PERCUSSION'))return 3000;if(type.includes('PIED')||type.includes('DROP'))return 2800;if(type.includes('ESSAI'))return 3200;return 2600}
function actionProgress(e){return clamp((performance.now()-phaseStart)/(duration(e?.type)/state.prm9Speed),0,1)}
function carrierIndex(e){let t=norm(e?.type);if(t.includes('MELEE')||t.includes('RUCK'))return 8;if(t.includes('PIED')||t.includes('DROP'))return 9;if(t.includes('TOUCHE'))return 3;if(t.includes('PERCUSSION'))return 11;if(t.includes('ESSAI'))return 13;return 12}
function baseShape(home,i,e){let bx=e?.x??50,by=e?.y??50,t=norm(e?.type),att=e?.home===home,dir=home?1:-1,pack=i<8,x=50,y=50;
 if(t.includes('MELEE')){if(pack){const rows=[[0,1,2],[3,4,5,6],[7]],row=rows.findIndex(r=>r.includes(i)),idx=rows[row].indexOf(i),cnt=rows[row].length;x=bx-dir*(1.4+row*2.1);y=by+(idx-(cnt-1)/2)*3.5}else if(i===8){x=bx-dir*6.2;y=by+3}else{x=bx-dir*(10+(i-9)*4);y=12+(i-9)*15}}
 else if(t.includes('TOUCHE')){let edge=by<50?10:90,sg=by<50?1:-1;if(pack){x=bx+(i%2?.85:-.85);y=edge+sg*(5.5+i*4.35)}else if(i===8){x=bx-dir*5;y=edge+sg*17}else{x=bx-dir*(9+(i-9)*3.7);y=15+(i-9)*13.5}}
 else if(t.includes('RUCK')||t.includes('TURNOVER')||t.includes('PERCUSSION')){if(i<4){x=bx-dir*(1.2+Math.floor(i/2)*1.8);y=by+(i%2?2.1:-2.1)}else if(pack){x=bx-dir*(5+(i-3)*2.2);y=by+(i-5.5)*6.5}else if(i===8){x=bx-dir*5.2;y=by+2.8}else{x=bx-dir*(8.5+(i-9)*4.1);y=8+(i-9)*15.5}}
 else if(t.includes('PIED')||t.includes('DROP')){if(i===9){x=bx-dir*3.8;y=by}else if(i===8){x=bx-dir*7;y=by+3}else{x=(att?bx-dir*(7+(i%5)*4):bx+dir*(11+(i%5)*3));y=7+(i*6.2)%86}}
 else if(t.includes('ESSAI')){x=att?bx-dir*(1+i*1.0):bx+dir*(4+i*.7);y=8+(i*6.1)%84}
 else{if(pack){let pod=i<3?0:i<6?1:2,slot=i<3?i:i<6?i-3:i-6;x=att?bx-dir*(4+pod*5):bx+dir*(6+pod*4);y=by+(slot-1)*7+pod*5}else if(i===8){x=bx-dir*5;y=by+2}else{x=att?bx-dir*(9+(i-9)*4.4):bx+dir*(9+(i-9)*3.8);y=10+(i-9)*15}}
 return[clamp(x,3,97),clamp(y,4,96)]}
function subShape(home,i,e,p){let [x,y]=baseShape(home,i,e),t=norm(e?.type),att=e?.home===home,dir=home?1:-1,ci=carrierIndex(e),bx=e?.x??50,by=e?.y??50;
 // Create continuity inside the event instead of one static formation.
 if(t.includes('PASSE')){if(att){if(i===ci){x=bx-dir*(7*(1-p));y=by-4*(1-p)}else if(i>8){x+=dir*(p*2.5);y+=(i%2?1:-1)*p*2}}else{x+=dir*(p*1.5)}}
 if(t.includes('PERCUSSION')){if(att&&i===ci){x=bx-dir*(6*(1-p));y=by}else if(!att&&i===11){x=bx+dir*(5*(1-p));y=by+1.2}if(p>.58&&p<.88&&((att&&i===ci)||(!att&&i===11))){x=bx+(att?-dir:dir)*(1-p)*2;y=by}}
 if(t.includes('RUCK')||t.includes('TURNOVER')){let arrive=clamp((p-.22)/.55,0,1);if(i<5||i===8){let [tx,ty]=baseShape(home,i,e);let spread=[tx-dir*(5+i*.3),ty+(i-2)*2.2];x=lerp(spread[0],tx,sm(arrive));y=lerp(spread[1],ty,sm(arrive))}if(i===8&&att&&p>.72){x=bx-dir*(6-(p-.72)*9);y=by+2.8}}
 if(t.includes('MELEE')){let push=(p>.42&&p<.78)?Math.sin((p-.42)/.36*Math.PI)*1.4:0;x+=att?dir*push:-dir*push}
 if(t.includes('TOUCHE')&&(i===3||i===4)){let jump=Math.sin(clamp((p-.25)/.45,0,1)*Math.PI);y+=(by<50?1:-1)*jump*1.3;x+=jump*.25}
 if((t.includes('PIED')||t.includes('DROP'))&&att&&i===9){x=bx-dir*(4-2.4*p)}
 if(t.includes('ESSAI')&&att&&i===ci){x=bx-dir*(5*(1-p));if(p>.72)y+=Math.sin((p-.72)/.28*Math.PI)*1.2}
 return[clamp(x,2,98),clamp(y,3,97)]}
function info(){let c=document.getElementById('prm9-canvas');if(!c)return null;let r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,1.8),w=Math.max(320,r.width),h=Math.max(220,r.height);if(c.width!==Math.round(w*d)||c.height!==Math.round(h*d)){c.width=Math.round(w*d);c.height=Math.round(h*d)}let ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);return{c,ctx,w,h}}
function proj(px,py,w,h){let e=evt(),targetX=e?.x??50,targetY=e?.y??50;if(state.prm9Camera==='follow'){camX=lerp(camX,targetX,.035);camY=lerp(camY,targetY,.025)}else{camX=lerp(camX,50,.05);camY=lerp(camY,50,.05)}let focus=state.prm9Camera==='follow'?(camX-50)*.19:0,x=clamp(px-focus,-5,105)/100,y=py/100;let topY=h*.19,botY=h*.92,tl=w*.13,tr=w*.87,bl=w*.01,br=w*.99;if(state.prm9Camera==='high'){topY=h*.11;tl=w*.07;tr=w*.93}if(state.prm9Camera==='sideline'){topY=h*.24;tl=w*.20;tr=w*.80}let yy=lerp(topY,botY,y),l=lerp(tl,bl,y),r=lerp(tr,br,y);return{x:lerp(l,r,x),y:yy,s:lerp(.48,1.30,y)}}
function line(ctx,a,b,c,lw=1,d=[]){ctx.save();ctx.strokeStyle=c;ctx.lineWidth=lw;ctx.setLineDash(d);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore()}
function poly(ctx,p,fill,stroke=null,lw=1){ctx.beginPath();p.forEach((q,i)=>i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}}
function stadium(ctx,w,h){ctx.clearRect(0,0,w,h);let sky=ctx.createLinearGradient(0,0,0,h*.25);sky.addColorStop(0,'#111713');sky.addColorStop(1,'#343936');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h*.25);ctx.fillStyle='#262c28';ctx.fillRect(0,h*.018,w,h*.12);ctx.fillStyle='#0c0f0d';ctx.fillRect(0,h*.137,w,h*.045);for(let y=0;y<10;y++)for(let x=0;x<w;x+=7){if(((x/7+y)|0)%4!==0){ctx.fillStyle=['#b9b7ad','#717a74','#c3a654','#d8d7ce'][((x/7+y)|0)%4];ctx.fillRect(x+(y%2)*2,8+y*4,2,2)}}ctx.fillStyle='#101311';ctx.fillRect(0,h*.177,w,h*.025);for(let x=0;x<w;x+=120){ctx.fillStyle=x%240?'#d6b860':'#ddd';ctx.font='700 8px Arial';ctx.fillText(x%240?'RUGBY LEGACY':'SPORT PRO',x+7,h*.194)}let a=proj(0,0,w,h),b=proj(100,0,w,h),c=proj(100,100,w,h),d=proj(0,100,w,h),g=ctx.createLinearGradient(0,a.y,0,d.y);g.addColorStop(0,'#4d843c');g.addColorStop(.5,'#529244');g.addColorStop(1,'#37712f');poly(ctx,[a,b,c,d],g,'rgba(255,255,255,.82)',1.2);for(let i=0;i<10;i+=2)poly(ctx,[proj(i*10,0,w,h),proj((i+1)*10,0,w,h),proj((i+1)*10,100,w,h),proj(i*10,100,w,h)],'rgba(255,255,255,.022)');[0,22,40,50,60,78,100].forEach(v=>line(ctx,proj(v,0,w,h),proj(v,100,w,h),'rgba(255,255,255,.72)',v===50?1.4:.8));[10,90].forEach(v=>line(ctx,proj(0,v,w,h),proj(100,v,w,h),'rgba(255,255,255,.30)',.7,[4,6]));posts(ctx,3,50,w,h);posts(ctx,97,50,w,h)}
function posts(ctx,x,y,w,h){let p=proj(x,y,w,h),s=p.s;ctx.strokeStyle='#f4f1e6';ctx.lineWidth=Math.max(1,1.25*s);ctx.beginPath();ctx.moveTo(p.x-5*s,p.y);ctx.lineTo(p.x-5*s,p.y-34*s);ctx.moveTo(p.x+5*s,p.y);ctx.lineTo(p.x+5*s,p.y-34*s);ctx.moveTo(p.x-5*s,p.y-22*s);ctx.lineTo(p.x+5*s,p.y-22*s);ctx.stroke()}
function pose(type,att,i,p){let t=norm(type),ci=carrierIndex({type});if(t.includes('MELEE'))return i<8?'scrum':'ready';if(t.includes('TOUCHE'))return (i===3||i===4)&&p>.2&&p<.8?'jump':'ready';if(t.includes('RUCK')||t.includes('TURNOVER'))return i<4?(p<.45?'arrive':'ruck'):'ready';if(t.includes('PERCUSSION')){if(att&&i===ci)return p>.68?'fall':'carry';if(!att&&i===11)return p>.55?'tackle':'run';return'run'}if(t.includes('ESSAI'))return att&&i===ci&&p>.72?'dive':'run';if(t.includes('PIED')||t.includes('DROP'))return att&&i===9?'kick':'chase';return'run'}
function kit(home){return home?{j:'#d2a333',j2:'#a9791b',s:'#17201b',num:'#fff0b6'}:{j:'#bd2830',j2:'#821a22',s:'#ededeb',num:'#fff'}}
function drawPlayer(ctx,p,n,home,pt,type,att,i,ts,progress){let c=kit(home),pr=profile(p),sc=pt.s*pr.h,b=pr.w,po=pose(type,att,i,progress),run=['run','chase','carry','arrive'].includes(po),cycle=ts*.017+i*1.7,stride=run?Math.sin(cycle)*4.2:po==='kick'?6:0,bob=run?Math.abs(Math.sin(cycle))*1.2:0,lean=po==='scrum'?.75:po==='ruck'?.72:po==='tackle'?.82:po==='fall'?1.25:po==='dive'?1.35:po==='kick'?.20:po==='carry'?.16:.08,x=pt.x,y=pt.y+bob*sc;ctx.save();ctx.fillStyle='rgba(0,0,0,.34)';ctx.beginPath();ctx.ellipse(x+2*sc,y+5*sc,6.4*b*sc,2.5*sc,0,0,Math.PI*2);ctx.fill();ctx.translate(x,y);ctx.rotate((home?1:-1)*lean);ctx.lineCap='round';ctx.strokeStyle='#191d1b';ctx.lineWidth=2.25*sc;ctx.beginPath();ctx.moveTo(-2.2*b*sc,-1*sc);ctx.lineTo((-2.3-stride)*b*sc,8.8*sc);ctx.moveTo(2.2*b*sc,-1*sc);ctx.lineTo((2.3+stride)*b*sc,8.8*sc);ctx.stroke();ctx.fillStyle=c.s;ctx.fillRect(-4.8*b*sc,-3*sc,9.6*b*sc,4.8*sc);let gr=ctx.createLinearGradient(-5*sc,-15*sc,5*sc,-3*sc);gr.addColorStop(0,c.j);gr.addColorStop(1,c.j2);ctx.fillStyle=gr;ctx.beginPath();ctx.moveTo(-4.8*b*sc,-14.5*sc);ctx.quadraticCurveTo(0,-16*sc,4.8*b*sc,-14.5*sc);ctx.lineTo(5.4*b*sc,-3*sc);ctx.lineTo(-5.4*b*sc,-3*sc);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(0,0,0,.34)';ctx.lineWidth=.65;ctx.stroke();ctx.fillStyle='#c98f68';ctx.beginPath();ctx.arc(0,-18.3*sc,3.2*sc,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#c98f68';ctx.lineWidth=2.1*sc;let arm=run?Math.sin(cycle+1.5)*4:po==='scrum'||po==='ruck'?6:po==='tackle'?8.5:po==='carry'?1.5:2.5;ctx.beginPath();ctx.moveTo(-4.2*b*sc,-11*sc);ctx.lineTo((-6-arm)*b*sc,-5*sc);ctx.moveTo(4.2*b*sc,-11*sc);ctx.lineTo((6+arm)*b*sc,-5*sc);ctx.stroke();if(sc>.56){ctx.fillStyle=c.num;ctx.font=`700 ${Math.max(5,6.2*sc)}px Arial`;ctx.textAlign='center';ctx.fillText(n,0,-7*sc)}ctx.restore()}
function drawBall(ctx,e,prev,w,h,p,ts){let t=norm(e?.type),ci=carrierIndex(e),start=proj(prev?.x??50,prev?.y??50,w,h),end=proj(e?.x??50,e?.y??50,w,h),u=sm(clamp(p*1.25,0,1)),x=lerp(start.x,end.x,u),y=lerp(start.y,end.y,u),arc=0;if(t.includes('PIED')||t.includes('DROP'))arc=72*Math.sin(Math.PI*u);else if(t.includes('PASSE'))arc=18*Math.sin(Math.PI*u);else if(t.includes('TOUCHE'))arc=34*Math.sin(Math.PI*u);y-=arc;ctx.save();ctx.translate(x,y);ctx.rotate(ts*.012);ctx.fillStyle='#eee3c7';ctx.strokeStyle='#483321';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(0,0,5.2*end.s,2.55*end.s,.25,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}
function fx(ctx,e,w,h,p){let t=norm(e?.type),q=proj(e?.x??50,e?.y??50,w,h);if(t.includes('RUCK')&&p>.35){ctx.fillStyle='rgba(215,197,157,.12)';ctx.beginPath();ctx.ellipse(q.x,q.y,26*q.s,8*q.s,0,0,Math.PI*2);ctx.fill()}if(t.includes('PERCUSSION')&&p>.58&&p<.84){ctx.strokeStyle=`rgba(245,225,165,${.5-(Math.abs(p-.71)*1.7)})`;ctx.lineWidth=2;ctx.beginPath();ctx.arc(q.x,q.y,10+18*(p-.58),0,Math.PI*2);ctx.stroke()}if(t.includes('ESSAI')&&p>.72){ctx.save();ctx.textAlign='center';ctx.font='900 34px Arial';ctx.fillStyle='rgba(247,226,159,.95)';ctx.shadowColor='#000';ctx.shadowBlur=10;ctx.fillText('ESSAI',w/2,h*.29);ctx.restore()}}
function frame(ts){let inf=info();if(!inf){raf=requestAnimationFrame(frame);return}let{ctx,w,h}=inf,m=state.match,e=evt(),pr=evt(2);if(m&&m.index!==lastIdx){lastIdx=m.index;phaseStart=performance.now()}let p=actionProgress(e);stadium(ctx,w,h);if(m){let hc=club(m.homeId),ac=club(m.awayId),hl=fifteen(hc),al=fifteen(ac),actors=[];for(let i=0;i<15;i++){let a=subShape(true,i,e,p),b=subShape(false,i,e,p);actors.push({p:hl[i],n:i+1,home:true,pt:proj(a[0],a[1],w,h),att:e?.home===true,i});actors.push({p:al[i],n:i+1,home:false,pt:proj(b[0],b[1],w,h),att:e?.home===false,i})}actors.sort((a,b)=>a.pt.y-b.pt.y);actors.forEach(a=>drawPlayer(ctx,a.p,a.n,a.home,a.pt,e?.type,a.att,a.i,ts,p));drawBall(ctx,e,pr,w,h,p,ts);fx(ctx,e,w,h,p)}raf=requestAnimationFrame(frame)}
function score(m,h,a){return `<div class="prm9-score"><span class="team h">${h.short}</span><b>${m.hs}</b><i>${m.minute}'</i><b>${m.as}</b><span class="team a">${a.short}</span></div>`}
function liveSel(label,key,vals){let cur=state.save?.tactics?.[key]||'';return `<label><span>${label}</span><select onchange="liveTacticChange('${key}',this.value)">${vals.map(v=>`<option ${v===cur?'selected':''}>${v}</option>`).join('')}</select></label>`}
function side(c,home){let f=fifteen(c);return `<aside class="prm9-side ${home?'home':'away'}"><header>${home?'DOMICILE':'EXTÉRIEUR'} <b>${c.short}</b></header>${f.map((p,i)=>`<div><i>${i+1}</i><span><b>${p?.last||'—'}</b><small>${p?.pos||''}</small></span><em>${Math.round(p?.fitness||90)}</em></div>`).join('')}</aside>`}
function controls(){return `<div class="prm9-controls"><button class="play" onclick="toggleLive()">${state.match?.running?'Ⅱ':'▶'}</button><button onclick="stepMatch()">▸|</button><button onclick="state.prm9Camera='tv';render()" class="${state.prm9Camera==='tv'?'active':''}">TV</button><button onclick="state.prm9Camera='follow';render()" class="${state.prm9Camera==='follow'?'active':''}">Suivi</button><button onclick="state.prm9Camera='sideline';render()" class="${state.prm9Camera==='sideline'?'active':''}">Latérale</button><button onclick="state.prm9Camera='high';render()" class="${state.prm9Camera==='high'?'active':''}">Haute</button><span class="spacer"></span>${liveSel('Attaque','attack',['Équilibré','Jeu au large','Jeu direct','Occupation'])}${liveSel('Défense','defense',['Glissée','Montée agressive','Blitz','Inversée'])}${liveSel('Jeu au pied','kick',['Relance','Alternance','Occupation','Pression aérienne'])}</div>`}
matchView=function(){let m=state.match,h=club(m.homeId),a=club(m.awayId),e=evt();return `<div class="prm9-shell">${score(m,h,a)}<div class="prm9-main">${side(h,true)}<section class="prm9-stage"><canvas id="prm9-canvas"></canvas><div class="prm9-phase"><b>${e?.type||"COUP D'ENVOI"}</b><span>${e?.text||'Les équipes se mettent en place.'}</span></div></section>${side(a,false)}</div>${controls()}<div class="prm9-footer"><button onclick="instantResult()">Résultat instantané</button><span>RUGBY LEGACY · moteur match V0.9</span>${m.finished?`<button class="finish" onclick="commitMatch()">Continuer la saison</button>`:''}</div></div>`};
const oldRender=render;render=function(){oldRender();cancelAnimationFrame(raf);raf=requestAnimationFrame(frame)};
render();
})();
