/* Rugby Legacy v1.1 — major PRM-inspired match upgrade: club kits, broadcast camera, richer choreography, sound */
(()=>{
'use strict';
const V='1.1.0';
if(typeof RL_DATA!=='undefined') RL_DATA.version=V;
if(typeof DB!=='undefined') DB.version=V;
state.prm11Camera=state.prm11Camera||'auto';
state.prm11Speed=state.prm11Speed||1;
state.prm11Sound=state.prm11Sound||false;
state.prm11Bench=state.prm11Bench||false;
let raf=0,lastIdx=-1,phaseStart=performance.now(),cam={x:50,y:50,z:1,tilt:.18},audioCtx=null;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),lerp=(a,b,t)=>a+(b-a)*t;
const ease=t=>t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
const POS=['PIL','TAL','PIL','2L','2L','3L','3L','3L','9','10','AIL','C','C','AIL','AR'];
const KIT={
 'Stade Toulousain':['#d11425','#111111'],'Union Bordeaux-Bègles':['#6d1732','#ffffff'],'Stade Rochelais':['#f4cc19','#111111'],'RC Toulon':['#d30f22','#111111'],'ASM Clermont':['#f4dc23','#194b9b'],'Aviron Bayonnais':['#6eb5df','#ffffff'],'Montpellier HR':['#194b8f','#ffffff'],'Castres Olympique':['#2567a7','#ffffff'],'Racing 92':['#87d0ec','#ffffff'],'Stade Français Paris':['#e98abb','#233e92'],'LOU Rugby':['#c8102e','#111111'],'Section Paloise':['#179d55','#ffffff'],'USA Perpignan':['#d3122a','#f1d225'],'RC Vannes':['#101010','#ffffff'],
 'Provence Rugby':['#111111','#d7aa42'],'Oyonnax':['#d31b25','#111111'],'Brive':['#111111','#ffffff'],'Montauban':['#1c8c52','#111111'],'Grenoble':['#d52232','#17478f'],'Valence Romans':['#d52232','#ffffff'],'Biarritz':['#d51c29','#ffffff'],'Aurillac':['#d51f2c','#2c5b8f'],'Dax':['#d6202b','#ffffff'],'Nissa':['#d52432','#111111'],'Soyaux-Angoulême':['#6d1b57','#ffffff'],'Narbonne':['#ef6a20','#111111'],'Nevers':['#f1d219','#1d4a95'],'Colomiers':['#1b66b2','#ffffff'],'Béziers':['#d52331','#22599a'],'Agen':['#1b5fa5','#ffffff']
};
function ev(off=1){const m=state.match;if(!m)return null;return m.events[Math.max(0,m.index-off)]||{x:50,y:50,type:"COUP D'ENVOI",home:true,text:'Coup d’envoi',m:0}}
function fifteen(c){if(state.save&&c.id===state.save.clubId&&state.save.lineup?.length===15)return state.save.lineup.map(id=>c.players.find(p=>p.id===id)).filter(Boolean).slice(0,15);let used=new Set(),out=[];for(const pos of POS){let p=c.players.filter(x=>!used.has(x.id)&&x.pos===pos).sort((a,b)=>(b.ca||0)-(a.ca||0))[0]||c.players.filter(x=>!used.has(x.id)).sort((a,b)=>(b.ca||0)-(a.ca||0))[0];if(p){used.add(p.id);out.push(p)}}return out}
function bench(c){if(!state.save||c.id!==state.save.clubId)return[];const used=new Set(state.save.lineup||[]);return (state.save.bench||[]).map(id=>c.players.find(p=>p.id===id)).filter(p=>p&&!used.has(p.id)).slice(0,8)}
function hash(s){let h=0;for(const ch of (s||''))h=(h*31+ch.charCodeAt(0))>>>0;return h}
function kit(c,home){if(KIT[c.name])return{j:KIT[c.name][0],s:KIT[c.name][1],sock:KIT[c.name][0],num:'#fff'};let h=hash(c.name)%360;return{j:`hsl(${h} 62% 42%)`,s:home?'#171a18':'#ededeb',sock:`hsl(${h} 62% 42%)`,num:'#fff'}}
function body(p){const pos=p?.pos||'C',h=clamp((p?.height||185)/185,.87,1.17),w=clamp((p?.weight||95)/95,.80,1.28),bulk=['PIL','TAL'].includes(pos)?1.18:['2L','3L'].includes(pos)?1.08:['9','AIL'].includes(pos)?.92:1;return{h,w:w*bulk}}
function duration(t){t=norm(t);if(t.includes('MELEE'))return 6000;if(t.includes('TOUCHE'))return 5200;if(t.includes('RUCK')||t.includes('TURNOVER'))return 5000;if(t.includes('PERCUSSION'))return 4500;if(t.includes('PIED')||t.includes('DROP'))return 4000;if(t.includes('ESSAI'))return 4800;if(t.includes('PASSE'))return 4100;return 3400}
function progress(e){return clamp((performance.now()-phaseStart)/(duration(e?.type)/state.prm11Speed),0,1)}
function micro(t,p){t=norm(t);if(t.includes('PASSE'))return p<.15?'FIXATION':p<.38?'1RE PASSE':p<.62?'2E PASSE':p<.82?'LARGEUR':'RECEPTION';if(t.includes('PERCUSSION'))return p<.30?'COURSE':p<.47?'IMPACT':p<.64?'PLAQUAGE':p<.80?'CHUTE':'SOUTIEN';if(t.includes('RUCK')||t.includes('TURNOVER'))return p<.18?'ARRIVEE':p<.40?'NETTOYAGE':p<.64?'CONTEST':p<.82?'BALLON SECURISE':'SORTIE DU 9';if(t.includes('MELEE'))return p<.16?'MISE EN PLACE':p<.32?'LIAISON':p<.62?'POUSSEE':p<.82?'STABILISATION':'SORTIE DU 8/9';if(t.includes('TOUCHE'))return p<.20?'ALIGNEMENT':p<.40?'LANCER':p<.60?'SAUT':p<.76?'CAPTURE':'LANCEMENT';if(t.includes('PIED')||t.includes('DROP'))return p<.22?'PREPARATION':p<.38?'FRAPPE':p<.74?'VOL':'CHASE';if(t.includes('ESSAI'))return p<.66?'COURSE':p<.84?'PLONGEON':'APLATIR';return p<.72?'JEU COURANT':'REPLACEMENT'}
function carrier(e){const t=norm(e?.type);if(t.includes('MELEE')||t.includes('RUCK')||t.includes('TURNOVER'))return 8;if(t.includes('PIED')||t.includes('DROP'))return 9;if(t.includes('TOUCHE'))return 3;if(t.includes('PERCUSSION'))return 11;if(t.includes('ESSAI'))return 13;if(t.includes('PASSE'))return 9;return 12}
function baseShape(home,i,e){const bx=e?.x??50,by=e?.y??50,t=norm(e?.type),att=e?.home===home,dir=home?1:-1,pack=i<8;let x=50,y=50;
 if(t.includes('MELEE')){if(pack){const rows=[[0,1,2],[3,4,5,6],[7]],r=rows.findIndex(a=>a.includes(i)),ix=rows[r].indexOf(i),n=rows[r].length;x=bx-dir*(1.3+r*2.0);y=by+(ix-(n-1)/2)*3.2}else if(i===8){x=bx-dir*6;y=by+3}else{x=bx-dir*(10+(i-9)*4.2);y=10+(i-9)*16}}
 else if(t.includes('TOUCHE')){const edge=by<50?10:90,sg=by<50?1:-1;if(pack){x=bx+(i%2?.75:-.75);y=edge+sg*(5.5+i*4.2)}else if(i===8){x=bx-dir*5;y=edge+sg*17}else{x=bx-dir*(8+(i-9)*4);y=14+(i-9)*14}}
 else if(t.includes('RUCK')||t.includes('TURNOVER')||t.includes('PERCUSSION')){if(i<4){x=bx-dir*(1.0+Math.floor(i/2)*1.7);y=by+(i%2?2:-2)}else if(pack){x=bx-dir*(5+(i-3)*2.2);y=by+(i-5.5)*6.4}else if(i===8){x=bx-dir*5.3;y=by+2.8}else{x=bx-dir*(8+(i-9)*4.3);y=8+(i-9)*15.6}}
 else if(t.includes('PIED')||t.includes('DROP')){if(i===9){x=bx-dir*4;y=by}else if(i===8){x=bx-dir*7;y=by+3}else{x=(att?bx-dir*(7+(i%5)*4):bx+dir*(11+(i%5)*3));y=7+(i*6.2)%86}}
 else{if(pack){const pod=i<3?0:i<6?1:2,slot=i<3?i:i<6?i-3:i-6;x=att?bx-dir*(4+pod*5):bx+dir*(6+pod*4);y=by+(slot-1)*7+pod*4}else if(i===8){x=bx-dir*5;y=by+2}else{x=att?bx-dir*(9+(i-9)*4.2):bx+dir*(9+(i-9)*3.8);y=9+(i-9)*15.5}}
 return[clamp(x,1,99),clamp(y,2,98)]}
function actionShape(home,i,e,p){let [x,y]=baseShape(home,i,e),t=norm(e?.type),att=e?.home===home,dir=home?1:-1,bx=e?.x??50,by=e?.y??50;
 if(t.includes('PASSE')&&att){const chain=[9,11,12,13],stage=Math.min(3,Math.floor(p*4));if(i===chain[stage]){x=bx-dir*(7-stage*2);y=by+(stage-1.5)*7}if(i>8){x+=dir*(p*4);y+=(i%2?1:-1)*p*2}}
 if(t.includes('PERCUSSION')){const ci=11,di=att?11:12;if(att&&i===ci){x=bx-dir*(8*(1-Math.min(p/.48,1)));y=by}if(!att&&i===di){x=bx+dir*(7*(1-Math.min(p/.48,1)));y=by+1}if(p>.62&&((att&&i===ci)||(!att&&i===di))){x=bx+(att?-dir:dir)*(1-p)*2;y=by}}
 if(t.includes('RUCK')||t.includes('TURNOVER')){let a=ease(clamp((p-.08)/.55,0,1));if(i<6||i===8){let [tx,ty]=baseShape(home,i,e),sx=tx-dir*(7+i*.35),sy=ty+(i-2.5)*2.3;x=lerp(sx,tx,a);y=lerp(sy,ty,a)}if(i===8&&att&&p>.79){x=bx-dir*(6-(p-.79)*18);y=by+2.5}}
 if(t.includes('MELEE')){const push=(p>.30&&p<.77)?Math.sin((p-.30)/.47*Math.PI)*2:0;x+=(att?dir:-dir)*push;if(i===8&&att&&p>.82)x=bx-dir*(6-(p-.82)*20)}
 if(t.includes('TOUCHE')){if((i===3||i===4)&&p>.34&&p<.70){const j=Math.sin(clamp((p-.34)/.36,0,1)*Math.PI);y+=(by<50?1:-1)*j*1.8;x+=j*.25}if(att&&i===8&&p>.76)x+=dir*(p-.76)*10}
 if((t.includes('PIED')||t.includes('DROP'))&&att&&i===9)x=bx-dir*(4-2.8*Math.min(p/.42,1));
 if(t.includes('ESSAI')&&att&&i===13){x=bx-dir*(8*(1-Math.min(p/.72,1)));if(p>.72)y+=Math.sin((p-.72)/.28*Math.PI)*1.1}
 return[clamp(x,0,100),clamp(y,1,99)]}
function info(){const c=document.getElementById('prm11-canvas');if(!c)return null;const r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),w=Math.max(360,r.width),h=Math.max(250,r.height);if(c.width!==Math.round(w*d)||c.height!==Math.round(h*d)){c.width=Math.round(w*d);c.height=Math.round(h*d)}const ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);return{ctx,w,h}}
function cameraTarget(e,p){let t=norm(e?.type),x=e?.x??50,y=e?.y??50,z=1,tilt=.18;if(t.includes('MELEE')||t.includes('RUCK')||t.includes('PERCUSSION'))z=1.15;if(t.includes('TOUCHE')){y=e?.y<50?24:76;z=1.10}if(t.includes('PIED'))z=.92;if(t.includes('ESSAI'))z=1.17;if(state.prm11Camera==='high')z=.86;if(state.prm11Camera==='sideline'){z=1.18;tilt=.28}if(state.prm11Camera==='follow')z=1.20;return{x,y,z,tilt}}
function proj(px,py,w,h){const e=ev(),p=progress(e),tar=cameraTarget(e,p),follow=['auto','tv','follow'].includes(state.prm11Camera);cam.x=lerp(cam.x,follow?tar.x:50,.028);cam.y=lerp(cam.y,follow?tar.y:50,.022);cam.z=lerp(cam.z,tar.z,.03);cam.tilt=lerp(cam.tilt,tar.tilt,.025);const focus=(cam.x-50)*(state.prm11Camera==='follow'?.27:.18),x=clamp(px-focus,-10,110)/100,y=py/100;let topY=h*(.18+cam.tilt*.08),botY=h*.94,tl=w*(.12+cam.tilt*.15),tr=w*(.88-cam.tilt*.15),bl=w*.005,br=w*.995;if(state.prm11Camera==='high'){topY=h*.10;tl=w*.06;tr=w*.94}const yy=lerp(topY,botY,y),l=lerp(tl,bl,y),r=lerp(tr,br,y),cx=w/2;return{x:cx+(lerp(l,r,x)-cx)*cam.z,y:yy,s:lerp(.44,1.34,y)*cam.z}}
function line(ctx,a,b,c,lw=1,d=[]){ctx.save();ctx.strokeStyle=c;ctx.lineWidth=lw;ctx.setLineDash(d);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore()}
function poly(ctx,pts,fill,stroke=null,lw=1){ctx.beginPath();pts.forEach((q,i)=>i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}}
function stadium(ctx,w,h){ctx.clearRect(0,0,w,h);let sky=ctx.createLinearGradient(0,0,0,h*.27);sky.addColorStop(0,'#131714');sky.addColorStop(1,'#3b403d');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h*.28);ctx.fillStyle='#292e2b';ctx.fillRect(0,h*.01,w,h*.15);ctx.fillStyle='#0b0e0c';ctx.fillRect(0,h*.15,w,h*.045);for(let y=0;y<12;y++)for(let x=0;x<w;x+=7){if(((x/7+y)|0)%5!==0){ctx.fillStyle=['#bdb9ae','#737c76','#c9a84f','#dad7ce','#5d655f'][((x/7+y)|0)%5];ctx.fillRect(x+(y%2)*2,7+y*4,2.1,2.1)}}ctx.fillStyle='#111411';ctx.fillRect(0,h*.188,w,h*.028);for(let x=0;x<w;x+=105){ctx.fillStyle=x%210?'#dbbd60':'#e6e6e1';ctx.font='700 8px Arial';ctx.fillText(x%210?'RUGBY LEGACY':'SPORT PRO',x+6,h*.207)}let a=proj(0,0,w,h),b=proj(100,0,w,h),c=proj(100,100,w,h),d=proj(0,100,w,h),g=ctx.createLinearGradient(0,a.y,0,d.y);g.addColorStop(0,'#4a8039');g.addColorStop(.5,'#559449');g.addColorStop(1,'#356d2e');poly(ctx,[a,b,c,d],g,'rgba(255,255,255,.88)',1.2);for(let i=0;i<10;i+=2)poly(ctx,[proj(i*10,0,w,h),proj((i+1)*10,0,w,h),proj((i+1)*10,100,w,h),proj(i*10,100,w,h)],'rgba(255,255,255,.025)');[0,22,40,50,60,78,100].forEach(v=>line(ctx,proj(v,0,w,h),proj(v,100,w,h),'rgba(255,255,255,.76)',v===50?1.5:.9));[10,90].forEach(v=>line(ctx,proj(0,v,w,h),proj(100,v,w,h),'rgba(255,255,255,.30)',.7,[4,6]));posts(ctx,3,50,w,h);posts(ctx,97,50,w,h)}
function posts(ctx,x,y,w,h){let p=proj(x,y,w,h),s=p.s;ctx.strokeStyle='#f3f1e8';ctx.lineWidth=Math.max(1,1.3*s);ctx.beginPath();ctx.moveTo(p.x-5*s,p.y);ctx.lineTo(p.x-5*s,p.y-36*s);ctx.moveTo(p.x+5*s,p.y);ctx.lineTo(p.x+5*s,p.y-36*s);ctx.moveTo(p.x-5*s,p.y-23*s);ctx.lineTo(p.x+5*s,p.y-23*s);ctx.stroke()}
function pose(type,att,i,p){let t=norm(type);if(t.includes('MELEE'))return i<8?'scrum':'ready';if(t.includes('TOUCHE'))return (i===3||i===4)&&p>.32&&p<.72?'jump':'ready';if(t.includes('RUCK')||t.includes('TURNOVER'))return i<5?(p<.38?'arrive':'ruck'):'ready';if(t.includes('PERCUSSION')){if(att&&i===11)return p>.64?'fall':'carry';if(!att&&i===12)return p>.47?'tackle':'run'}if(t.includes('ESSAI')&&att&&i===13)return p>.73?'dive':'carry';if((t.includes('PIED')||t.includes('DROP'))&&att&&i===9)return'kick';return'run'}
function drawPlayer(ctx,p,n,home,pt,type,att,i,ts,prog,colors){let pr=body(p),sc=pt.s*pr.h,b=pr.w,po=pose(type,att,i,prog),run=['run','carry','arrive'].includes(po),cy=ts*.017+i*1.8,stride=run?Math.sin(cy)*4.5:po==='kick'?6.5:0,bob=run?Math.abs(Math.sin(cy))*1.25:0,lean=po==='scrum'?.82:po==='ruck'?.76:po==='tackle'?.92:po==='fall'?1.30:po==='dive'?1.42:po==='kick'?.24:po==='carry'?.15:.07,x=pt.x,y=pt.y+bob*sc;ctx.save();ctx.fillStyle='rgba(0,0,0,.36)';ctx.beginPath();ctx.ellipse(x+2*sc,y+5*sc,6.7*b*sc,2.5*sc,0,0,Math.PI*2);ctx.fill();ctx.translate(x,y);ctx.rotate((home?1:-1)*lean);ctx.lineCap='round';ctx.strokeStyle='#171b19';ctx.lineWidth=2.3*sc;ctx.beginPath();ctx.moveTo(-2.2*b*sc,-1*sc);ctx.lineTo((-2.4-stride)*b*sc,9*sc);ctx.moveTo(2.2*b*sc,-1*sc);ctx.lineTo((2.4+stride)*b*sc,9*sc);ctx.stroke();ctx.fillStyle=colors.s;ctx.fillRect(-4.9*b*sc,-3*sc,9.8*b*sc,4.9*sc);let grad=ctx.createLinearGradient(-5*sc,-15*sc,5*sc,-3*sc);grad.addColorStop(0,colors.j);grad.addColorStop(1,'#111');ctx.fillStyle=grad;ctx.beginPath();ctx.moveTo(-4.7*b*sc,-14*sc);ctx.quadraticCurveTo(0,-16*sc,4.7*b*sc,-14*sc);ctx.lineTo(5.4*b*sc,-3*sc);ctx.lineTo(-5.4*b*sc,-3*sc);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(255,255,255,.16)';ctx.lineWidth=.8;ctx.stroke();ctx.fillStyle='#c88d67';ctx.beginPath();ctx.arc(0,-18*sc,3.2*sc,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#c88d67';ctx.lineWidth=2.0*sc;let arm=run?Math.sin(cy+1.5)*4:po==='scrum'||po==='ruck'?6:po==='tackle'?8.5:po==='carry'?2:2.5;ctx.beginPath();ctx.moveTo(-4*b*sc,-11*sc);ctx.lineTo((-6-arm)*b*sc,-5*sc);ctx.moveTo(4*b*sc,-11*sc);ctx.lineTo((6+arm)*b*sc,-5*sc);ctx.stroke();if(sc>.57){ctx.fillStyle=colors.num;ctx.font=`bold ${Math.max(5,6.4*sc)}px Arial`;ctx.textAlign='center';ctx.fillText(n,0,-7*sc)}ctx.restore()}
function ballPos(e,p,home,w,h){let t=norm(e?.type),bx=e?.x??50,by=e?.y??50,dir=home?1:-1,x=bx,y=by,z=0;if(t.includes('PASSE')){let seg=Math.min(2,Math.floor(p*3)),u=(p*3)%1;x=bx-dir*(7-seg*2)+dir*u*3;y=by+(seg-1)*7+u*7;z=Math.sin(Math.PI*u)*12}else if(t.includes('PIED')||t.includes('DROP')){x=bx-dir*(4-35*p);y=by;z=Math.sin(Math.PI*p)*75}else if(t.includes('TOUCHE')){x=bx;y=by<50?10+24*p:90-24*p;z=Math.sin(Math.PI*p)*42}else if(t.includes('MELEE')||t.includes('RUCK')){x=bx-dir*(p>.80?(p-.80)*25:0);y=by+2}else if(t.includes('PERCUSSION')){x=bx-dir*(6*(1-Math.min(p/.5,1)));y=by;z=p<.55?6:1}else if(t.includes('ESSAI')){x=bx-dir*(6*(1-Math.min(p/.74,1)));y=by;z=p<.8?5:0}else{x=bx;y=by;z=4}let q=proj(x,y,w,h);return{x:q.x,y:q.y-z*q.s,s:q.s}}
function drawBall(ctx,e,p,w,h,ts){let home=e?.home!==false,q=ballPos(e,p,home,w,h);ctx.save();ctx.translate(q.x,q.y);ctx.rotate(ts*.012);ctx.fillStyle='#eee4c8';ctx.strokeStyle='#3e2f20';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(0,0,5*q.s,2.6*q.s,.2,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}
function effects(ctx,e,p,w,h){let t=norm(e?.type),q=proj(e?.x??50,e?.y??50,w,h);if((t.includes('RUCK')||t.includes('PERCUSSION'))&&p>.48){ctx.fillStyle='rgba(213,198,161,.13)';ctx.beginPath();ctx.ellipse(q.x,q.y,27*q.s,8*q.s,0,0,Math.PI*2);ctx.fill()}if(t.includes('MELEE')&&p>.28&&p<.84){ctx.strokeStyle='rgba(244,228,176,.30)';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(q.x,q.y,27*q.s,10*q.s,0,0,Math.PI*2);ctx.stroke()}if(t.includes('ESSAI')&&p>.82){ctx.save();ctx.textAlign='center';ctx.font='900 38px Arial';ctx.fillStyle='rgba(249,229,160,.96)';ctx.shadowColor='#000';ctx.shadowBlur=12;ctx.fillText('ESSAI',w/2,h*.30);ctx.restore()}}
function ensureAudio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}
function beep(freq,dur,gain=.025){if(!state.prm11Sound)return;ensureAudio();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;g.gain.value=gain;o.connect(g).connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.stop(audioCtx.currentTime+dur)}
function noise(dur=.08,gain=.025){if(!state.prm11Sound)return;ensureAudio();let b=audioCtx.createBuffer(1,Math.floor(audioCtx.sampleRate*dur),audioCtx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);let s=audioCtx.createBufferSource(),g=audioCtx.createGain();s.buffer=b;g.gain.value=gain;s.connect(g).connect(audioCtx.destination);s.start()}
function eventSound(e){let t=norm(e?.type);if(t.includes('PENAL')||t.includes('ESSAI')){beep(920,.09,.035);setTimeout(()=>beep(1180,.14,.03),100)}else if(t.includes('PERCUSSION')||t.includes('RUCK')||t.includes('MELEE'))noise(.10,.032);else if(t.includes('PIED'))beep(420,.06,.018)}
window.togglePrm11Sound=function(){state.prm11Sound=!state.prm11Sound;if(state.prm11Sound){ensureAudio();beep(760,.08,.02)}render()};
window.setPrm11Camera=function(v){state.prm11Camera=v;render()};window.setPrm11Speed=function(v){state.prm11Speed=+v;state.matchSpeed=+v;if(window.restartLive)restartLive();render()};window.togglePrm11Bench=function(){state.prm11Bench=!state.prm11Bench;render()};
function frame(ts){let inf=info();if(!inf){raf=requestAnimationFrame(frame);return}let{ctx,w,h}=inf,m=state.match,e=ev(),prev=ev(2);if(m&&m.index!==lastIdx){lastIdx=m.index;phaseStart=performance.now();eventSound(e)}stadium(ctx,w,h);if(m&&e){let p=progress(e),hc=club(m.homeId),ac=club(m.awayId),hl=fifteen(hc),al=fifteen(ac),actors=[];for(let i=0;i<15;i++){for(const home of [true,false]){let arr=home?hl:al,now=actionShape(home,i,e,p),before=baseShape(home,i,prev||e),blend=ease(clamp(p/.30,0,1)),xy=[lerp(before[0],now[0],blend),lerp(before[1],now[1],blend)];actors.push({home,i,p:arr[i],pt:proj(xy[0],xy[1],w,h),att:e.home===home})}}actors.sort((a,b)=>a.pt.y-b.pt.y);for(const a of actors)drawPlayer(ctx,a.p,a.i+1,a.home,a.pt,e.type,a.att,a.i,ts,p,kit(a.home?hc:ac,a.home));drawBall(ctx,e,p,w,h,ts);effects(ctx,e,p,w,h)}raf=requestAnimationFrame(frame)}
function fatigue(p,m,i){return clamp(Math.round((p?.fitness||94)-(m/80)*(['PIL','TAL','2L','3L'].includes(p?.pos)?15:11)-(i%4)),45,100)}
function side(c,home){return `<div class="prm11-sidehead"><span>${home?'DOMICILE':'EXTÉRIEUR'}</span><b>${c.short}</b></div>${fifteen(c).map((p,i)=>{let en=fatigue(p,state.match?.minute||0,i);return `<div class="prm11-row"><em>${i+1}</em><span><b>${p?.last||'—'}</b><small>${p?.pos||''}</small></span><i><u style="width:${en}%"></u></i><strong>${en}</strong></div>`}).join('')}`}
function benchPanel(c){if(!state.save||c.id!==state.save.clubId)return'';let ln=fifteen(c),bn=bench(c);return `<div class="prm11-bench ${state.prm11Bench?'open':''}"><div class="prm11-benchhead"><b>REMPLACEMENTS</b><span>${state.match?.subs?.length||0}/8 utilisés</span></div><div class="prm11-sub"><select id="prm11-out">${ln.map((p,i)=>`<option value="${p.id}">${i+1}. ${p.last} · ${p.pos}</option>`).join('')}</select><select id="prm11-in">${bn.map((p,i)=>`<option value="${p.id}">${16+i}. ${p.last} · ${p.pos} · ${p.ca}</option>`).join('')}</select><button onclick="subPlayerV6(document.getElementById('prm11-out').value,document.getElementById('prm11-in').value)">Effectuer</button></div></div>`}
function liveSel(label,key,vals){let cur=state.save?.tactics?.[key]||'';return `<label><span>${label}</span><select onchange="liveTacticChange('${key}',this.value)">${vals.map(v=>`<option ${v===cur?'selected':''}>${v}</option>`).join('')}</select></label>`}
function radar(e){return `<div class="prm11-radar"><i></i><b></b><span style="left:${e?.x??50}%;top:${e?.y??50}%"></span></div>`}
matchView=function(){let m=state.match,h=club(m.homeId),a=club(m.awayId),e=ev(),p=progress(e),sub=micro(e?.type,p);return `<div class="prm11-wrap"><div class="prm11-top"><div class="team"><span>${h.short}</span><b>${h.name}</b></div><div class="score"><small>${m.minute}'</small><strong>${m.hs}<i>:</i>${m.as}</strong><em>${m.finished?'TERMINÉ':'2MT'}</em></div><div class="team away"><b>${a.name}</b><span>${a.short}</span></div></div><div class="prm11-tools"><div><button class="${state.view==='3d'?'on':''}" onclick="state.view='3d';render()">3D</button><button class="${state.view==='2d'?'on':''}" onclick="state.view='2d';render()">2D</button><button class="${state.prm11Sound?'on':''}" onclick="togglePrm11Sound()">${state.prm11Sound?'🔊':'🔇'}</button></div><div>${['auto','follow','sideline','high'].map(v=>`<button class="${state.prm11Camera===v?'on':''}" onclick="setPrm11Camera('${v}')">${v==='auto'?'TV':v==='follow'?'Suivi':v==='sideline'?'Latérale':'Haute'}</button>`).join('')}</div></div><div class="prm11-grid"><aside>${side(h,true)}</aside><section class="prm11-stage">${state.view==='3d'?'<canvas id="prm11-canvas"></canvas>':`<div class="prm11-2d"><div class="match-pitch">${typeof matchDots==='function'?matchDots():''}</div></div>`}<div class="prm11-phase"><b>${e?.type||'COUP D’ENVOI'}</b><span>${sub}</span><small>${e?.text||''}</small></div><div class="prm11-brand">RUGBY LEGACY</div></section><aside>${side(a,false)}</aside></div><div class="prm11-play"><button class="main" onclick="toggleLive()">${m.running?'Ⅱ':'▶'}</button><button onclick="stepMatch()">▸|</button>${[1,2,4].map(v=>`<button class="${state.prm11Speed===v?'on':''}" onclick="setPrm11Speed(${v})">×${v}</button>`).join('')} ${radar(e)}<b class="phase">${sub}</b><button onclick="instantResult()">Résultat instantané</button></div><div class="prm11-tactics"><button onclick="togglePrm11Bench()">Remplacement</button><button onclick="liveTacticChange('attack','Jeu direct')">Avants</button><button onclick="liveTacticChange('attack','Équilibré')">Centres</button><button onclick="liveTacticChange('attack','Jeu au large')">Ailes</button><button onclick="liveTacticChange('attack','Équilibré')">Équilibre</button>${liveSel('Défense','defense',['Glissée','Montée agressive','Blitz','Inversée'])}${liveSel('Jeu au pied','kick',['Relance','Alternance','Occupation','Pression aérienne'])}</div>${benchPanel(h)}${m.finished?`<div class="prm11-final"><b>${h.short} ${m.hs} - ${m.as} ${a.short}</b><button class="btn" onclick="commitMatch()">Continuer la saison</button></div>`:''}</div>`};
const oldRender=render;render=function(){oldRender();cancelAnimationFrame(raf);raf=requestAnimationFrame(frame)};
render();
})();
