/* Rugby Legacy v1.0 — multi-system PRM-style match overhaul */
(()=>{
'use strict';
const V='1.0.0';
if(typeof RL_DATA!=='undefined') RL_DATA.version=V;
if(typeof DB!=='undefined') DB.version=V;
state.prm10Camera=state.prm10Camera||'tv';
state.prm10Speed=state.prm10Speed||1;
state.prm10Bench=state.prm10Bench||false;
let raf=0,lastIdx=-1,phaseStart=performance.now(),cam={x:50,y:50,z:1};
const POS=['PIL','TAL','PIL','2L','2L','3L','3L','3L','9','10','AIL','C','C','AIL','AR'];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const lerp=(a,b,t)=>a+(b-a)*t;
const ease=t=>t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2;
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
const C={home:{j:'#d1a234',j2:'#8f6515',sh:'#101713',sock:'#d1a234',num:'#fff0b0'},away:{j:'#c42b34',j2:'#78181e',sh:'#ededeb',sock:'#c42b34',num:'#fff'}};
function ev(off=1){const m=state.match;if(!m)return null;return m.events[Math.max(0,m.index-off)]||{x:50,y:50,type:"COUP D'ENVOI",home:true,text:'Coup d’envoi',m:0}}
function fifteen(c){if(state.save&&c.id===state.save.clubId&&state.save.lineup?.length===15)return state.save.lineup.map(id=>c.players.find(p=>p.id===id)).filter(Boolean).slice(0,15);let used=new Set(),out=[];for(const pos of POS){let p=c.players.filter(x=>!used.has(x.id)&&x.pos===pos).sort((a,b)=>(b.ca||0)-(a.ca||0))[0]||c.players.filter(x=>!used.has(x.id)).sort((a,b)=>(b.ca||0)-(a.ca||0))[0];if(p){used.add(p.id);out.push(p)}}return out}
function bench(c){if(!state.save||c.id!==state.save.clubId)return[];const used=new Set(state.save.lineup||[]);return (state.save.bench||[]).map(id=>c.players.find(p=>p.id===id)).filter(p=>p&&!used.has(p.id)).slice(0,8)}
function body(p){const pos=p?.pos||'C',h=clamp((p?.height||185)/185,.88,1.16),w=clamp((p?.weight||95)/95,.80,1.25);return{h,w:w*(['PIL','TAL'].includes(pos)?1.13:['2L','3L'].includes(pos)?1.06:['9','AIL'].includes(pos)?.93:1)}}
function duration(t){t=norm(t);if(t.includes('MELEE'))return 5200;if(t.includes('TOUCHE'))return 4600;if(t.includes('RUCK')||t.includes('TURNOVER'))return 4200;if(t.includes('PERCUSSION'))return 3900;if(t.includes('PIED')||t.includes('DROP'))return 3600;if(t.includes('ESSAI'))return 4300;if(t.includes('PASSE'))return 3200;return 3000}
function progress(e){return clamp((performance.now()-phaseStart)/(duration(e?.type)/state.prm10Speed),0,1)}
function micro(t,p){t=norm(t);if(t.includes('PERCUSSION'))return p<.32?'COURSE':p<.52?'CONTACT':p<.70?'PLAQUAGE':p<.84?'SOL':'SOUTIEN';if(t.includes('RUCK')||t.includes('TURNOVER'))return p<.22?'ARRIVEE':p<.45?'NETTOYAGE':p<.72?'CONTEST':p<.88?'STABILISE':'SORTIE 9';if(t.includes('PASSE'))return p<.22?'ARMEMENT':p<.58?'PASSE':p<.78?'BALLON':'RECEPTION';if(t.includes('MELEE'))return p<.20?'MISE EN PLACE':p<.36?'LIAISON':p<.64?'POUSSEE':p<.84?'STABILISATION':'SORTIE';if(t.includes('TOUCHE'))return p<.22?'ALIGNEMENT':p<.43?'LANCER':p<.62?'SAUT':p<.78?'CAPTURE':'LANCEMENT';if(t.includes('PIED')||t.includes('DROP'))return p<.25?'PREPARATION':p<.43?'FRAPPE':p<.75?'VOL':p<.90?'CHASE':'RECEPTION';if(t.includes('ESSAI'))return p<.60?'COURSE':p<.82?'PLONGEON':'APLATIR';return p<.7?'JEU COURANT':'REPLACEMENT'}
function carrier(e){const t=norm(e?.type);if(t.includes('MELEE')||t.includes('RUCK')||t.includes('TURNOVER'))return 8;if(t.includes('PIED')||t.includes('DROP'))return 9;if(t.includes('TOUCHE'))return 3;if(t.includes('PERCUSSION'))return 11;if(t.includes('ESSAI'))return 13;if(t.includes('PASSE'))return 11;return 12}
function receiver(e){const c=carrier(e);return c===14?13:Math.min(14,c+1)}
function baseShape(home,i,e){const bx=e?.x??50,by=e?.y??50,t=norm(e?.type),att=e?.home===home,dir=home?1:-1,pack=i<8;let x=50,y=50;
 if(t.includes('MELEE')){if(pack){const rows=[[0,1,2],[3,4,5,6],[7]],r=rows.findIndex(a=>a.includes(i)),ix=rows[r].indexOf(i),n=rows[r].length;x=bx-dir*(1.4+r*2.15);y=by+(ix-(n-1)/2)*3.45}else if(i===8){x=bx-dir*6.2;y=by+3}else{x=bx-dir*(10+(i-9)*4.1);y=11+(i-9)*15.5}}
 else if(t.includes('TOUCHE')){const edge=by<50?9:91,sg=by<50?1:-1;if(pack){x=bx+(i%2?.85:-.85);y=edge+sg*(6+i*4.35)}else if(i===8){x=bx-dir*5;y=edge+sg*17}else{x=bx-dir*(9+(i-9)*3.8);y=15+(i-9)*13.8}}
 else if(t.includes('RUCK')||t.includes('TURNOVER')||t.includes('PERCUSSION')){if(i<4){x=bx-dir*(1.1+Math.floor(i/2)*1.9);y=by+(i%2?2.1:-2.1)}else if(pack){x=bx-dir*(5+(i-3)*2.25);y=by+(i-5.5)*6.4}else if(i===8){x=bx-dir*5.2;y=by+2.8}else{x=bx-dir*(8.5+(i-9)*4.15);y=8+(i-9)*15.4}}
 else if(t.includes('PIED')||t.includes('DROP')){if(i===9){x=bx-dir*3.8;y=by}else if(i===8){x=bx-dir*7;y=by+3}else{x=(att?bx-dir*(7+(i%5)*4.1):bx+dir*(11+(i%5)*3.1));y=7+(i*6.2)%86}}
 else if(t.includes('ESSAI')){x=att?bx-dir*(1+i*1.0):bx+dir*(4+i*.72);y=8+(i*6.1)%84}
 else{if(pack){const pod=i<3?0:i<6?1:2,slot=i<3?i:i<6?i-3:i-6;x=att?bx-dir*(4+pod*5):bx+dir*(6+pod*4);y=by+(slot-1)*7+pod*5}else if(i===8){x=bx-dir*5;y=by+2}else{x=att?bx-dir*(9+(i-9)*4.35):bx+dir*(9+(i-9)*3.85);y=10+(i-9)*15}}
 return[clamp(x,2,98),clamp(y,3,97)]}
function actionShape(home,i,e,p){let [x,y]=baseShape(home,i,e),t=norm(e?.type),att=e?.home===home,dir=home?1:-1,ci=carrier(e),ri=receiver(e),bx=e?.x??50,by=e?.y??50;
 if(t.includes('PASSE')){if(att&&i===ci){x=bx-dir*(7*(1-Math.min(p/.58,1)));y=by-4*(1-p)}else if(att&&i===ri){x=bx+dir*(4+3*p);y=by+7*(1-p)}else if(i>8)x+=dir*(p*2.2)}
 if(t.includes('PERCUSSION')){if(att&&i===ci){x=bx-dir*(8*(1-Math.min(p/.55,1)));if(p>.52)y+=Math.sin((p-.52)/.48*Math.PI)*.7}else if(!att&&i===11){x=bx+dir*(7*(1-Math.min(p/.52,1)));y=by+1.0}if(p>.72&&((att&&i===ci)||(!att&&i===11)))x=bx+dir*(att?-1:1)*(.9-p)*2}
 if(t.includes('RUCK')||t.includes('TURNOVER')){const arrive=ease(clamp((p-.12)/.52,0,1));if(i<5||i===8){const [tx,ty]=baseShape(home,i,e),sx=tx-dir*(6+i*.45),sy=ty+(i-2)*2.4;x=lerp(sx,tx,arrive);y=lerp(sy,ty,arrive)}if(i===8&&att&&p>.78){x=bx-dir*(6-(p-.78)*15);y=by+2.8}}
 if(t.includes('MELEE')){const push=(p>.34&&p<.78)?Math.sin((p-.34)/.44*Math.PI)*1.7:0;x+=(att?dir:-dir)*push;if(i===8&&att&&p>.82)x=bx-dir*(6-(p-.82)*20)}
 if(t.includes('TOUCHE')){if((i===3||i===4)&&p>.35&&p<.72){const j=Math.sin(clamp((p-.35)/.37,0,1)*Math.PI);x+=j*.2;y+=(by<50?1:-1)*j*1.5}if(att&&i===8&&p>.78)x+=dir*(p-.78)*9}
 if((t.includes('PIED')||t.includes('DROP'))&&att&&i===9){x=bx-dir*(4-2.7*Math.min(p/.45,1))}
 if(t.includes('ESSAI')&&att&&i===ci){x=bx-dir*(7*(1-Math.min(p/.75,1)));if(p>.74)y+=Math.sin((p-.74)/.26*Math.PI)*1.0}
 return[clamp(x,1,99),clamp(y,2,98)]}
function canvasInfo(){const c=document.getElementById('prm10-canvas');if(!c)return null;const r=c.getBoundingClientRect(),d=Math.min(window.devicePixelRatio||1,1.9),w=Math.max(340,r.width),h=Math.max(240,r.height);if(c.width!==Math.round(w*d)||c.height!==Math.round(h*d)){c.width=Math.round(w*d);c.height=Math.round(h*d)}const ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);return{c,ctx,w,h}}
function cameraTarget(e,p){let x=e?.x??50,y=e?.y??50,t=norm(e?.type),z=1;if(t.includes('MELEE')||t.includes('RUCK')||t.includes('PERCUSSION'))z=1.08;if(t.includes('TOUCHE')){y=e?.y<50?20:80;z=1.05}if(t.includes('PIED'))z=.94;if(t.includes('ESSAI'))z=1.10;if(state.prm10Camera==='high')z=.88;if(state.prm10Camera==='sideline')z=1.13;if(state.prm10Camera==='follow')z=1.12;return{x,y,z}}
function proj(px,py,w,h){const e=ev(),p=progress(e),tar=cameraTarget(e,p);const follow=state.prm10Camera==='tv'||state.prm10Camera==='follow';cam.x=lerp(cam.x,follow?tar.x:50,.035);cam.y=lerp(cam.y,follow?tar.y:50,.03);cam.z=lerp(cam.z,tar.z,.035);const focus=(cam.x-50)*(state.prm10Camera==='follow'?.24:.16),x=clamp(px-focus,-8,108)/100,y=py/100;let topY=h*.20,botY=h*.93,tl=w*.13,tr=w*.87,bl=w*.01,br=w*.99;if(state.prm10Camera==='high'){topY=h*.11;tl=w*.07;tr=w*.93}if(state.prm10Camera==='sideline'){topY=h*.27;tl=w*.22;tr=w*.78}const yy=lerp(topY,botY,y),l=lerp(tl,bl,y),r=lerp(tr,br,y),cx=w/2;return{x:cx+(lerp(l,r,x)-cx)*cam.z,y:yy,s:lerp(.47,1.32,y)*cam.z}}
function line(ctx,a,b,c,lw=1,d=[]){ctx.save();ctx.strokeStyle=c;ctx.lineWidth=lw;ctx.setLineDash(d);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore()}
function poly(ctx,pts,fill,stroke=null,lw=1){ctx.beginPath();pts.forEach((q,i)=>i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=lw;ctx.stroke()}}
function posts(ctx,x,y,w,h){const p=proj(x,y,w,h),s=p.s;ctx.strokeStyle='#f4f1e8';ctx.lineWidth=Math.max(1,1.25*s);ctx.beginPath();ctx.moveTo(p.x-5*s,p.y);ctx.lineTo(p.x-5*s,p.y-35*s);ctx.moveTo(p.x+5*s,p.y);ctx.lineTo(p.x+5*s,p.y-35*s);ctx.moveTo(p.x-5*s,p.y-23*s);ctx.lineTo(p.x+5*s,p.y-23*s);ctx.stroke()}
function stadium(ctx,w,h){ctx.clearRect(0,0,w,h);let sky=ctx.createLinearGradient(0,0,0,h*.27);sky.addColorStop(0,'#0b1210');sky.addColorStop(1,'#313835');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h*.28);ctx.fillStyle='#262d29';ctx.fillRect(0,h*.02,w,h*.13);ctx.fillStyle='#0b0e0c';ctx.fillRect(0,h*.145,w,h*.045);for(let y=0;y<10;y++)for(let x=0;x<w;x+=7){if(((x/7+y)|0)%5!==0){ctx.fillStyle=['#b8b7ae','#707a74','#c3a450','#d6d5cd','#6b715e'][((x/7+y)|0)%5];ctx.fillRect(x+(y%2)*2,8+y*4,2,2)}}ctx.fillStyle='#121512';ctx.fillRect(0,h*.184,w,h*.027);for(let x=0;x<w;x+=115){ctx.fillStyle=x%230?'#dabd63':'#e2e3df';ctx.font='700 8px Arial';ctx.fillText(x%230?'RUGBY LEGACY':'SPORT',x+8,h*.202)}const a=proj(0,0,w,h),b=proj(100,0,w,h),c=proj(100,100,w,h),d=proj(0,100,w,h);let g=ctx.createLinearGradient(0,a.y,0,d.y);g.addColorStop(0,'#4d813c');g.addColorStop(.48,'#579846');g.addColorStop(1,'#34702e');poly(ctx,[a,b,c,d],g,'rgba(255,255,255,.85)',1.2);for(let i=0;i<10;i+=2)poly(ctx,[proj(i*10,0,w,h),proj((i+1)*10,0,w,h),proj((i+1)*10,100,w,h),proj(i*10,100,w,h)],'rgba(255,255,255,.023)');[0,22,40,50,60,78,100].forEach(v=>line(ctx,proj(v,0,w,h),proj(v,100,w,h),'rgba(255,255,255,.72)',v===50?1.35:.8));[5,10,90,95].forEach(v=>line(ctx,proj(0,v,w,h),proj(100,v,w,h),'rgba(255,255,255,.28)',.65,[4,6]));posts(ctx,3,50,w,h);posts(ctx,97,50,w,h)}
function pose(type,att,i,p){const t=norm(type),ci=carrier({type}),ri=receiver({type});if(t.includes('MELEE'))return i<8?(p<.35?'bind':p<.82?'scrum':'rise'):'ready';if(t.includes('TOUCHE'))return (i===3||i===4)&&p>.34&&p<.72?'jump':'ready';if(t.includes('RUCK')||t.includes('TURNOVER'))return i<4?(p<.3?'arrive':'ruck'):i===8&&att&&p>.78?'pass':'ready';if(t.includes('PERCUSSION')){if(att&&i===ci)return p>.68?'fall':'carry';if(!att&&i===11)return p>.48?'tackle':'run';return'run'}if(t.includes('PASSE')){if(att&&i===ci)return p<.58?'pass':'ready';if(att&&i===ri)return p>.66?'catch':'run';return'run'}if(t.includes('ESSAI'))return att&&i===ci&&p>.74?'dive':'run';if(t.includes('PIED')||t.includes('DROP'))return att&&i===9&&p<.56?'kick':'chase';return'run'}
function drawHuman(ctx,p,n,home,pt,type,att,i,ts,pg){const kit=home?C.home:C.away,pr=body(p),sc=pt.s*pr.h,b=pr.w,po=pose(type,att,i,pg),run=['run','chase','carry','arrive','catch'].includes(po),cy=ts*.018+i*1.9,stride=run?Math.sin(cy)*4.5:po==='kick'?6.5:0,bob=run?Math.abs(Math.sin(cy))*1.15:0;let lean=po==='scrum'?.82:po==='bind'?.55:po==='ruck'?.78:po==='tackle'?.95:po==='fall'?1.32:po==='dive'?1.42:po==='kick'?.22:po==='carry'?.13:po==='pass'?.08:.06;const x=pt.x,y=pt.y+bob*sc;ctx.save();ctx.fillStyle='rgba(0,0,0,.36)';ctx.beginPath();ctx.ellipse(x+2*sc,y+5*sc,6.6*b*sc,2.5*sc,0,0,Math.PI*2);ctx.fill();ctx.translate(x,y);ctx.rotate((home?1:-1)*lean);ctx.lineCap='round';ctx.strokeStyle='#171b19';ctx.lineWidth=2.25*sc;ctx.beginPath();ctx.moveTo(-2.2*b*sc,-1*sc);ctx.lineTo((-2.4-stride)*b*sc,9*sc);ctx.moveTo(2.2*b*sc,-1*sc);ctx.lineTo((2.4+stride)*b*sc,9*sc);ctx.stroke();ctx.strokeStyle=kit.sock;ctx.lineWidth=1.7*sc;ctx.beginPath();ctx.moveTo((-2.4-stride)*b*sc,5.8*sc);ctx.lineTo((-2.4-stride)*b*sc,9*sc);ctx.moveTo((2.4+stride)*b*sc,5.8*sc);ctx.lineTo((2.4+stride)*b*sc,9*sc);ctx.stroke();ctx.fillStyle=kit.sh;ctx.fillRect(-5*b*sc,-3*sc,10*b*sc,4.8*sc);const gr=ctx.createLinearGradient(-6*sc,-16*sc,6*sc,-3*sc);gr.addColorStop(0,kit.j);gr.addColorStop(1,kit.j2);ctx.fillStyle=gr;ctx.beginPath();ctx.moveTo(-4.8*b*sc,-14*sc);ctx.quadraticCurveTo(0,-16.2*sc,4.8*b*sc,-14*sc);ctx.lineTo(5.5*b*sc,-3*sc);ctx.lineTo(-5.5*b*sc,-3*sc);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(0,0,0,.34)';ctx.lineWidth=.65;ctx.stroke();ctx.fillStyle='#c98f68';ctx.beginPath();ctx.arc(0,-18.3*sc,3.2*sc,0,Math.PI*2);ctx.fill();let arm=run?Math.sin(cy+1.5)*4:po==='ruck'||po==='scrum'||po==='bind'?6:po==='tackle'?9:po==='pass'?7:po==='catch'?6:3;ctx.strokeStyle='#c98f68';ctx.lineWidth=2.0*sc;ctx.beginPath();ctx.moveTo(-4*b*sc,-11*sc);ctx.lineTo((-6-arm)*b*sc,-5*sc);ctx.moveTo(4*b*sc,-11*sc);ctx.lineTo((6+arm)*b*sc,-5*sc);ctx.stroke();if(sc>.56){ctx.fillStyle=kit.num;ctx.font=`bold ${Math.max(5,6.4*sc)}px Arial`;ctx.textAlign='center';ctx.fillText(n,0,-7*sc)}if((po==='carry'||po==='pass')&&att){ctx.fillStyle='#e8dec3';ctx.strokeStyle='#4a3724';ctx.lineWidth=.7;ctx.beginPath();ctx.ellipse((home?6:-6)*b*sc,-7*sc,3.8*sc,1.9*sc,.25,0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.restore()}
function ballPos(e,pr,p){const t=norm(e?.type),dir=e?.home?1:-1,bx=e?.x??50,by=e?.y??50;if(t.includes('PASSE')){const s=[bx-dir*5,by-3],r=[bx+dir*5,by+4],u=ease(clamp((p-.28)/.5,0,1));return{x:lerp(s[0],r[0],u),y:lerp(s[1],r[1],u),z:Math.sin(Math.PI*u)*10}}if(t.includes('PIED')||t.includes('DROP')){const u=ease(clamp((p-.38)/.5,0,1));return{x:lerp(pr?.x??50,bx,u),y:lerp(pr?.y??50,by,u),z:Math.sin(Math.PI*u)*42}}if(t.includes('TOUCHE')){const u=ease(clamp((p-.35)/.38,0,1));return{x:bx,y:by<50?lerp(8,28,u):lerp(92,72,u),z:Math.sin(Math.PI*u)*18}}if(t.includes('RUCK')||t.includes('TURNOVER')||t.includes('MELEE'))return{x:bx-dir*(p>.82?3:0),y:by,z:1};return{x:bx,y:by,z:2}}
function drawBall(ctx,e,pr,w,h,p,ts){const bp=ballPos(e,pr,p),pt=proj(bp.x,bp.y,w,h);ctx.save();ctx.translate(pt.x,pt.y-bp.z*pt.s);ctx.rotate(ts*.013);ctx.fillStyle='#eee5ca';ctx.strokeStyle='#493724';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(0,0,5.2*pt.s,2.65*pt.s,.25,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}
function fx(ctx,e,w,h,p){const t=norm(e?.type),pt=proj(e?.x??50,e?.y??50,w,h);if((t.includes('RUCK')||t.includes('PERCUSSION')||t.includes('TURNOVER'))&&p>.45){ctx.fillStyle=`rgba(215,198,158,${.05+.08*Math.sin(p*Math.PI)})`;ctx.beginPath();ctx.ellipse(pt.x,pt.y,26*pt.s,8*pt.s,0,0,Math.PI*2);ctx.fill()}if(t.includes('MELEE')&&p>.32&&p<.84){ctx.strokeStyle='rgba(247,228,171,.22)';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(pt.x,pt.y,26*pt.s,10*pt.s,0,0,Math.PI*2);ctx.stroke()}if(t.includes('ESSAI')&&p>.78){ctx.save();ctx.textAlign='center';ctx.font='900 38px Arial';ctx.fillStyle=`rgba(249,226,149,${clamp((p-.78)/.15,0,1)})`;ctx.shadowColor='#000';ctx.shadowBlur=12;ctx.fillText('ESSAI',w/2,h*.29);ctx.restore()}}
function frame(ts){const inf=canvasInfo();if(!inf){raf=requestAnimationFrame(frame);return}const {ctx,w,h}=inf,m=state.match,e=ev(),pr=ev(2);if(m&&m.index!==lastIdx){lastIdx=m.index;phaseStart=performance.now()}const pg=progress(e);stadium(ctx,w,h);if(m){const hc=club(m.homeId),ac=club(m.awayId),hl=fifteen(hc),al=fifteen(ac),actors=[];for(let i=0;i<15;i++){const ha=actionShape(true,i,e,pg),aa=actionShape(false,i,e,pg);actors.push({p:hl[i],n:i+1,home:true,att:e?.home===true,pt:proj(ha[0],ha[1],w,h),i});actors.push({p:al[i],n:i+1,home:false,att:e?.home===false,pt:proj(aa[0],aa[1],w,h),i})}actors.sort((a,b)=>a.pt.y-b.pt.y);actors.forEach(a=>drawHuman(ctx,a.p,a.n,a.home,a.pt,e?.type,a.att,a.i,ts,pg));drawBall(ctx,e,pr,w,h,pg,ts);fx(ctx,e,w,h,pg)}raf=requestAnimationFrame(frame)}
function side(c,home){const ln=fifteen(c);return `<div class="prm10-side-head"><span>${home?'DOM':'EXT'}</span><b>${c.short}</b></div>${ln.map((p,i)=>{const fit=Math.max(45,Math.round((p?.fitness||90)-(state.match?.minute||0)*(['PIL','TAL','2L','3L'].includes(p?.pos)?.28:.21)));return `<div class="prm10-row"><em>${i+1}</em><span><b>${p?.last||'—'}</b><small>${p?.pos||POS[i]}</small></span><i><u style="width:${fit}%"></u></i><strong>${fit}</strong></div>`}).join('')}`}
function benchPanel(c){if(!state.save||c.id!==state.save.clubId)return'';const ln=fifteen(c),bn=bench(c);return `<div class="prm10-bench ${state.prm10Bench?'open':''}"><div class="prm10-bench-title"><b>BANC / REMPLACEMENTS</b><button onclick="state.prm10Bench=false;render()">×</button></div><div class="prm10-sub"><label>Sortie<select id="v10out">${ln.map((p,i)=>`<option value="${p.id}">${i+1}. ${p.last} · ${p.pos}</option>`).join('')}</select></label><label>Entrée<select id="v10in">${bn.map((p,i)=>`<option value="${p.id}">${16+i}. ${p.last} · ${p.pos} · ${p.ca}</option>`).join('')}</select></label><button class="btn" onclick="prm10Sub()">Remplacer</button></div><div class="prm10-bench-list">${bn.map((p,i)=>`<span><b>${16+i}</b><i>${p.last}</i><small>${p.pos} · ${p.ca} · ${p.fitness||90}%</small></span>`).join('')}</div></div>`}
window.prm10Sub=function(){const o=document.getElementById('v10out')?.value,i=document.getElementById('v10in')?.value;if(window.subPlayerV6&&o&&i){subPlayerV6(o,i);state.prm10Bench=false;render()}};
window.prm10Tactic=function(kind,val){if(!state.save)return;const map={forwards:['attack',val==='Avants'?'Jeu direct':state.save.tactics.attack],centres:['width',val==='Centres'?'Mixte':state.save.tactics.width],wings:['width',val==='Ailes'?'Large':state.save.tactics.width],balance:['attack','Équilibré'],def:['defense',val],kick:['kick',val]};const pair=map[kind];if(pair){if(window.liveTacticChange)liveTacticChange(pair[0],pair[1]);else{state.save.tactics[pair[0]]=pair[1];saveLocal();render()}}};
function radar(m){const e=ev();return `<div class="prm10-radar"><span style="left:${e?.x??50}%;top:${e?.y??50}%"></span><i></i><b></b></div>`}
function controls(){const t=state.save?.tactics||{};return `<div class="prm10-tactics"><button onclick="state.prm10Bench=true;render()">Remplacement</button><button onclick="prm10Tactic('forwards','Avants')">Avants</button><button onclick="prm10Tactic('centres','Centres')">Centres</button><button onclick="prm10Tactic('wings','Ailes')">Ailes</button><button onclick="prm10Tactic('balance','Équilibre')">Équilibre</button><label>Défense<select onchange="prm10Tactic('def',this.value)">${['Glissée','Montée agressive','Blitz','Inversée'].map(v=>`<option ${v===t.defense?'selected':''}>${v}</option>`).join('')}</select></label><label>Jeu au pied<select onchange="prm10Tactic('kick',this.value)">${['Relance','Alternance','Occupation','Pression aérienne'].map(v=>`<option ${v===t.kick?'selected':''}>${v}</option>`).join('')}</select></label></div>`}
function matchMain(){const m=state.match,h=club(m.homeId),a=club(m.awayId),e=ev(),pg=progress(e),mic=micro(e?.type,pg);return `<div class="prm10-wrap"><div class="prm10-top"><div class="tm home"><span>${h.short}</span><b>${h.name}</b></div><div class="scr"><small>${m.minute}'</small><strong>${m.hs}<i>–</i>${m.as}</strong><em>${m.finished?'TERMINÉ':'EN DIRECT'}</em></div><div class="tm away"><b>${a.name}</b><span>${a.short}</span></div></div><div class="prm10-toolbar"><div><button class="${state.view==='2d'?'on':''}" onclick="state.view='2d';render()">2D</button><button class="${state.view==='3d'?'on':''}" onclick="state.view='3d';render()">3D PRM</button></div><div class="cams">${['tv','follow','sideline','high'].map(v=>`<button class="${state.prm10Camera===v?'on':''}" onclick="state.prm10Camera='${v}';render()">${v==='tv'?'TV':v==='follow'?'Suivi':v==='sideline'?'Latérale':'Haute'}</button>`).join('')}</div><div><button onclick="instantResult()">Résultat</button></div></div><div class="prm10-grid"><aside>${side(h,true)}</aside><section class="prm10-stage">${state.view==='3d'?'<canvas id="prm10-canvas"></canvas>':`<div class="prm10-2d"><div id="pitch" class="match-pitch">${matchDots()}</div></div>`}<div class="prm10-phase"><b>${e?.type||'COUP D’ENVOI'}</b><span>${mic}</span><small>${e?.text||''}</small></div><div class="prm10-brand">RUGBY LEGACY</div></section><aside>${side(a,false)}</aside></div><div class="prm10-play"><button class="main" onclick="toggleLive()">${m.running?'Ⅱ':'▶'}</button><button onclick="stepMatch()">▸|</button>${[1,2,4].map(v=>`<button class="${state.prm10Speed===v?'on':''}" onclick="state.prm10Speed=${v};state.matchSpeed=${v};restartLive()">×${v}</button>`).join('')}${radar(m)}<span class="phase-name">${mic}</span></div>${controls()}${benchPanel(h)}${m.finished?`<div class="prm10-final"><b>${h.short} ${m.hs} – ${m.as} ${a.short}</b><button class="btn" onclick="commitMatch()">Continuer</button></div>`:''}</div>`}
matchView=function(){return matchMain()};
const oldRender=render;render=function(){oldRender();cancelAnimationFrame(raf);if(state.page==='match'&&state.match&&state.view==='3d')raf=requestAnimationFrame(frame)};
render();
})();
